### ISSUE TITLE
In App PDF viewing

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#10]
# Summary
Supports PDFs: multi-page PDFs in Universal Viewer or other media player.

Hyku supports most of these file formats. Custom work relative to this requirement will include the functionality to delineate basic images for static viewing and the in-app viewing requirements for PDFs

They want in viewer highlighting, and for the search to go to the correct page. #139 

# Acceptance Criteria

- [ ] PDFs are supported

# Screenshots or Video

# Testing Instructions

# Notes
- Can we close this ticket, as we will be creating a feature flipper to view PDFs? #58 

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by DiemBTran** [comment]
Linked items:

- In viewer highlighting for Books

**Comment by jillpe** [comment]
covered in #358
