### ISSUE TITLE
Collections: IIIF Recipe

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#100]
# Summary
Over-arching Goal: Align IIIF manifests for collections with UTK's requirements.

UTK requires additional functionality in their IIIF Manifest to allow in viewer experience and use of the manifest in other applications.

This ticket builds off of the base IIIF manifest Recipe.

# Acceptance Criteria

- [ ] Collections should always have a type property equal to Collection and a viewingDirection of left-to-right.
- [ ] The behavior should be unordered.
- [ ] The items property includes each child with properties for id, type, label, thumbnail, and homepage.

# Screenshots or Video

# Testing Instructions

# Notes
[Collections IIIF Recipe](https://utk-iiif-cookbook.readthedocs.io/en/latest/contents/collections.html#iiif-manifest)

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by DiemBTran** [comment]
Kirk Oct 2022

---

https://iiif.io/api/presentation/3.0/#51-collection

Currently it looks like IIIF Manifest gem has some support for v3 Collections
https://github.com/samvera/iiif_manifest/blob/main/lib/iiif_manifest/v3/manifest_service_locator.rb#L24

There would need to be work done to bring in v3 specs

The `WorksControllerBehavior` trigger a manifest to be built, so something similar needs to exist for a collection manifest.

https://gitlab.com/notch8/utk-hyku/-/blob/main/app/controllers/concerns/hyrax/works_controller_behavior.rb#L24

**Comment by jillpe** [comment]
Closed - ticket created in first iteration of project and no longer relevant
