### ISSUE TITLE
Compound Objects: IIIF Recipe

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#101]
# Summary
Over-arching Goal: Align IIIF manifests for Compound Objects with UTK's requirements.

UTK requires additional functionality in their IIIF Manifest to allow in viewer experience and use of the manifest in other applications.

This ticket builds off of the base IIIF manifest Recipe.

# Acceptance Criteria

- [ ] The Compound Object has a behavior property, with its array including the string value individuals meaning that the included Canvases of the work are distinct views, and should not be presented in a page-turning interface.
- [ ] The items property can consist of many canvases.
- [ ] The Canvases, the contents of the canvas has properties like id, type, metadata, summary, rights, and requiredStatement, but the details of most property values are dictated by the work type of the Work the Canvas is based on. (Audio, Large Image, or Videos)

# Screenshots or Video
Screenshots can be accessed via the [link](https://utk-iiif-cookbook.readthedocs.io/en/latest/contents/compound_objects.html#iiif-manifest)

# Testing Instructions

# Notes
[Compound Objects IIIF Recipe](https://utk-iiif-cookbook.readthedocs.io/en/latest/contents/compound_objects.html#iiif-manifest)

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
related to #47

**Comment by jillpe** [comment]
Closed - ticket created in first iteration of project and no longer relevant
