### ISSUE TITLE
Creator drop down

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#104]
# Summary
UTK would like the creator field to be a drop down menu.

# Acceptance Criteria

- [ ] Creator field is a drop down

# Screenshots or Video
Example taken from British Library

![Image](https://user-images.githubusercontent.com/29311858/203170313-13d26606-26a7-4198-86c6-55c047cfe336.png)

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
No longer a priority per adjusted priority list 2023-04
