### ISSUE TITLE
Base Manifest: accompanyingCanvas

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#109]
# Summary

The accompanyingCanvas property is a single Canvas that provides additional content for use while rendering the resource.

# Acceptance Criteria

- [ ] manifest has a valid `accompanyingCanvas` property

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by DiemBTran** [comment]
Linked items:

Relates to:

- [5] Base Manifest: IIIF Recipe
- [8]Base Manifest: thumbnail

**Comment by jillpe** [comment]
Closed - ticket created in first iteration of project and no longer relevant
