### ISSUE TITLE
[utk-hyku] github.com/notch8/utk-hyku make rubocop to-do list for failing Cops

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#110]
Currently Hyku on main does not use Bixby. There will be work that will be done for this later in another project. Please make a todo list with the offending cops for now until that work can come from upstream Hyku proper.

Pre Reqs: 
Need access to the project located: https://github.com/notch8/utk-hyku

Acceptance criteria:
- [ ] There is a new rubocop todo file, or you have added to a pre-existing one.
- [ ] There are no more failing rubocop cops in the lint stage in CI

**Comment by jillpe** [comment]
Possibly relevant?
https://github.com/scientist-softserv/utk-hyku/blob/main/.rubocop_todo.yml

**Comment by jillpe** [comment]
@markpbaggett
