### ISSUE TITLE
manifest['summary'] test

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#112]
# Summary

https://gitlab.com/notch8/utk-hyku/-/merge_requests/122/diffs#ded76764d5240a20bb7d79cc5afd11f7a5872063_0_53

The above test was skipped to move the ticket forward. Outside of the testing environment, the `summary` field gets set just fine, however, in the testing environment it does not.

https://github.com/samvera/iiif_manifest/blob/935ae736ebbcca1f05bc031e4a290ffdc90addf9/lib/iiif_manifest/v3/manifest_builder.rb#L30

`obj` is an ActiveTriples relation instead of an Array which is causing `#obj_to_language_map` to return `nil`

# Acceptance Criteria

- [ ] the test passes

**Comment by DiemBTran** [comment]
Related MRs:

- [192-base-manifest](https://gitlab.com/notch8/utk-hyku/-/merge_requests/122)

**Comment by jillpe** [comment]
No longer relevant
