### ISSUE TITLE
[2] Spike: Houndstooth compatibility

### ISSUE THREAD

**Issue by crisr15** [notch8/utk-hyku#124]
In our client iteration meeting, Mark mentioned how even though allinson flex (aka flex) says it's based off of the houndstooth gem, the two gems are not 100% compatible with each other. 

[Houndstooth](https://github.com/samvera-labs/houndstooth) has a m3 profile generator. However, what it validates is considered not valid when importing it in with flex. 

Rob mentioned that there may be a WIP PR in houndstooth or flex about this issue. Search closed issues as well. We should try to find it and possibly finish it. He also mentioned that this may require 1-2 hrs of pairing with tamsin.

This ticket is for researching the above. A separate ticket should be created for implementation.

**Comment by crisr15** [comment]
Alisha:
open houndstooth pr's: https://github.com/samvera-labs/houndstooth/pulls

**Comment by crisr15** [comment]
Shana:
I wonder if this is because houndstooth has since been updated to reflect hyrax 3.0+ changes, and flex was not. 

In flex I found this [line](https://github.com/samvera-labs/allinson_flex/blob/c6ec00e90b9003b1e982766310528d98c616862e/lib/allinson_flex.rb#L13-L14), which points to using a very specific version/commit sha of houndstooth that I'm actually having trouble locating. But maybe pointing the version to main will resolve the discrepancies?

not raw version: 
https://github.com/samvera-labs/houndstooth/blob/f753864727a0ba743cb5ec47e88797435a0a596a/m3_json_schema.json

I am also noticing that in the flex repository, once constructed, the url flex builds (and is basing it's m3 profile on) is: https://raw.githubusercontent.com/samvera-labs/houndstooth/f753864727a0ba743cb5ec47e88797435a0a596a/m3_json_schema.json

The most up to date m3_json from houndstooth is available [here](https://raw.githubusercontent.com/samvera-labs/houndstooth/main/m3_json_schema.json), however the contexts block has been removed which may be a breaking change for flex if we were to update flex.

diff checker: https://www.diffchecker.com/diff


---

Turns out, julie had a specific branch called context. and that version is based off of it. Her commit message states: "Add support for contexts - properties and classes used in a specific". This branch was never merged into main. Maybe it should be? I will try to hunt down a MR.

UPDATE: no mr was found

I'm not confident about this but I created a MR: https://github.com/samvera-labs/houndstooth/compare/main...context

the [validate script](https://github.com/samvera-labs/houndstooth/blob/main/validate.rb#L6) is not using the json defined by allinson flex

**Comment by crisr15** [comment]
Shana: 
TODO:

Does flex require contexts or is it optional?

Post summary in local/s3 samvera channel
slack convo: https://assaydepot.slack.com/archives/G031E2NTA01/p1662756255953549

**Comment by crisr15** [comment]
Shana:
Contexts and mappings are not required.

https://github.com/samvera-labs/allinson_flex/blob/main/lib/generators/allinson_flex/templates/config/metadata_profile/default_schema.json#L6

**Comment by crisr15** [comment]
Shana: 
TODO: find out who the maintainer for houndstooth is to discuss next moves. (Chris Colvar and Tamsin are the ones most active recently): https://github.com/samvera-labs/houndstooth/graphs/contributors

Mappings and Contexts are not required for flex profiles. ref: https://github.com/samvera-labs/allinson_flex/blob/main/lib/generators/allinson_flex/templates/config/metadata_profile/default_schema.json#L6


Per the client iteration meeting, Mark will try using the context branch of houndstooth for validations. He'll report back if that resolves the observed discrepancies.

**Comment by crisr15** [comment]
Shana: 
Per discussions had during the [Allinson Flex meeting](https://docs.google.com/document/d/1fQ2XOSR1Dww6JEtk0Q5F-uJB136OKyEcD-HNoPfIqt0/edit#), we will proceed with our [PR](https://github.com/samvera-labs/houndstooth/pull/33/files) against houndstooth.

**Comment by crisr15** [comment]
Shana: 
PR was approved by daniel pierce after attending the samvera tech call.

I will update allinson flex, and our gemfile's version to call this done.

**Comment by crisr15** [comment]
Shana: Not QA-able. Client could test to see if the validator more accurately reflects flex. They are the ones who spotted this discrepancy.

**Comment by markpbaggett** [comment]
We found a few other issues that Shana was aware of, but we've just moved to using the schema defined in allinson flex, which we should have been doing from the beginning.
