### ISSUE TITLE
[3] Manually add additional properties to Collection

### ISSUE THREAD

**Issue by crisr15** [notch8/utk-hyku#126]
Per our last iteration meeting on 10/11/2022, the client agreed to not make allinson flex work with Collections. 

We will manually be adding any additional properties needed, to the Collection model.

Manually adding the collection metadata will allow us to still have the default behavior that comes with collections in hyrax, such as the collections show pages, and the search in collections

ref: notes from meeting - https://docs.google.com/document/d/18Bp1_mdXcVtFq1h8-nGA_97LL4n1YPO1TSX4rxweRCc/edit#

ref: notes from flex meeting - https://docs.google.com/document/d/1fQ2XOSR1Dww6JEtk0Q5F-uJB136OKyEcD-HNoPfIqt0/edit#heading=h.t2h1esit84hv

# Testing Instruction

- Create a collection and set the following properties
  - Title
  - Machine Readable Creation Date
  - Date issued
  - Machine Readable Publication Date
  - Extent
  - Form
  - Publication place
  - Repository
  - Spatial Coverage
  - Local Creator
  - Local Contributor
  - Local Publisher
- Check that the properties render on the show page
- Search for some of the terms you just set and observe that the Collection is found
- Bulkrax: Verify that collection metadata can be saved when imported via Bulkrax with this zip: [collection-with-image-with-attachment-row.zip](/uploads/1dda03e21ab20e8d08c6af1fc5792d29/collection-with-image-with-attachment-row.zip)

**Comment by DiemBTran** [comment]
From Meredith 2022-10-27 11:11 AM PT on Gitlab:

Noting here that two changes were made on the spreadsheet. License was removed and a new URI was selected for the property for form (http://purl.org/dc/terms/format) due to an oversight on our main MAP for work types. These are in addition to Tuesday's changes of removing rights and adding note. I will not make any other changes after today.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested on:
- collection created through UI: https://dc.utk-hyku-staging.notch8.cloud/collections/60da4263-7aa4-4388-83c4-c86d26054f91?locale=en
- csv for import: 
[collection-with-image-with-attachment-row (1).zip](https://github.com/scientist-softserv/utk-hyku/files/9882915/collection-with-image-with-attachment-row.1.zip)
- importer: https://dc.utk-hyku-staging.notch8.cloud/importers/18?locale=en
- imported collection: https://dc.utk-hyku-staging.notch8.cloud/collections/0a88bb37-7003-454b-84ca-5462f9c79a09?locale=en
[collection-with-image-with-attachment-row (1).zip](https://github.com/scientist-softserv/utk-hyku/files/9882912/collection-with-image-with-attachment-row.1.zip)

https://user-images.githubusercontent.com/29311858/198391218-341149e0-f948-4ff4-829d-32dc32884918.mp4

**Comment by ShanaLMoore** [comment]
Per the client's request, we will be updating the collection metadata again so the client can review this once #149 is complete.
