### ISSUE TITLE
Able to serve book-like objects in a IIIF manifest as a sequence of canvases with a viewing hint of “paged”

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#13]
# Summary
Universal Viewer will process the manifests this way if given the right data. Page-level metadata isn’t automatically generated by Hyrax/Hyku, so there is some custom configuration required by Notch8 to add page numbers to manifests.

# Acceptance Criteria

- [ ] Page numbers are added to manifests for books

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
covered in #358
