### ISSUE TITLE
Resolve Sentry Errors

### ISSUE THREAD

**Issue by crisr15** [notch8/utk-hyku#130]
UTK Sentry Errors:

Resolving the frequently seen errors to help clear up the error limit.
  
- [ ] NoMethodError: undefined method `propagate' for #<Hyrax::VisibilityPropagator::NullVisibilityPropogator:0x000055eb666d6878> Did you mean? propogate

- [ ] [NoMethodError](https://sentry.io/organizations/scientist-inc/issues/3597913959/?project=6745049&referrer=project-issue-stream): undefined method `log_profile_event' for nil:NilClass

**Comment by ShanaLMoore** [comment]
We will ignore the errors in sentry and create separate ticket, to handle each error properly vs hot fixing to mute them.
