### ISSUE TITLE
[8]Remove Hyrax::BasicMetadata

### ISSUE THREAD

**Issue by crisr15** [notch8/utk-hyku#131]
# Summary

Out of Hyrax::BasicMetadata, we need to determine which properties are absolutely necessary. Anything that is not should be handled by Allinson Flex. 

The small set of required metadata would then need to be defined on the model. Allinson Flex needs to skip handling these properties if they are defined on the model. 

# Acceptance Criteria

- [ ] Allinsonflex should define most of the properties of a model (minus the ones that are set on a model). 
- [ ] AllinsonFlex should ignore any properties defined on the model.
- [ ] Difference in yaml file and default field is documented

# Screenshots or Video

# Testing Instructions

# Notes

Ref notes from the [Allinson Flex meeting](https://docs.google.com/document/d/1fQ2XOSR1Dww6JEtk0Q5F-uJB136OKyEcD-HNoPfIqt0/edit#).

Relevant notes from the meeting: 

"There are “privileged/unique/foundational” properties in Hyrax (e.g. title, rights statement, possibly license, embargo, etc); Allinson flex should ignore properties already on the model.  We may need to tease out of Hyrax the subset of properties that are in BasicMetadata that are in fact required.  The BasicMetadata properties would then include the FundamentalProperites and AllinsonFlex implementations would include only the FundamentalProperites then mixin the YML configured properties.  (THere is a question of can things move out of fundamental to basic?, so that AllinsonFlex/M3 can be used to define things; this is a aspirational state)"

"4. Remove Hyrax::BasicMetadata? => spend a day or two to do this
#115 - This causes issues. As a quick recap, hyrax by default seems to expect these properties at the minimum and complained about not having xyz when we removed this module entirely. 
comments around removing “basic metadata” from each model: https://gitlab.com/notch8/utk-hyku/-/merge_requests/104#note_1070749145
We need to Find out which fields are mandatory (this may mean we need two modules Basic and Hyrax Mandatory; Basic always includes Mandatory but Allinson Flex could include only Mandatory)
May add property to model just to appease any errors - such as source"

**Comment by crisr15** [comment]
Shana: 
Hyrax has core metadata too. Once these fields are identified, should they just get moved to the core metadata module ? https://github.com/samvera/hyrax/blob/main/app/models/concerns/hyrax/core_metadata.rb

**Comment by laritakr** [comment]
Testing instructions: 

Changes should be mostly invisible... just testing for standard functionality.

- [x] Should be able to perform all normal functions on all work types without errors, both via UI and Bulkrax imports.
- [x] All of the work metadata fields as defined on Digital Collections map spreadsheet should be available.

**Comment by ShanaLMoore** [comment]
This passes QA: https://qa.utk-hyku-staging.notch8.cloud/importers/20?locale=en#work-entries

The user is still able to create works via bulkrax and manually. Client QA is not required as this was an internal concern.
