### ISSUE TITLE
Staging: NoMethodError undefined method `<=' for nil:NilClass

### ISSUE THREAD

**Issue by crisr15** [notch8/utk-hyku#139]
https://sentry.io/organizations/scientist-inc/issues/3680810550/?project=6745049&referrer=project-issue-stream

This error is related to the UV

**Comment by DiemBTran** [comment]
Related MRs:

- [Draft: i229 - Resolve sidekiq errors](https://gitlab.com/notch8/utk-hyku/-/merge_requests/154)

**Comment by jillpe** [comment]
closed - the issue no longer shows in sentry, re-report if there are errors
