### ISSUE TITLE
Spike: Staging: Faraday::TimeoutError:Net::ReadTimeout

### ISSUE THREAD

**Issue by crisr15** [notch8/utk-hyku#140]
Resolve sentry error caused by importing the following spreadsheet: 

[157-test.zip](https://github.com/scientist-softserv/utk-hyku/files/9873993/157-test.zip)

https://sentry.io/organizations/scientist-inc/issues/3642277279/?project=6745049&referrer=project-issue-stream

![Image](https://user-images.githubusercontent.com/29311858/203180792-09a7496f-b1c6-4f73-8b37-3b4977b10a38.png)

# Acceptance Criteria
- [ ] The above spreadsheet is imported
- [ ] A new ticket is created if the error still exists

**Comment by ShanaLMoore** [comment]
Retest running the above sample zip file to verify that this is still an issue

**Comment by jillpe** [comment]
~~closed no longer relevant~~

**Comment by jillpe** [comment]
Verify this if this is still an issue?

**Comment by jillpe** [comment]
No longer relevant
