### ISSUE TITLE
[3]Allinson Flex form does not show option to add another value

### ISSUE THREAD

**Issue by crisr15** [notch8/utk-hyku#142]
# Summary
Only Language and Subject fields show the `+ Add another` option on the `New Works` page. All true multi-value fields should be giving the option to add another value. 

Note that this is appearing correctly for edit. It only involves new works.

# Acceptance Criteria
Able to add multiple values when valid according to the metadata profile. 

The opposite should also be true, if a property can only have 1 it should not have the add button.

# Screenshots or Video

![Image](https://user-images.githubusercontent.com/29311858/203168367-e6ecb8e4-0e4e-4c65-838e-e69cbc9897ca.png)

# Testing Instructions
- [ ] Open a "New Work" window.
- [ ] Verify that `+ Add another` appears under the fields.

# Notes
This may need to be a fix on Hyku.

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by crisr15** [comment]
Jill: 
'More' shows in staging, but not in local

**Comment by crisr15** [comment]
[This is the code in Hyrax](https://github.com/samvera/hyrax/blob/94cd8e0d48991e0acdeccbbddef29749beaeae87/app/assets/javascripts/hyrax/editor/controlled_vocabulary.es6) which appears to handle showing the "Add another" option via the `controls-add-text` class.

**Comment by jillpe** [comment]
No longer necessary
