### ISSUE TITLE
Attachment work type should display in the parent's UV

### ISSUE THREAD

**Issue by crisr15** [notch8/utk-hyku#145]
# Summary

- [ ] If a work has an attachment (child work), its files should be displayed in the parent work's UV (as if Attachment were a file set). 
- [ ] The thumbnail of the parent work should be the attachment's first fileset

Sample metadata profile: [metadata-profile-v.38.0.yml](/uploads/eb24b511247fff48c3a7b4f7acb72051/metadata-profile-v.38.0.yml)

Sample bulkrax file: [audio-w-attachment.zip](/uploads/ba30bc86dfdc28ccbcdccbb69edf7c0d/audio-w-attachment.zip)

# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by ShanaLMoore** [comment]
Closing this ticket because it should be done when #83 is completed.
