### ISSUE TITLE
Spike: Is the graph indexer a part of hyrax upgrade in UTK?

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#154]
Using solr graph instead of fedora relationship nested indexing is a lot faster. This would allow for faster ingests.

**Comment by laritakr** [comment]
Relates to https://github.com/samvera/hyrax/pull/5850

**Comment by laritakr** [comment]
According to [comments on the MR linked above](https://github.com/samvera/hyrax/pull/5850#issuecomment-1244156991), they do not intend to backport the graph indexer into hyrax 3.x series, but rather put in deprecation notices. There is a reference to possibly implementing the query portion of the work, but the 3.x-stable branch does not appear to include any of these changes at this point. 

There is an i[n-progress pull request](https://github.com/samvera/hyrax/pull/5858) referring to the backport work.

I'm not certain of the implications re: us backporting it ourselves, but the code to do so seems manageable at first glance.  We would likely need to be in discussion with community members re: this implementation.

**Comment by ShanaLMoore** [comment]
Meeting with LaRita, Crystal, Jill and Jeremy:

Older Hyrax is running on deprecated rails with securities issues. Upgrading to Hyrax 4 with allinson flex may cause some challenges. 

We could fork hyrax off of 3.4.2 to make our own updates without the semantic changes. Will it be worth it?

**Comment by ShanaLMoore** [comment]
@laritakr I'm forgetting the outcome of this discussion during our planning meeting. 

Should we make an implementation ticket and close this, or do we need to have more discussion around it?

**Comment by laritakr** [comment]
I don't remember getting an answer from Rob regarding the issue with semantic versioning and how that would be handled. I think he (or someone) needed to talk with Tamsin re: why they decided NOT to move forward with the 3.x series. So yes I think more discussion is needed.

**Comment by ShanaLMoore** [comment]
Rob to review and make recommendations before closing this ticket.

**Comment by orangewolf** [comment]
I read through the code of the backport and left a comment there. Bumping Hyku from 3.4.1 to whatever 3.x release this would be if it were merged and released is a no brainer to me. 

Going up to 4.x is a _much_ bigger lift that we can do right now (it includes a Rails upgrade, Blacklight upgrade and a Boostrap upgrade). We need to do it eventually, but not before the end of the year. 

If Tamsin doesn't respond on getting the backport merged, we can simply update UTK hyku to point to this branch. But I'd rather update Hyku proper and pull that down in to this.

**Comment by ShanaLMoore** [comment]
TODO: 

Per planning mtg/Rob - If release is not cut within the next 48 hrs, point UTK's hyrax to this branch + add config variable

Rob to review two PRS:

https://github.com/samvera/hyrax/pull/5778

**Comment by laritakr** [comment]
Closed by https://github.com/scientist-softserv/utk-hyku/issues/188
