### ISSUE TITLE
Spike 3 - How can we make this into a gem?

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#157]
ref #83 

Should this be a gem or be work that goes back into hyrax/hyku?

IU is a hyrax app.

**Comment by ShanaLMoore** [comment]
# dev note

TODO: 

Schedule a planning meeting. Include Rob.

**Comment by ShanaLMoore** [comment]
Shana to pair with Rob on teasing out the pieces of the newspaper gem. 

A separate implementation meeting will be scheduled if it's required.

**Comment by ShanaLMoore** [comment]
todo: 

Rob has about an hr left of work before tickets will be available to work on

test gem against hyku since utk has allinson flex in place. 

- update keying off of neswpaperissue (iiif_print_upload_actor.rb)
  - if class' ancestors included SplitPdf

check in with jeremy => (derivative types get made all the time, hard to turn on/off)

**Comment by ShanaLMoore** [comment]
ref

**Comment by kirkkwang** [comment]
IIIF Print was created for this
