### ISSUE TITLE
Serves audio/visual objects via IIIF with transcripts following the IIIF Presentation API specification

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#16]
# Summary
This is custom work that Notch8 will undertake to make audio playback available by the Universal Viewer or similar media player. This is currently on the roadmap for multiple projects, so there may be community work in motion that we can utilize for Hyku.

# Acceptance Criteria

- [ ] Audio playback is available by the Universal Viewer

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by DiemBTran** [comment]
Linked items:

- Spike: how do we import their pbcore/annotation

**Comment by jillpe** [comment]
no longer in scope 2023-04-19
