### ISSUE TITLE
Bulkrax Import

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#17]
# Summary
Migrate approximately 15 TB of digital objects and over 330,000 digital objects (includes pages as objects based on Fedora 3.81 content modeling)

Notch8 will configure the Bulkrax gem as the primary tool for migration. Bulkrax will be configured to be mapped with appropriate work types that import files, metadata, relationships, and other settings into Hyku. The process will utilize background jobs to keep migration moving over a period of days or weeks, while consistently being monitored by the Notch8 team for interruptions or errors.

We will be importing from a URL on the web.

# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
covered in #47
