### ISSUE TITLE
AllinsonFlex: Create dynamic view partial automatically if it matches an authority

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#171]
# Summary
If a property is connected to a controlled vocabulary, it should be represented in the UI as a drop down of select-able options. 

This ticket may depend on #170 

# Acceptance Criteria

- [ ] If a property is connected to a controlled vocab, we should see it represented as a drop down of acceptable qa ([questioning authority](https://github.com/samvera/questioning_authority)) terms, instead of an input field. 
- [ ] The acceptable values will be seen once the user starts to type for them (aka: implement type ahead)

# Screenshots or Video

# Testing Instructions

# Notes

ref: [Allinson Flex x Controlled Values Meeting](https://docs.google.com/document/d/1PDZsGDeZUh9b7BrzsyprmRZOCT4GEwNCg5FXBzyRCUU/edit?usp=sharing)

**Comment by ShanaLMoore** [comment]
[Allinson Flex x Controlled Values Meeting](https://docs.google.com/document/d/1PDZsGDeZUh9b7BrzsyprmRZOCT4GEwNCg5FXBzyRCUU/edit?usp=sharing)

**Comment by jillpe** [comment]
No longer necessary
