### ISSUE TITLE
Bring in Hyrax graph indexer 

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#188]
### Descriptive summary

If branch not merged by 11/15, refer to branch from merge request https://github.com/samvera/hyrax/pull/5858

If Bixby update results in spec failures, this work can be spun off to another ticket. 

_Note: if branch is removed, build will break._

**Comment by ShanaLMoore** [comment]
This branch may get merged in Friday, 11/18 per [this comment](https://github.com/samvera/hyrax/pull/5858#issuecomment-1317407181)

**Comment by laritakr** [comment]
To QA ticket, verify ability to nest collections and works. 

- [ ] * Verify that collections can be nested within collections: Able to add new collection within collection. Able to add a collection into a collection, etc
- [ ] * Verify that works can be nested within collections and within works

All relationships that are verified above as working appear on the UI upon completion.

**Comment by ShanaLMoore** [comment]
This passes QA: 

- [x] Verify that collections can be nested within collections: Able to add new collection within collection. Able to add a collection into a collection, etc

![Image](https://user-images.githubusercontent.com/10081604/204394588-adeae6ad-8258-4564-8d41-1b1b38ca7a8f.png)


- [x] Verify that works can be nested within collections and within works


Added Collection to another collection and added work to collection
![Image](https://user-images.githubusercontent.com/10081604/204396155-f8eef402-2f46-4f8e-964f-66ae6eed1055.png)


Added work to another work
![Image](https://user-images.githubusercontent.com/10081604/204396211-f2ea895d-7c6f-4ea6-8155-3bcd5e80d386.png)

**Comment by laritakr** [comment]
This change did not actually turn on the graph indexer via environment variables. That is being handled by https://github.com/scientist-softserv/utk-hyku/pull/247

**Comment by ShanaLMoore** [comment]
client review not required
