### ISSUE TITLE
Bug: Clicking on contributor from Collection show pg causes 500 error

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#193]
Steps to Reproduce: 

Import CSV: [149-all-collection-metadata.csv](https://github.com/scientist-softserv/utk-hyku/files/10014015/149-all-collection-metadata.csv)

It creates a collection. Go to its show page.

Click contributor. 

In staging it'll lead to an invalid search: 

<img width="1430" alt="Screen Shot 2022-11-15 at 7 34 36 AM" src="https://user-images.githubusercontent.com/10081604/201960514-030bf342-e73b-487f-bbab-26a87670b73b.png">

Locally the error is: 
<img width="1439" alt="Screen Shot 2022-11-15 at 7 35 56 AM" src="https://user-images.githubusercontent.com/10081604/201960709-284419d7-bccd-4d62-98bb-620ceedeae2e.png">

**Comment by jillpe** [comment]
Example: https://dc.utk-hyku-staging.notch8.cloud/collections/c93b530a-2edf-457c-9a56-e07084c6a862?locale=en

**Comment by jillpe** [comment]
related to #394

**Comment by jillpe** [comment]
closed - contributor will not display on collection show page
