### ISSUE TITLE
EPIC: Allinson Flex Contolled Values

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#195]
# RELATED TICKETS
- [AllinsonFlex::DynamicSchema should save controlled_values#169](https://github.com/scientist-softserv/utk-hyku/issues/169)
- [Get a single authority working#212](https://github.com/scientist-softserv/utk-hyku/issues/212)
- [AllinsonFlex: Make a QA for each potential property#170](https://github.com/scientist-softserv/utk-hyku/issues/170)
- [Bulkrax: Reference controlled values from Allinson Flex#174](https://github.com/scientist-softserv/utk-hyku/issues/174)
- [AllinsonFlex: Create dynamic view partial automatically if it matches an authority#171](https://github.com/scientist-softserv/utk-hyku/issues/171)

### The following tickets were created after the Tamsin meeting...

Get a single authority working first: 
- [Set up instance of lark#196](https://github.com/scientist-softserv/utk-hyku/issues/196)
- [Create ability for qa to talk to Lark#197](https://github.com/scientist-softserv/utk-hyku/issues/197)
  - [LARK](https://gitlab.com/surfliner/surfliner/-/tree/trunk/lark-client)
- [Create way to map controlled value to a single QA (Questioning Authority) through a hyrax service#198](https://github.com/scientist-softserv/utk-hyku/issues/198)

[Get multiple authorities to work#201](https://github.com/scientist-softserv/utk-hyku/issues/201)

# NOTES 
Rob, Jeremy and Shana met with Tamsin to discuss Surfliner's implementation: [Meeting Minutes](https://docs.google.com/document/d/1rLDHufesIWh71unkeAeucVpPy5syFaeGWQXr3KucIfQ/edit)

**Comment by ShanaLMoore** [comment]
[UCSC](https://github.com/UCSCLibrary/ucsc-library-digital-collections) has the ability to choose from multiple QA in their forms. Refer to Kiah.

**Comment by ShanaLMoore** [comment]
start by trying to set up remote library of congress QA. Search the QA wiki. RIght now it may only assume local authorities. 

find a term that uses both lcsh and another authority, implement the property querying both either by UCSC dropdown or a QA aggregate that will show all authorities. 

how can flex do this dynamically?

this will store url but we will need the see label. We will want to index and store the label. Possible that we will write the label to fedora, solr, or our local db cached, or somehow dynamically get the label. We will need to revisit this when the time comes. 

QA will return uri and label. in the form object, we could add a property_label hidden field that shadows the uri property. property and property label should be sorted by Order Already antics. (a gem that Jeremy wrote). We will also want to index the property label. 

We will want to cache at the time we've retrieved the label. 

CACHING LAYER 
TBD

**Comment by ShanaLMoore** [comment]
goal 1: on the edit page for an LCSH property, search and select functionality for a term within an authority.
goal 2: The show page will have the term's label. 
goal 3: When I edit and save an existing work that has a uri term, it will continue to show the label.

Then: 
multiple authorities
allow for single property to choose which authority to query
must be performant and durable.

**Comment by ShanaLMoore** [comment]
Do the clients have a label? if not, we will need a job that will re-label all of the things.

**Comment by ShanaLMoore** [comment]
How will this work with allinson flex? 

in fedora, we write tiples (subject (the work), predicate (url), object (either a literal or an url)). Authorities will write the object as url. When there's a label, we will need to use a different predicate and the object will be a string. Because we have two different predicates, we will need to make sure we map the correct url from the authority to the correct label. Order matters!

**Comment by ShanaLMoore** [comment]
Discussed during planning meeting w Rob and the team, 

DOT has UI for editing QA within hyrax app

Best approach - get QA do all the things it needs to talk to the authorities

We will likely not use Lark. 

step 1: connect library of congress w QA.

**Comment by jillpe** [comment]
covered in #388
