### ISSUE TITLE
3. Create a way to map controlled value to a single QA (Questioning Authority) through a hyrax service

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#198]
# Summary
- Property has an authority, will go thru a service and get a view partial.  The view partial is responsible for hitting QA, we want this to be a concept of the property instead (e.g. a service lookup that returns the lookup functionality)
- Valkyrie indexer / Valkyrie forms have mechanisms for pulling their behavior from a generic configuration.  This is a breadcrumb for a potential implementation.
# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

# Notes

Controlled values meeting:
https://docs.google.com/document/d/1rLDHufesIWh71unkeAeucVpPy5syFaeGWQXr3KucIfQ/edit

**Comment by jillpe** [comment]
related to #388
