### ISSUE TITLE
Spike: bulkrax reimporting with a new FileSet causes weird behavior

### ISSUE THREAD

**Issue by kirkkwang** [notch8/utk-hyku#202]
ref https://github.com/scientist-softserv/utk-hyku/issues/181

When a `FileSet` gets added to an existing `Attachment` the IIIF looks weird, doesn't have all properties.

![Image](https://user-images.githubusercontent.com/19597776/202032431-aee76936-a804-4edf-8022-25cfb329eafa.png)

Acceptance Criteria:
- [ ] Problem is identified
- [ ] Follow up tickets are created

**Comment by kirkkwang** [comment]
test csv

[work_attachment_fileset.csv](https://github.com/scientist-softserv/utk-hyku/files/10016510/work_attachment_fileset.csv)

**Comment by jillpe** [comment]
related to #47

**Comment by jillpe** [comment]
Is it causing issues because the data is incorrect? If so, then we should fix soon

**Comment by jeremyf** [comment]
This has echoes of what I noticed during my Derivative Rodeo debugging.  And has me wondering if there's an issue in IIIF Print.

See https://github.com/scientist-softserv/derivative_rodeo/issues/56#issuecomment-1651881982

**Comment by jillpe** [comment]
@markpbaggett this has been resolved
