### ISSUE TITLE
Spike: Find a solution for role terms

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#203]
# Summary

This is a spike ticket.  Action for this work will be done on #104.  Update 104 with approach. 

Client request came from [slack](https://assaydepot.slack.com/archives/C0396LSM06P/p1668611662850049): 

"We are reviewing the current [add work form](https://dc.utk-hyku-staging.notch8.cloud/concern/generic_works/new?locale=en) and all of the expanded additional fields.

The amount of role terms in the form make it unusable. We've thought of a few options for fixing this:
- The creator and contributor fields have drop downs to select a role mapped to those fields.
- A button similar to “additional fields” that will expand/collapse just the role terms.
- The role terms sorted so that they are the last metadata elements in the form.
- Set infrequently selected role terms to admin only (keep frequent terms in main form: creator, contributor, and author).

The options are sorted by preference. What's the relative ease of implementation for each one?"

List of role terms: 

addressee
architect
arranger
artist
associated_name
attributed_name
author
autographer
binding_designer
cartographer
censor
choreographer
client
compiler
composer
contractor
contributor
copyright_holder
correspondent
costumer_designer
creator
dedicatee
depicted
designer
distributor
donor
editor
editor_of_compilation
engraver
former_owner
honoree
host_institution
illustrator
instrumentalist
interviewee
interviewer
issuing_body
lithographer
lyricist
music_copyist
musical_director
organizer
originator
owner
performer
photographer
printer
printer_of_plates
producer
production_company
publisher
restorationist
set_designer
signer
speaker
stage_director
stage_manager
standards_body
surveyor
translator
videographer
witness
utk_addressee
utk_architect
utk_arranger
utk_artist
utk_associated_name
utk_attributed_name
utk_author
utk_autographer
utk_binding_designer
utk_cartographer
utk_censor
utk_choreographer
utk_client
utk_compiler
utk_composer
utk_contractor
utk_contributor
utk_copyright_holder
utk_correspondent
utk_costumer_designer
utk_creator
utk_dedicatee
utk_depicted
utk_designer
utk_distributor
utk_donor
utk_editor
utk_editor_of_compilation
utk_engraver
utk_former_owner
utk_honoree
utk_host_institution
utk_illustrator
utk_instrumentalist
utk_interviewee
utk_interviewer
utk_issuing_body
utk_lithographer
utk_lyricist
utk_music_copyist
utk_musical_director
utk_organizer
utk_originator
utk_owner
utk_performer
utk_photographer
utk_printer
utk_printer_of_plates
utk_producer
utk_production_company
utk_publisher
utk_restorationist
utk_set_designer
utk_signer
utk_speaker
utk_stage_director
utk_stage_manager
utk_standards_body
utk_surveyor
utk_translator
utk_videographer
utk_witness

**Comment by ShanaLMoore** [comment]
<img width="420" alt="Screen Shot 2022-11-16 at 8 03 07 AM" src="https://user-images.githubusercontent.com/10081604/202231427-a6bdfdfe-d4a7-4397-b8d3-0e33f28032a0.png">

<img width="430" alt="Screen Shot 2022-11-16 at 8 03 32 AM" src="https://user-images.githubusercontent.com/10081604/202231538-c40ede96-bf4d-41a9-b421-2aad8a6839c7.png">

**Comment by ShanaLMoore** [comment]
![Image](https://user-images.githubusercontent.com/10081604/202524540-3b80c9e3-37bc-4a05-a319-f74760986392.png)

**Comment by crisr15** [comment]
Possible model for javascript updates on page: British Library staging: 


![Image](https://user-images.githubusercontent.com/11359350/202798904-045c2045-f140-4f03-b1d7-18c06fadf907.png)

**Comment by jillpe** [comment]
No longer necessary
