### ISSUE TITLE
Create client credentials for production

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#207]
## Summary

A user should be able to register their own account in prod. They will receive an email as part of the signup process.

We will need to get the mailer credentials from the client.

**Comment by ShanaLMoore** [comment]
Until then, I manually created a login for prod, for them to use.

**Comment by jillpe** [comment]
related to #2

**Comment by ShanaLMoore** [comment]
Closing because this ticket was referring to non-cas-sso signup, which the client does not require.
