### ISSUE TITLE
📎 SOW: Outgoing OAI-PMH

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#21]
# Summary
Supports including metadata elements such as thesis advisor and committee members in separate fields in the search index and outgoing OAI-PMH feed

Endpoint data will be configured as part of development.

We will need to map for DC and MODS.

This was done in Jio and Adventist

# Acceptance Criteria

- [ ] As a user I can access an OAI feed with prefix oai_dc that shows me all public metadata that has dc mappings
- [ ] As a user I can access an OAI feed with prefix oai_mods that shows me all public metadata that has mods mappings

# Screenshots or Video

# Testing Instructions

# Notes
- Can we get mappings for these?

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
May require additional work in AllinsonFlex to complete

**Comment by markpbaggett** [comment]
@jillpe this looks good. We approve this as is.  Just noting that since we are focused on digital collections, that first bullet can come later.

**Comment by jillpe** [comment]
related to 
- #405

**Comment by markpbaggett** [comment]
@jillpe and @laritakr I've created [this issue](https://github.com/scientist-softserv/utk-hyku/issues/535) and will be bump this one forward.
