### ISSUE TITLE
QA (BACKEND): Get a single remote authority working (Bulkrax)

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#212]
# Summary 

Get a single remote authority working. Start with library of congress

## Notes

[Questioning Authority Gem ](https://github.com/samvera/questioning_authority)

LOC (library of congress) [QA docs](https://github.com/samvera/questioning_authority/wiki/Connecting-to-Library-of-Congress-%28LOC%29)

client's list: https://github.com/markpbaggett/cartography/blob/main/extras/vocabs.yml

**Comment by ShanaLMoore** [comment]
GET http://dev.utk-hyku.test/authorities/show/linked_data/loc/subjects/sh85076841

![Image](https://user-images.githubusercontent.com/10081604/204355750-d239c9fa-0e61-4cfb-a3ac-71d3e575b049.png)

**Comment by ShanaLMoore** [comment]
GET http://dev.utk-hyku.test/authorities/show/loc/subjects/sh2008121753



![Image](https://user-images.githubusercontent.com/10081604/204356034-88dccb4e-4631-4201-8b30-ef6db90e2e8f.png)

**Comment by ShanaLMoore** [comment]
Example search subauthority subjects:

http://dev.utk-hyku.test/authorities/search/loc/subjects?q=History--





![Image](https://user-images.githubusercontent.com/10081604/204358467-0aff5fa8-3ef4-40ec-8402-199f437dd161.png)

**Comment by ShanaLMoore** [comment]
remote example from hyrax (based_near): https://github.com/samvera/hyrax/blob/a0f8455fa373b94f2700b0a47fd55084ba7fde6d/app/views/records/edit_fields/_based_near.html.erb#L1-L12

**Comment by ShanaLMoore** [comment]
qa [removed lcsh authority](https://github.com/samvera/questioning_authority/pull/46/files) because it duplicates LOC's subjects sub-authority

**Comment by ShanaLMoore** [comment]
ref UCSC for bulkrax remote qa support: https://github.com/UCSCLibrary/ucsc-library-digital-collections/blob/sandbox/app/models/concerns/bulkrax/has_local_processing.rb

PR - https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/181
bulkrax pr - https://github.com/UCSCLibrary/ucsc-library-digital-collections/pull/215

**Comment by ShanaLMoore** [comment]
client requirements: https://github.com/utkdigitalinitiatives/m3_profiles/blob/main/extras/vocabs.yml

**Comment by ShanaLMoore** [comment]
This ticket needs to be broken down into multiple tickets. UI vs backend. 

# make factory pattern/single point of entry for the term - pass URL and get back relevant label. This will also make it easier to test
          # make RemoteAuthority module . Authority.label_for_url(url) -  check for where url is (local, db, remote)
          # will allow us to make submodules for each type (ie: geoname)
          # local caching can be done at the remoteAuthority level.
          # this separates frontend from backend. someone can handle frontend. someone else can handle adding more sub authorities.
          # with the argument passed we need to figure out where authority is (ask remote, db cache or local)
          # Break tickets down
          # UI/Indexing (label show on page (solr), editing should show label(fedora) )
          # caching as a different ticket?
          # BACKEND How is this done in questioning authority (remote interaction). get authority module working to return a string once passed a url
          # Insullation layer (=> create wrapper around calling gem directly. can help to protect us from being codependent on the gem)
          # do we can the label to be saved in fedora? 

          auth_id = Authority.sanitize_controlled_field_uri(value) # assume user-provided URI references a valid authority
          # fetch and cache authority (job) => background job to go to LOC and pull them into local db. Authority.fetch_cache_term

**Comment by ShanaLMoore** [comment]
https://github.com/samvera/questioning_authority/wiki/Connecting-to-Library-of-Congress-%28LOC%29#accessing-via-qa

We need to implement vocabulary search with #find. this will be captured in a [separate ticket](https://github.com/scientist-softserv/utk-hyku/issues/267).

**Comment by ShanaLMoore** [comment]
PR started: https://github.com/scientist-softserv/utk-hyku/pull/263

**Comment by laritakr** [comment]
Another test comment for Shana

**Comment by ShanaLMoore** [comment]
subject is part of process_parse in bulkrax https://github.com/samvera-labs/bulkrax/blob/main/app/matchers/bulkrax/application_matcher.rb#L42

**Comment by jillpe** [comment]
No longer necessary
