### ISSUE TITLE
Restructure theming files

### ISSUE THREAD

**Issue by AKFosterDev** [notch8/utk-hyku#214]
Restructure theming files. 

Move theming partials into dc-repository
- [x] Header
- [x] Hero/Nav

Revert hyrax partials.
- [x] Header
- [x] Hero/Nav

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/scientist-softserv/utk-hyku/pull/210

**Comment by ShanaLMoore** [comment]
@AKFosterDev How should this get tested in staging?

**Comment by AKFosterDev** [comment]
QA Testing

- On dc-repository theme the header and hero/nav should look like this:
![Image](https://user-images.githubusercontent.com/39319859/203369322-2d0fb458-817e-42ed-ba94-7e3a71c51d38.JPG)

- All other themes should be unaffected

**Comment by ShanaLMoore** [comment]
# QA
## DC tenant and theme



![Image](https://user-images.githubusercontent.com/10081604/203374854-6e87a8d5-960a-4f42-9bef-8a7a7ff16cb3.png)

## Default tenant and theme



![Image](https://user-images.githubusercontent.com/10081604/203375069-1ec85fb5-458b-4a61-bbd4-4bee47c8e924.png)


cc @AKFosterDev When switched to the default theme the utk logo/header and the image of the people are still present. Should it be?

**Comment by AKFosterDev** [comment]
@ShanaLMoore Yes, those should be there on all themes because they are added through the dashboard.

**Comment by ShanaLMoore** [comment]
Thanks! Then this passes QA. 🎉 

Since this was basically a refactor, I don't think this requires client QA.
