### ISSUE TITLE
Thumbnails for A/V material

### ISSUE THREAD

**Issue by kirkkwang** [notch8/utk-hyku#215]
## Summary
ref
- #409 
- #391 

After installing the Hyrax IIIF AV gem, it has been observed that Audio and Video material does not generate thumbnails in the IIIF manifest.  This would likely require a closer look at the IIIF Manifest gem to see where things missing.

## Acceptance Criteria
- [ ] Thumbnails are generated in the IIIF manifest for Audio and Video material

**Comment by jillpe** [comment]
blocked, need to confirm with client if this should be in milestone 2

**Comment by jillpe** [comment]
This is resolved
