### ISSUE TITLE
Staging: NoMethodError: undefined method `propagate' for #<Hyrax::VisibilityPropagator::NullVisibilityPropogator:0x0000560eb785d498> Did you mean? propogate

### ISSUE THREAD

**Issue by DiemBTran** [notch8/utk-hyku#218]
![Image](https://user-images.githubusercontent.com/29311858/203167755-bbfc831c-e6ed-47e6-8a0d-86bf18286113.png)

Caused by running an importer

**Comment by jillpe** [comment]
should be taken care of - re-report if still seeing error
