### ISSUE TITLE
decorator files are being ignored

### ISSUE THREAD

**Issue by DiemBTran** [notch8/utk-hyku#221]
since the introduction of allinson flex, decorator files are being ignored. (i believe allinson_flex is the cause... but i may be wrong!)Either: 

1) convert all decorator files to traditional override methods and/or
2) figure out why the decorators are being ignored and fix it

2 is preferred but if it's too time consuming, 1 also works as a workaround.

**Comment by DiemBTran** [comment]
Related MRs:

- [Draft: 80 - use traditional overrides](https://gitlab.com/notch8/utk-hyku/-/merge_requests/84)

**Comment by jillpe** [comment]
should be working - re-report if still seeing
