### ISSUE TITLE
Homepage search tenant catalog link fails with no query terms

### ISSUE THREAD

**Issue by DiemBTran** [notch8/utk-hyku#222]
# Summary
When selecting the search icon from the search tenant with no terms, an error is thrown. 

https://sentry.notch8.com/sentry/utk-hyku-v7/issues/142651/

# Acceptance Criteria

- [ ] Able to search the search tenant with no term entered.

# Screenshots or Video

![Image](https://user-images.githubusercontent.com/29311858/203179954-d963bfb7-d863-4e43-b7e7-1912b4abe4c8.png)

![Image](https://user-images.githubusercontent.com/29311858/203179972-e3dd647a-2bda-456a-b445-d991d0dead08.png)

# Testing Instructions

Go to the home page of the search tenant, and click the magnifying glass icon.

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by DiemBTran** [comment]
Crystal Aug 2022

---

Possible related issue that has been resolved: https://gitlab.com/notch8/adventist-dl/-/issues/60

**Comment by jillpe** [comment]
resolved - re-report if seeing
