### ISSUE TITLE
Development: Redis::CannotConnectError

### ISSUE THREAD

**Issue by DiemBTran** [notch8/utk-hyku#223]
Identify cause of Sidekiq `development` environment error appearing in Sentry and remediate. 

https://sentry.io/organizations/scientist-inc/issues/3644472653/events/?project=6745049&referrer=issue-stream

![Image](https://user-images.githubusercontent.com/29311858/203180390-a45f89c7-1c9b-4974-8e51-bc8fc2f12e8e.png)

**Comment by jillpe** [comment]
re-report if still seeing error
