### ISSUE TITLE
Integrates with an ARK minting service for digital objects

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#23]
# Summary
Crossref is the current provider for DOI. Notch8 will implement integration to mint an ARK id for completed records. This will not be used as the internal primary ID, and a record will never have both an ARK and a DOI.

# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

# Notes
- What fields need to be mapped?
- Does this need to read and write? 
Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by DiemBTran** [comment]
Mark July 2022

---

Just adding that we have access to ARK minting via EZID. Our goal is to be able to mint ARKs for an object in batches and have the generated ID written back to the RDF property for ARKs and use existing metadata to fill out "who", "what", "when", and "where".

**Comment by jillpe** [comment]
no longer in scope 2023-04-19
