### ISSUE TITLE
M1 Macs are stalling on `CharacterizeJob`

### ISSUE THREAD

**Issue by kirkkwang** [notch8/utk-hyku#231]
ref: #230, #239, https://github.com/scientist-softserv/dev-ops/pull/492

M1 Macs are stalling on `CharacterizeJob` making it hard/impossible to test import code locally

**Comment by ShanaLMoore** [comment]
Todo: update base image to distribute to all hykus

**Comment by kirkkwang** [comment]
update base found here: https://github.com/scientist-softserv/dev-ops/tree/main/base/samvera

**Comment by ShanaLMoore** [comment]
PR: https://github.com/scientist-softserv/dev-ops/pull/492

**Comment by kirkkwang** [comment]
for UTK instance: https://github.com/scientist-softserv/utk-hyku/pull/258

**Comment by DiemBTran** [comment]
does not require QA
