### ISSUE TITLE
Unexpected visibility results in imported collection

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#232]
Collection was imported from csv. Collection and images are private. Attachments and filesets are public. 
https://qa.utk-hyku-production.notch8.cloud/dashboard/collections/f3e7f98c-ab1b-49e5-9810-4cda3c70ea8c?locale=en

The csv used did not have a visibility column, so we expected everything to be public by default.

**Comment by laritakr** [comment]
CSV used:

[gamble_good2_with_collections.csv](https://github.com/scientist-softserv/utk-hyku/files/10106316/gamble_good2_with_collections.csv)

**Comment by ShanaLMoore** [comment]
I'm guessing that someone went in and manually changed the visibility of this collection, which caused this confusion. 

When we re import this file in local, [staging](https://dc.utk-hyku-staging.notch8.cloud/dashboard/collections/d354d217-83c9-4194-a765-2bba18a57393?locale=en), and [prod](https://qa.utk-hyku-production.notch8.cloud/dashboard/collections/3536d7ef-ff36-48f1-b791-8064766a313f?locale=en), there is no issue. Collection is public as expected.
