### ISSUE TITLE
Unable to view collection from list if no metadata profile has been uploaded

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#234]
In the case of works, before adding a work, you are directed to upload a metadata profile. Before allowing Collections to be added, a check and re-route to the metadata profile page should happen, similarly to what happens for works.

You can apparently add a collection without one (at least you could at one point... possibly not with the new metadata terms. Apparently the solr document dynamically defines terms used, so the fact that collections could be added may be simply because they were added prior to the new terms being in the model.)

When viewing it, an error was thrown because it can't find the terms in solr_document, and it is possible that an error might be thrown earlier in the process.

**Comment by jillpe** [comment]
no longer relevant
