### ISSUE TITLE
Collection metadata should not appear on show page if empty

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#235]
# Summary
ref
- #411 
- #7 

Ticket was filed in Bulkrax to stop adding empty metadata, but this should be handled similarly to what was done in the works show page.

# Acceptance Criteria
- [ ]  Empty metadata does not appear on show page

# Testing Instructions
- [ ] Import a work that has missing metadata fields
- [ ] Navigate to the work's show page
  - [ ] Confirm empty metadata fields are not displaying on the show page

**Comment by jillpe** [comment]
related to #7

**Comment by jillpe** [comment]
SoftServ QA: Pass

Imported csv: 

[gamble_partial_small.csv](https://github.com/scientist-softserv/utk-hyku/files/12043419/gamble_partial_small.csv)

[Collection show page url](https://dc.utk-hyku-staging.notch8.cloud/collections/d354d217-83c9-4194-a765-2bba18a57393?locale=en)



![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/56fb35ef-c012-4671-b71e-30937e7e2a86)
