### ISSUE TITLE
DOI minting

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#24]
# Summary
Most major Hyku implementations require custom work to meet individual institutional requirements, including SSO integration, custom work types, custom deposit workflows, and integration of services like DOI minting. Notch8 has completed various degrees of similar extension of the open source base for all projects mentioned in the RFP.

Hyku supports DOI minting via recent contributions. This may require some custom work to utilize CrossRef.

# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
no longer in scope 2023-04-19
