### ISSUE TITLE
Sidebar menu loses Allinson Flex & Bulkrax options randomly

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#244]
Crashed trying to open importers page, and options were gone after back arrow. Needs a restart of app to reinstate options.  (Does this affect environments other than development?)

![Image](https://user-images.githubusercontent.com/17851674/204930029-943752b9-1263-4318-8645-15f01c17ced4.png)

![Image](https://user-images.githubusercontent.com/17851674/204930030-881940a6-09a7-499f-af83-4e71c373621c.png)

**Comment by jeremyf** [comment]
LaRita pinged me yesterday about an issue with UTK’s side-bar menu disappearing in dev instances.  My strong suspicion is that there’s some load/reload issues.

I’m wondering about https://github.com/scientist-softserv/utk-hyku/blob/4226fa6e13cd4db783a066185f2f27b243a0e5e5/config/application.rb#L11-L16

One thing I’d like to try is to move that to_prepare block down within the other to_prepare block.  It’s grasping at straws but perhaps those are evaluated in inconsistent order.

Next is to look at AllinsonFlex with some scrutiny regarding loading orders.

**Comment by jeremyf** [comment]
Digging a bit deeper, this code is running after each initialization.  It might be useful to check the view paths for in the running application.

https://github.com/samvera-labs/allinson_flex/blob/c1dfe12e5386f8f4325b3a19dde949ecef1fede3/lib/allinson_flex/engine.rb#L38-L48

My read on the intention of that logic is to ensure that Allinson Flex views are found before Hyrax views.  Below is some ruby code demonstrating what’s happening.

```
❯ irb
irb(main):001:0> array = [:a, :hyrax, :c]
=> [:a, :hyrax, :c]
irb(main):002:0> array.insert(array.index(:hyrax), :allinson)
=> [:a, :allinson, :hyrax, :c]
irb(main):003:0>
```

**Comment by jeremyf** [comment]
Another thing to consider regarding the partials is the order of initializer loading:

initializers load in alphabetical order; so it is possible that AllinsonFlex, the Bulkrax, then Hyrax loads which could obliterate the `Hyrax::DashboardController.sidebar_partials[:repository_content]`

Moving those `Hyrax::DashboardController.sidebar_partials[:repository_content]` into a to_prepare block in the application might also help.
