### ISSUE TITLE
Bulkrax import works & collection failed when trying to add relationships

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#245]
Happened in dev environment. Most likely related to graph indexer changes. Was able to add works to the collection through UI but it failed in Bulkrax import. I believe Bulkrax CreateRelationshipsJob needs to be modified on line 84.

Note: did NOT happen in staging test... does staging have the graph indexer environment variable set?

![Image](https://user-images.githubusercontent.com/17851674/204930379-dfbac802-3e21-4c6a-b504-09e9a42cf9f0.png)

**Comment by laritakr** [comment]
Testing instructions: 

This pull request adds in the actual use of the graph indexer. Previously environment variables were not set to use it. 

Testing involves making sure relationships can be created and viewed appropriately between works, collections, and works & collections. See https://github.com/scientist-softserv/utk-hyku/issues/188 for more detail.

**Comment by kirkkwang** [comment]
✅ Did a test on a brand new tenant with:
[gamble_good2_with_collections.1.csv](https://github.com/scientist-softserv/utk-hyku/files/10157095/gamble_good2_with_collections.1.csv)

And did not observe any errors related to creating relationships.


However, I did notice this error which seems unrelated:

![Image](https://user-images.githubusercontent.com/19597776/205720665-2fcfa674-1400-4d7c-9dcd-1982ddf09057.png)

**Comment by ShanaLMoore** [comment]
review not required by client review
