### ISSUE TITLE
IP based access controls changed to be handled by SSO

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#25]
# Summary
UTK wants SSO to be able to view work.

# Acceptance Criteria

- [ ] SSO implemented

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
related to #2

**Comment by jillpe** [comment]
Closed, no longer needed. Client just want SSO
