### ISSUE TITLE
Browse Collections - All Collections List View

### ISSUE THREAD

**Issue by AKFosterDev** [notch8/utk-hyku#259]
# Summary
- Update the DC Repository home page browse collections section list view per the figma wire frames
- Add functionality for List/Grid buttons to display specific view

### Requested Change
- [x] Make interior scroll bar visible in browse collections section of the homepage

UTK colors: https://brand.utk.edu/standards/colors/

# Related Tickets
[Browse Collections - All Collections Grid View #259](https://github.com/scientist-softserv/utk-hyku/issues/259)
[Browse Collections - Filter Collections List Alphabetically #260](https://github.com/scientist-softserv/utk-hyku/issues/260)

# Acceptance Criteria

- [x] List/Grid button functionality for rendering List or Grid partial and active state of button
- [x] Style list view for collections per screenshot below
- [x] The browse collections section is changed to look like the screenshot below
- [x] The collections link out appropriately

# Screenshots or Video
ref: https://www.figma.com/file/3JjoRJYmCrfoAcWhHu2Br4/UTK?node-id=388%3A789

### list view

![Image](https://user-images.githubusercontent.com/29311858/202317263-623ec512-0654-49b4-a16f-59ab56f54019.png)

**Comment by AKFosterDev** [comment]
## Summary
Custom theming for Browse Collections section list view 
- add partial for grid view
- add partial for list view
- update partial to include abstract and works count
- update partial to use bootstrap nav-tabs and panes for view toggle
- update and rearrange styles for browse collections section
- update div order
- update file formatting
- add helper decorator for returning work count in a specific collection
- update file to use new helper decorator
- update and restructure styles

## Pull Request
[Browse Collections - All Collections List View #280](https://github.com/scientist-softserv/utk-hyku/pull/280)

## Screencasts

<details>
<summary>Full Screen</summary>

https://user-images.githubusercontent.com/39319859/208202563-87ffcf47-db95-4cdf-8af4-7fab47e284f2.mp4
</details>

<details>
<summary>Medium Screen</summary>

https://user-images.githubusercontent.com/39319859/208202584-b6e20857-bbbd-4137-8b01-21a0ac7e41dd.mp4
</details>

<details>
<summary>Small Screen</summary>

https://user-images.githubusercontent.com/39319859/208202610-3f05d934-8466-4d6e-af19-3802527169f3.mp4
</details>

<details>
<summary>X-Small Screen</summary>

https://user-images.githubusercontent.com/39319859/208202625-65f2ceba-f668-49e0-a6f6-4bb7c532fada.mp4
</details>

## QA Instructions
- These changes only apply to the DC Repository theme - all other themes should have default styling
- Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- Test on browsers
- [x] Chrome
- [x] Safari
- [x] Firefox
- List view looks like screencasts above for (med, sm, x-sm screencasts are at 75% view so they would show more at once)
- [x] Large screen 992px and above
- [x] Medium screen 991px
- [x] Small screen 767px
- [x] X-small screen 575px
- [x] List view renders the number of works for each specific collection
- Grid view remains the same as related ticket [#61](https://github.com/scientist-softserv/utk-hyku/issues/61)
- Feature flippers should be _disabled_ for the following:
- [x] Share work button
- Feature flippers should be _enabled_ for the following:
- [x] Show featured works tab
- [x] Show recently uploaded tab
- [x] Show featured researcher
- NOTE: I noticed that the grid/list buttons have a grey hover effect which is being fixed on ticket #260

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

## QA Instructions
- These changes only apply to the DC Repository theme - all other themes should have default styling
- Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- Test on browsers
     - [x] Chrome
     - [x] Safari
     - [x] Firefox
- List view looks like screencasts above for (med, sm, x-sm screencasts are at 75% view so they would show more at once)
     - [x] Large screen 992px and above
     - [x] Medium screen 991px
     - [x] Small screen 767px
     - [x] X-small screen 575px
     - [x] List view renders the number of works for each specific collection
- Grid view remains the same as related ticket [#61](https://github.com/scientist-softserv/utk-hyku/issues/61)
- Feature flippers should be _disabled_ for the following:
     - [x] Share work button
- Feature flippers should be _enabled_ for the following:
     - [x] Show featured works tab
     - [x] Show recently uploaded tab
     - [x] Show featured researcher

<details><summary>List View looks good on Chrome, Safari, and Firefox</summary>



https://user-images.githubusercontent.com/29311858/208555729-958db696-0dd7-47f9-81d6-ef4f3d15442b.mp4
</details>

**Comment by markpbaggett** [comment]
@AKFosterDev looks good to me.  Let's go ahead and move this one forward.

**Comment by mlhale7** [comment]
@AKFosterDev - A quick thought, given that we can only show 50 collections and not affect performance, I wondered if it would be possible to exclude featured collections from the all collections list to ensure that the page has more variety (since they'll always show above the 50)?

Otherwise I'm interested to see what the All collections page yet to be developed will look like. I think UTK may also need to consider ways of grouping collections in the future if we want more to be shown on the home page.

**Comment by ShanaLMoore** [comment]
The client provided feedback about the hidden scroll bar. @AKFosterDev to address and share screen shots.

**Comment by AKFosterDev** [comment]
## Summary
Update to show inner scroll bar for browse collections section on the homepage.

## Related PR
[#312](https://github.com/scientist-softserv/utk-hyku/pull/312)

## Screenshot
![Screenshot 2023-01-23 at 1 02 11 PM](https://user-images.githubusercontent.com/39319859/214150689-e6fc1971-6207-42af-8703-074b38315ead.JPG)

## QA Instructions
These changes only apply to the DC Repository theme - all other themes should have default styling
- Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- [ ] Inner scroll bar should be visible for browse collections section on the homepage

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

# QA Instructions
These changes only apply to the DC Repository theme - all other themes should have default styling

- [x] Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- [x] Inner scroll bar should be visible for browse collections section on the homepage

<details><summary>The scroll bar is visible for the Browse Collections section in both List and Grid view</summary>



https://user-images.githubusercontent.com/29311858/214180629-c6f9ba5d-2ace-4d1e-a1e7-e45b7e6187c8.mp4
</details>

**Comment by josh-morgan117** [comment]
We're still discussing this ticket and should have some feedback tomorrow for you, though we all agree the featured images should be reduced from 400px to 300px. They just take up too much real estate in our opinion.

**Comment by markpbaggett** [comment]
@AKFosterDev, thanks for your work on this. After lengthy discussions, we're wondering if we could just not  include all collections on the home page and instead have:

1. Show featured collections
2. Provide some context to our digital collections overall (We'd provide some text about what digital collections are overall, where they come from, etc.)
3. Link to a search of all the collection objects in the repository under an anchor like "Browse Collections"

We realize this is a break away from the original wireframes, but if this is possible, we think we'd be happier. Maybe we can discuss this as a possibility tomorrow.

**Comment by AKFosterDev** [comment]
Client re-work request - remove browse collections section from homepage and move "view all collections" button to the featured collections sections of the homepage to be completed on ticket #320 once new Figma design is approved from ticket #324. This ticket being closed.
