### ISSUE TITLE
Browse Collections - Finalize Section

### ISSUE THREAD

**Issue by AKFosterDev** [notch8/utk-hyku#260]
# Summary
~~Implement sorting collections alphabetically ascending and descending within the browse collections section.~~
- Remove "A-Z" button
- Remove "Group" button
- Update "All Collections" button to "Search All Collections" and link to search type=collections page

UTK colors: https://brand.utk.edu/standards/colors/

# Related Tickets
[Browse Collections - All Collections Grid View #61](https://github.com/scientist-softserv/utk-hyku/issues/61)
[Browse Collections - All Collections List View #259](https://github.com/scientist-softserv/utk-hyku/issues/259)

# Acceptance Criteria

- [ ] ~~collections can be sorted alphabetically in ascending order~~
- [ ] ~~collections can be sorted alphabetically in descending order~~
- [x] Remove "A-Z" button
- [x] Remove "Group" button
- [x] "All Collections" button shows "View all collections" and links to search type=collections page (Styling for the search results page to be completed on [Ticket #64 - Search Results](https://github.com/scientist-softserv/utk-hyku/issues/64)

# Screenshots or Video
ref: https://www.figma.com/file/3JjoRJYmCrfoAcWhHu2Br4/UTK?node-id=388%3A789

**Comment by AKFosterDev** [comment]
### Summary
- update styles to remove hover effect on grid/list buttons
- limit all collection items on homepage to max 50
- hide A-Z and Group buttons
- convert View all collections from dropdown to button
- update styles for view all collections button

### Pull Request
[#283 - Browse Collections - Finalize Section](https://github.com/scientist-softserv/utk-hyku/pull/283)

### Screenshots
![Screenshot 2022-12-20 at 9 59 19 AM](https://user-images.githubusercontent.com/39319859/208734852-4f2da56a-61ce-4e93-a6e7-c44a08fd123c.JPG)

Hover state
![Screenshot 2022-12-20 at 9 59 29 AM](https://user-images.githubusercontent.com/39319859/208735025-fdde4885-f2bf-4b4d-89de-4178e8b23ab9.JPG)

Links to Search filtered to All Collections
![Screenshot 2022-12-20 at 9 59 49 AM](https://user-images.githubusercontent.com/39319859/208735147-0e4c410a-8b44-4f95-afd4-e222bc8b3d51.JPG)


### QA Instructions
- These changes only apply to the DC Repository theme - all other themes should have default styling
- Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- Test on browsers
- [x] Chrome
- [x] Safari
- [x] Firefox
- Looks like screenshots above
- [x] Large screen 992px and above
- [x] Hover state of View all collections button
- [x] Links to Search results page filtered to collections - This is currently resulting in an error. Ticket created to fix this behavior [#286 Empty search results in error](https://github.com/scientist-softserv/utk-hyku/issues/286)


![Image](https://user-images.githubusercontent.com/39319859/208756876-a3979a72-9aa4-4a7b-8fd6-ce902ab36d95.JPG)

**Comment by ShanaLMoore** [comment]
@AKFosterDev Your QA instructions were super helpful. Thank you! 

This passes QA. 🎉 

re the 500 error, caused by clicking on the view all collections button in staging. I'm surprised you didn't see the same behavior locally. 

Here is the error, which I'll also attach in the bug ticket for it: 

https://sentry.io/organizations/scientist-inc/issues/3606000070/?query=is%3Aunresolved&referrer=issue-stream

![image](https://user-images.githubusercontent.com/10081604/209172405-58fd43bd-7aff-4d42-ab8b-434519767118.png)

**Comment by AKFosterDev** [comment]
Client re-work request - remove browse collections section from homepage and move "view all collections" button to the featured collections sections of the homepage to be completed on ticket #320 once new Figma design is approved from ticket #324. This ticket being closed.
