### ISSUE TITLE
🦄 Spike: Attachments should not be seen in the work index page

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#266]
# Summary

In production, we noticed that the Attachment work type was being displayed in the [work index page](https://dc.utk-hyku-production.notch8.cloud/dashboard/works?locale=en) (when they shouldn't be). Attachments should get treated like a fileset, so a user should access it by clicking on the parent. 

Original MR did not include the path for the All works tab: https://github.com/scientist-softserv/utk-hyku/pull/132/files

# Acceptance Criteria

The Attachment work type should not be included in the work index page. 
- [ ] close if no longer relevant. if it is relevant close and create a follow up ticket

# Testing Instructions

**Comment by jillpe** [comment]
Verify if this is still relevant

**Comment by kirkkwang** [comment]
Attachments are not shown in the work index page anymore.  This was handled by this commit
https://github.com/scientist-softserv/utk-hyku/pull/364/commits/ddcea57127a0eed38c063c24bca69eb90d95d440
