### ISSUE TITLE
QA (BACKEND) - Implement #find for vocabularies

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#267]
# Summary 

This work is to update the questioning authority gem.

ref: https://github.com/samvera/questioning_authority/wiki/Connecting-to-Library-of-Congress-%28LOC%29#accessing-via-qa

Bulkrax error received when importing the following sample file: 

[212.csv](https://github.com/scientist-softserv/utk-hyku/files/10196809/212.csv)

` Error: Qa::TermNotFound - http://id.loc.gov/authorities/graphicMaterials/tgm008083 Not Found - Term may not exist at LOD Authority. (HTTPNotFound - 404)`

The client has listed the following LOC uri as a controlled value. 

`https://id.loc.gov/vocabulary/graphicMaterials/tgm008083.html`

However QA does not support anything other than authorities with its #[find](https://github.com/samvera/questioning_authority/blob/baf399f2dba6c45c99f90483242dc047ff94e47b/lib/qa/authorities/loc/generic_authority.rb#L33-L39) method (yet)

# Acceptance Criteria

- [ ] a user should be able to import the above sample file via bulkrax. The controlled value uris should resolve to actual labels. 
- [ ] Upate wiki documentation for LOC to reflect updates.

# Testing Instructions

1. Import the above sample file
2. Visit the Image it creates. Subject should display labels instead of uris. 

# Notes

Search uses #[build_query_url(q)](https://github.com/samvera/questioning_authority/blob/baf399f2dba6c45c99f90483242dc047ff94e47b/lib/qa/authorities/loc/generic_authority.rb#L22-L31) which [supports](https://github.com/samvera/questioning_authority/blob/baf399f2dba6c45c99f90483242dc047ff94e47b/lib/qa/authorities/loc_subauthority.rb#L2) more routes. 

[wiki](https://github.com/samvera/questioning_authority/wiki/Connecting-to-Library-of-Congress-%28LOC%29#accessing-via-qa) states: 

```
for search: Subauthorities include authorities, vocabularies, datatypes, and preservation as defined in [loc_subauthorities.rb](https://github.com/samvera/questioning_authority/blob/master/lib/qa/authorities/loc_subauthority.rb).
for term: Subauthorities include only the authorities listed in [loc_subauthorities.rb](https://github.com/samvera/questioning_authority/blob/master/lib/qa/authorities/loc_subauthority.rb).”
```

**Comment by ShanaLMoore** [comment]
![Image](https://user-images.githubusercontent.com/10081604/206763450-6dc5de9e-b8d4-4c61-9c42-2e33710eb16e.png)

**Comment by ShanaLMoore** [comment]
PR started: https://github.com/samvera/questioning_authority/pull/379

**Comment by jillpe** [comment]
No longer necessary
