### ISSUE TITLE
Collection UI should only display a "Collection" option for its resource type dropdown

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#275]
## Acceptance Criteria
- [ ] Collection UI should only display a "Collection" option for its resource type dropdown 
- [ ] All the other work types should not include "Collection" as an option for its resource type drop down 

<img width="1713" alt="image" src="https://user-images.githubusercontent.com/10081604/207719770-bd14e90a-fc55-486c-a3c5-b3dc34bde133.png">

## Notes

ref [convo](https://github.com/scientist-softserv/utk-hyku/issues/149#issuecomment-1351912708) w @mlhale7 for desired behavior

**Comment by ShanaLMoore** [comment]
![image](https://user-images.githubusercontent.com/10081604/207734711-5a29a9bb-a180-468e-b531-ecd9714c4850.png)

**Comment by jillpe** [comment]
No longer a priority per adjusted priority list 2023-04
