### ISSUE TITLE
Migrate objects that have viewing restrictions defined in a XACML 1.0 policy file (see example for how to interpret)

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#28]
# Summary
This will involve custom work on the importer, but interpreted ACLs are supported in other file importer flows, making this implementation fairly straight forward.

# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
related to #4

**Comment by jillpe** [comment]
@markpbaggett is this still an issue?

**Comment by jillpe** [comment]
Confirmed in meeting 2024-04-09, this is no longer a requirement. The workflow discussed [here](https://github.com/scientist-softserv/utk-hyku/issues/4#issuecomment-1531653670) does not require the GwR feature. Closing this ticket and making a new one to implement the above workflow
