### ISSUE TITLE
Empty search results in error

### ISSUE THREAD

**Issue by AKFosterDev** [notch8/utk-hyku#286]
# Summary
Clicking the 'View all collections' button results in an error due to empty search field

![Image](https://user-images.githubusercontent.com/39319859/208755700-699a8bc0-9c7d-4afb-8bc4-4fedfa6d0e9c.JPG)

![Image](https://user-images.githubusercontent.com/39319859/208756020-f2a8b1d9-ffdd-46f9-b4dc-5c243d0d0e56.JPG)

# Related Ticket
[#260 Browse Collections - Finalize Section](https://github.com/scientist-softserv/utk-hyku/issues/260)

# Acceptance Criteria
- [ ] When clicking the 'View all collections' button the link to the search results filtered by all collections works

**Comment by ShanaLMoore** [comment]
Error: https://sentry.io/organizations/scientist-inc/issues/3606000070/?query=is%3Aunresolved&referrer=issue-stream

![image](https://user-images.githubusercontent.com/10081604/209172432-7ac2d891-ab57-42b9-a4bd-9138b36dc47a.png)

**Comment by jillpe** [comment]
Is working on dc staging 2023-04-13
