### ISSUE TITLE
IiifPrint x AllinsonFlex

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#298]
Created off of [i37](https://github.com/scientist-softserv/iiif_print/issues/37)

ManifestServiceBuilder x AllinsonFlex

**Comment by ShanaLMoore** [comment]
As discussed in Crystal's Office hr, this is not a concern at the moment. We will re visit this once the main iiif_print work is complete.

**Comment by jillpe** [comment]
No longer necessary
