### ISSUE TITLE
EPIC: Accessibility Improvements

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#3]
# Summary

Some budget was set aside for some basic remediation of accessibility issues for Hyku.  The accessibility report needs to be reviewed for what items need to be resolved.  This section will most likely focus on end front end changes.  Accessibility improvements of the viewers/media players will come in later tickets. 

# Notes
 Accessibility Audit: [Report for https___test.hykucommons.org_.pdf](https://github.com/scientist-softserv/utk-hyku/files/10061299/Report.for.https___test.hykucommons.org_.pdf)

**Comment by DiemBTran** [comment]
Linked items:

- [5] 1.1 Text Alternatives
- [1] 1.3 Adaptable: Add Label to 'Select a role' drop down
- [1] 1.3 Adaptable: Each form must have labels
- [2] 1.4.10 Reflow: Admin Dashboard's responsiveness
- [3] Use Alternative Text for collection branding
- Use Alternative Text as entered in appearance tabs

**Comment by jillpe** [comment]
related to #387

**Comment by jillpe** [comment]
closed - covered in #393
