### ISSUE TITLE
Fixity and Checksum scheduling

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#30]
# Summary
Hyku supports this. Fixity success or failure is based on the checksum of the file at ingest time vs its current checksum during the fixity check. File check frequency is tunable to meet performance vs safety requirements.

# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
no longer in scope 2023-04-19
