### ISSUE TITLE
Spike: Audit DC theming tickets

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#307]
# Summary

There appears to be theming tickets missing from our board, per Amanda. ie: About Page

This ticket is to review the figma board and create a checklist to represent each page. 

# Acceptance Criteria

- [x] Check off the ones that have already been completed.
- [x] Create new theming tickets for the unchecked items. Please link the ticket number to the relevant item before checking it off. 
- [x] close this ticket once all checkboxes are marked as done

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by AKFosterDev** [comment]
## Page Audit

[Google sheet](https://docs.google.com/spreadsheets/d/1vJ4aP-8e3Qvtru8RJUfCHVT2Mz1So7Waxh3e7qSbrvY/edit?usp=sharing)

## Resulting Tickets

### Design Tickets - Need client approval of designs
- https://github.com/scientist-softserv/utk-hyku/issues/329 - requested approval in S3-utk-client channel
- https://github.com/scientist-softserv/utk-hyku/issues/330
- https://github.com/scientist-softserv/utk-hyku/issues/331
- https://github.com/scientist-softserv/utk-hyku/issues/334


### Dev Tickets - Client design approval received
- https://github.com/scientist-softserv/utk-hyku/issues/320

### Dev Tickets - Client design approval needed
- https://github.com/scientist-softserv/utk-hyku/issues/332
- https://github.com/scientist-softserv/utk-hyku/issues/333
- https://github.com/scientist-softserv/utk-hyku/issues/335

**Comment by ShanaLMoore** [comment]
Thank you so much for doing this @AKFosterDev and @DeonFranklin
