### ISSUE TITLE
Spike: iiif_print x FileSets (bulkrax)

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#308]
# Summary

While testing #[11](https://github.com/scientist-softserv/iiif_print/issues/11) with the following csv, we discovered that the pdf split doesn't work when the FileSet is listed on its own row. We decided to make a spin off ticket to keep unblock the tickets dependent on the core functionality of PDFSplit.

Sample File: [Archive (1).zip](https://github.com/scientist-softserv/utk-hyku/files/10468012/Archive.1.zip)

# Acceptance Criteria

PDF Splitting should work for the following scenarios (feel free to break this ticket up to reflect each point, if needed): 

- [ ] A user should be able to import filesets when it's listed on its own row (does not work)
  - Sample File: [Archive (1).zip](https://github.com/scientist-softserv/utk-hyku/files/10468012/Archive.1.zip)
- [ ] A user should be able to import remote files (needs to be tested)
  - Sample File: [basic_hyku_example.csv](https://github.com/scientist-softserv/utk-hyku/files/10468088/basic_hyku_example.csv)

- [x] A user should be able to import filesets when it's listed in the same row as its parents. (should be working per i11)
  - Sample File: [i11.zip](https://github.com/scientist-softserv/utk-hyku/files/10468101/i11.zip)

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by ShanaLMoore** [comment]
figure out which actor stack needs to be inserted into and where, to make this work right.

pointed as a 13 in planning so we will Breakup into smaller tickets.

**Comment by ShanaLMoore** [comment]
converting to a spike ticket. Test each file set path for bulkrax. Close this spike once spin off tickets have been created.

**Comment by laritakr** [comment]
Tickets created: 
https://github.com/scientist-softserv/iiif_print/issues/98
https://github.com/scientist-softserv/iiif_print/issues/97
