### ISSUE TITLE
Audit trail

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#31]
# Summary
Tracks modifications to a digital object and updates an audit trail whenever the digital object is modified

Audit trails at the Fedora level are preserved. Hyku does not at this time display such audit trails to admins in the interface, but such a feature is planned for future development.

# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
no longer in scope 2023-04-19
