### ISSUE TITLE
Browse Collections - Render collections that are not part of featured collections

### ISSUE THREAD

**Issue by AKFosterDev** [notch8/utk-hyku#313]
## Summary
Currently the Browse Collection section of the homepage is rendering from all collections (currently limited to 50). The client is requesting that featured collections be removed from this section since they are already listed in the Featured Collections section above on the homepage this will allow more collections to be rendered on the homepage within the Browse Collections section. 

## Related Ticket
[#259 - Browse Collections - All Collections List View](https://github.com/scientist-softserv/utk-hyku/issues/259)

## Acceptance Criteria
- [ ] Collections rendered within the Browse Collections section of the homepage do not include any collections that are rendered within the Featured Collections section.

**Comment by jillpe** [comment]
Closed - this ticket is no longer relevant
