### ISSUE TITLE
Admin dashboard - Works breadcrumbs rendering twice

### ISSUE THREAD

**Issue by AKFosterDev** [notch8/utk-hyku#314]
## Summary
Currently on the admin dashboard breadcrumbs are rendering twice for Works

## Acceptance Criteria
- [ ] Admin dashboard breadcrumbs for works are rendered one time

## Screenshot
![Screenshot 2023-01-23 at 2 53 49 PM](https://user-images.githubusercontent.com/39319859/214170732-34573e23-2a08-4579-aea0-399d29e6299f.JPG)

**Comment by jillpe** [comment]
duplicate of #242
