### ISSUE TITLE
DC Repository Search Results Page Theme - Admin Dashboard Updates

### ISSUE THREAD

**Issue by AKFosterDev** [notch8/utk-hyku#315]
## Summary
ref
- #411 
- #7 

For DC Repository theming - on the admin dashboard under appearance/themes when DC Repository is selected the "Search Results Page Theme" needs to have "DC view" selected from the dropdown. When "DC View" is selected the Search Results Theme notes should be updated to reflect a note stating that this is the search results page for DC repository and the correct wireframe thumbnail should be rendered.

## Acceptance Criteria
When DC View is selected from the dropdown
- [ ] Search Results Theme notes updated to inform user that this view will render the DC Repository Search Results page
- [ ] Thumbnail for DC Repository Search Results page is visible (screenshot from Figma design)

## Testing Instructions

From the admin dashboard navigate to the section where you can select themes. Settings > Appearance > Themes. 
Under the Search Results Page Theme selection select DC view and verify a preview image appears. 

## Screenshot
![Screenshot 2023-01-23 at 3 00 53 PM](https://user-images.githubusercontent.com/39319859/214172191-6677e732-0452-4f67-b6e9-3bf26d2c31b3.JPG)

**Comment by ShanaLMoore** [comment]
I believe we are missing an image file. It should be named dc_repository_search.jpg and be placed in the themes/search directory. 

## TODO 

Track down the figma design and add it as described above.

ref: https://github.com/scientist-softserv/utk-hyku/issues/64

**Comment by ShanaLMoore** [comment]
## After

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/f18dcba4-a948-426e-bf88-c87ef94c6c40)

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- settings theme page: https://qa.utk-hyku-staging.notch8.cloud/admin/appearance?locale=en#themes
- image: https://qa.utk-hyku-staging.notch8.cloud/assets/themes/search/dc_repository_search-ff9d36cf6c2896444f98782bd0ea8a88a72c7d08bc028e03a6a2382566b06b63.jpg

<details><summary>Search Results Page theme now has a wireframe on the side to preview the DC view theme</summary>

![Show Appearance Hyku 2023-07-26 at 9 47 02 AM](https://github.com/scientist-softserv/utk-hyku/assets/29311858/80b4653b-e4ff-4f46-aa82-77563c769dc2)
![dc_repository_search-ff9d36cf6c2896444f98782bd0ea8a88a72c7d08bc028e03a6a2382566b06b63 jpg (587×870) 2023-07-26 at 9 47 11 AM](https://github.com/scientist-softserv/utk-hyku/assets/29311858/0910fa50-7ce6-479d-8fbb-49c2c5b6e954)

</details>
