### ISSUE TITLE
Expose Allinson Flex UI for staging

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#318]
ref slack convo/thread: https://assaydepot.slack.com/archives/G0313NK5NMA/p1674508242390289

# Summary

Expose Allinson Flex UI for UTK staging

# Acceptance Criteria

- [ ] a user should be able to access the allinson flex UI in UTK staging

# Screenshots or Video
![image](https://user-images.githubusercontent.com/10081604/215575223-292a6bc4-f12c-4935-bb28-44f7b9561233.png)

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by ShanaLMoore** [comment]
RESOLVED. I needed to add the env var to the rancher secrets section and redeploy.
I am able to access the [edit page](https://dc.utk-hyku-staging.notch8.cloud/profiles/28/edit?locale=en) now, on staging.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot. Closing, as this is an internal issue that will go away on the next deploy.

tested on::
- https://dc.utk-hyku-staging.notch8.cloud/profiles?locale=en

https://user-images.githubusercontent.com/29311858/215863921-8e1e0f8a-c719-4e60-9ef1-819ee0e61414.mp4
