### ISSUE TITLE
Remove Browse Collections Section from Homepage

### ISSUE THREAD

**Issue by AKFosterDev** [notch8/utk-hyku#320]
## Summary
Client is requesting: 
- Browse Collections section be removed from the homepage
- View all collections button is floated right next to "Featured Collections" section title
- Image thumbnails in the Featured Collections size reduced from 400px to 300px height (this impacts spacing within the section)

## Acceptance Criteria
- [ ] Browse Collections section be removed from the homepage
- [ ] View all collections button is floated right next to "Featured Collections" section title
- [ ] Image thumbnails in the Featured Collections size reduced to 300px height
- [ ] Homepage still responsive 

## Related Tickets
[#60 Featured Collections ](https://github.com/scientist-softserv/utk-hyku/issues/60)
[#61 Browse Collections - Grid View](https://github.com/scientist-softserv/utk-hyku/issues/61)
[#259 Browse Collections - List View](https://github.com/scientist-softserv/utk-hyku/issues/259)
[#260 Browse Collections - Finalize Section](https://github.com/scientist-softserv/utk-hyku/issues/260)

## Screenshots
![Screenshot 2023-01-31 at 11 36 27 AM](https://user-images.githubusercontent.com/39319859/215865326-dfe8aa17-2994-444a-896b-eaba08b2c4ea.JPG)
![Screenshot 2023-01-31 at 11 36 21 AM](https://user-images.githubusercontent.com/39319859/215865339-764fad50-f866-477e-8a34-1149d40eab77.JPG)

## Acceptance Criteria
- [ ] Browse collections section is gone from the homepage
- [ ] View all collections button is in Featured Collections section now
- [ ] Featured collections thumbnails are resized to 300px height and spacing is correct

**Comment by AKFosterDev** [comment]
Client approved new figma design from [ticket #324](https://github.com/scientist-softserv/utk-hyku/issues/324) 
Unblocked issue.

**Comment by AKFosterDev** [comment]
Blocked by approved change request.

**Comment by ShanaLMoore** [comment]
Jeremy's recommendation is to eventually remove the code, if the client has confirmed they don't want it. 

In the intermediary, display none may be ok.

**Comment by ShanaLMoore** [comment]
We are leaving this section afterall. The client will take care of any additional changes they want to make.
