### ISSUE TITLE
Figma design - DC Contact Page

### ISSUE THREAD

**Issue by AKFosterDev** [notch8/utk-hyku#330]
## Summary
Complete Figma design for the Theme DC Contact page.
[Figma design](https://www.figma.com/file/3JjoRJYmCrfoAcWhHu2Br4/UTK?node-id=0%3A1&t=Wk5BjlmDIwhNDfKb-1)

## Related Tickets
- https://github.com/scientist-softserv/utk-hyku/issues/332

## Acceptance Criteria
- [x] Complete Figma design of page
- [x] Client approval of design

## Screenshots
**Proposed Design for Client Approval**
![contact ](https://user-images.githubusercontent.com/39319859/218533239-83546ee6-30da-4cff-a41a-f5ed9d06d058.JPG)

**Current Page**
![contact current](https://user-images.githubusercontent.com/39319859/217633618-fd1822bd-f419-493b-9d83-2ea939ad050f.JPG)

**Comment by josh-morgan117** [comment]
@AKFosterDev Are the form fields configured in the Hyku dashboard?

**Comment by AKFosterDev** [comment]
@kidon0011 The form fields come from Hyrax and are not configurable.

**Comment by josh-morgan117** [comment]
@AKFosterDev Thanks, I've pinged the team about the theme tickets in Client QA. We should get back to you early next week.
