### ISSUE TITLE
DC Contact Page

### ISSUE THREAD

**Issue by AKFosterDev** [notch8/utk-hyku#332]
## Summary
Theme DC Contact page to reflect figma design completed in the related ticket.

## Related Tickets
Figma Design - [#320](https://github.com/scientist-softserv/utk-hyku/issues/320)

## Acceptance Criteria
- [x] DC contact page looks like figma design
- [x] DC contact page is responsive

## Screenshots
**Approved Design**
![image](https://user-images.githubusercontent.com/39319859/220463155-cc7ae8d4-90c1-4eae-b1a1-ddbc685127f2.png)

**Current Page**
![contact current](https://user-images.githubusercontent.com/39319859/217633618-fd1822bd-f419-493b-9d83-2ea939ad050f.JPG)

## QA Instructions
- These changes only apply to the DC Repository theme - all other themes should have default styling
- Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- In Admin dashboard under Appearance/Theme 
- [ ] Home Page Theme - choose DC Repository
- [ ] Search Results Page Theme dropdown - choose DC view
- [ ] Show Page Theme - choose DC Show Page
- General breakpoints
- full screen
- 991px
- 767px

**Comment by jillpe** [comment]
SoftServ QA: Pass!

Logged in under an admin user, set the Themes to the above specifications. Opened the contact page and it matches the wireframe and is responsive from the full screen to 767px

<details><summary>Screenshots</summary>

![Image](https://user-images.githubusercontent.com/84697174/221900430-e3c83942-9a9e-42c9-a28d-513926500f9d.png)



![Image](https://user-images.githubusercontent.com/84697174/221900462-401acbeb-046c-4314-93d3-a9954bc82c78.png)
</details>

**Comment by jillpe** [comment]
Approved in client meeting 2/28/2023
