### ISSUE TITLE
DC About Page Layout

### ISSUE THREAD

**Issue by AKFosterDev** [notch8/utk-hyku#333]
## Summary
Implement DC about page compressed header and footer elements to reflect figma design completed in the related ticket. This ticket is the first part of this page. 

The contents of the About page are populated from a WYSIWYG editor through the dashboard UI. Need client input on actual contents of the page as reflected in ticket #350 below.

## Related Tickets
**Approved** Figma design - [#331](https://github.com/scientist-softserv/utk-hyku/issues/331) 

**Waiting for client input on content** DC About Page Content - [#350](https://github.com/scientist-softserv/utk-hyku/issues/350)

## Acceptance Criteria
- [x] DC about page header and footer looks like figma design
- [x] DC about page header and footer are responsive

## Screenshots
**Approved Design**

![Image](https://user-images.githubusercontent.com/39319859/221626295-50759882-90cf-480b-96c4-a6679d99a4fb.JPG)

**Current Page - Content Populated from WYSIWIG editor in dashboard (locally)**
![Screenshot 2023-02-28 at 8 19 23 AM](https://user-images.githubusercontent.com/39319859/221913715-a1cbc608-f7bb-4815-b0fc-aa5e45d30578.JPG)
![Screenshot 2023-02-28 at 8 19 35 AM](https://user-images.githubusercontent.com/39319859/221913779-e2e0761e-e615-4703-af47-0924aacd676e.JPG)

## QA Instructions
- These changes only apply to the DC Repository theme - all other themes should have default styling
- Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- In Admin dashboard under Appearance/Theme 
- [ ] Home Page Theme - choose DC Repository
- [ ] Search Results Page Theme dropdown - choose DC view
- [ ] Show Page Theme - choose DC Show Page
- General breakpoints
- full screen
- 991px
- 767px

**Comment by markpbaggett** [comment]
@AKFosterDev this looks good to me.  If we bump this along, can we get it deployed to staging?

**Comment by AKFosterDev** [comment]
@markpbaggett This ticket is currently deployed to staging. The interior content of the page comes from a WYSIWYG editor within the dashboard. [Here](https://dc.utk-hyku-staging.notch8.cloud/pages/edit?locale=en) is a link to the page on staging.

The tickets in the Client QA column are deployed to staging for UTK to QA. Once that's complete, the tickets will be moved and deployed to production where they get a final client verification.

**Comment by markpbaggett** [comment]
@AKFosterDev apologies. we figured this out some time last wednesday, but didn't update the ticket.
