### ISSUE TITLE
DC File Set Show Page

### ISSUE THREAD

**Issue by AKFosterDev** [notch8/utk-hyku#335]
## Summary
Theme DC file set show page to reflect figma design completed in the related ticket.

## Related Tickets
**Currently blocked by:**
Figma Design - https://github.com/scientist-softserv/utk-hyku/issues/334

## Acceptance Criteria
- [x] DC file set show page looks like figma design
- [x] DC file set show page is responsive

## Screenshots
**Approved Design**
![image](https://user-images.githubusercontent.com/39319859/222264953-382d0412-f0c7-4efb-8a07-7dbc2158146e.png)

**Current Page Logged In**

https://user-images.githubusercontent.com/39319859/217660588-fde61923-65ca-4b94-bf5f-29936b815c18.mp4

**Current Page Logged Out**

https://user-images.githubusercontent.com/39319859/217660595-65a7804a-9c5c-4b69-9ecb-229433a29163.mp4

## QA Instructions
- These changes only apply to the DC Repository theme - all other themes should have default styling
- Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- In Admin dashboard under Appearance/Theme 
- [x] Home Page Theme - choose DC Repository
- [x] Search Results Page Theme dropdown - choose DC view
- [x] Show Page Theme - choose DC Show Page
- General breakpoints
- full screen
- 991px
- 767px

**Comment by jillpe** [comment]
SoftServ QA: PASS!

Confirmed DC Repository Theme settings were saved. DC File Set Show Page matches wireframe in both logged in and logged out, and is responsive. Tested [this](https://dc.utk-hyku-staging.notch8.cloud/concern/parent/7b2ae5b2-93e0-4d9f-859d-6f26c673d13b/file_sets/117a7e32-54ab-4f58-bd41-f9a0bcd8380b) file set

<details>
<summary>Logged Out Screenshots</summary>
Full Screen
![image](https://user-images.githubusercontent.com/84697174/222779523-b892f713-fc80-4e76-8981-e24738375796.png)

Small Screen
![image](https://user-images.githubusercontent.com/84697174/222779554-10b79bdf-7b28-4d0f-9177-75e54f38c4c1.png)

</details>

<details>
<summary>Logged In Screenshots</summary>
Full Screen
![image](https://user-images.githubusercontent.com/84697174/222784408-bcdf5a13-a255-4239-9a56-0b295858dbb3.png)

Small Screen
![image](https://user-images.githubusercontent.com/84697174/222784492-4ff9013e-ce33-448a-be55-d98f035d93e4.png)

</details>

**Comment by ShanaLMoore** [comment]
# QA RESULTS: PASS ✅ 


SET THEMES TO DC:
![Image](https://user-images.githubusercontent.com/10081604/222783868-94267824-610a-428f-a755-32381da7ecd5.png)

FILE SET SHOW PAGE logged in: 



![Image](https://user-images.githubusercontent.com/10081604/222784035-bc412271-98a9-4665-8166-63303720d470.png)


FILE SET SHOW PAGE logged out: 

![Image](https://user-images.githubusercontent.com/10081604/222784140-9014c47c-1cc7-486e-871e-b12271bd8451.png)


FILE SET SHOW PAGE is responsive: 




![Image](https://user-images.githubusercontent.com/10081604/222788083-fcfed1ca-e427-421c-a5df-3064f525fe60.png)

**Comment by markpbaggett** [comment]
@AKFosterDev this looks good.  Bumping forward.
