### ISSUE TITLE
DC About Page Content

### ISSUE THREAD

**Issue by AKFosterDev** [notch8/utk-hyku#350]
## Summary
The contents of the About page are populated from a WYSIWYG editor through the dashboard UI. Need client input on actual contents of the page. Initial layout completed on ticket #333 below
## Related Tickets
**Approved** Figma design - [#331](https://github.com/scientist-softserv/utk-hyku/issues/331) 

**Completed** DC About Page Layout - [#333](https://github.com/scientist-softserv/utk-hyku/issues/333)

## Acceptance Criteria
- [ ] DC about page content looks similar to the figma design
- [ ] DC about page content are responsive

## Screenshots
**Approved Design**

![Image](https://user-images.githubusercontent.com/39319859/221626295-50759882-90cf-480b-96c4-a6679d99a4fb.JPG)

**Current Page**
![Image](https://user-images.githubusercontent.com/39319859/221941163-db6b9f65-6f31-4f18-bc44-6a1690e60502.JPG)

![Image](https://user-images.githubusercontent.com/39319859/221941174-8874bfe9-f111-4936-919b-a8f673af4d0c.JPG)

## QA Instructions
- These changes only apply to the DC Repository theme - all other themes should have default styling
- Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- In Admin dashboard under Appearance/Theme 
- [ ] Home Page Theme - choose DC Repository
- [ ] Search Results Page Theme dropdown - choose DC view
- [ ] Show Page Theme - choose DC Show Page
- General breakpoints
- full screen
- 991px
- 767px

**Comment by jillpe** [comment]
No longer a priority per adjusted priority list 2023-04
