### ISSUE TITLE
Header Fixes

### ISSUE THREAD

**Issue by AKFosterDev** [notch8/utk-hyku#352]
## Summary
ref
- #411 
- #7 

The menu button in the top header is not being used and should be removed. The header 'breaks' at smaller screen sizes.

## Acceptance Criteria
- [x] Remove 'Menu' button from header - Not being used.
- [x] Make sure header doesn't break on responsive breakpoints

## Screenshots
**Before this ticket**
![Image](https://user-images.githubusercontent.com/39319859/223172186-e7c3a7b9-df57-48c7-a33c-49057322f90a.JPG)

**Comment by DeonFranklin** [comment]
This passes SoftServ QA.

Tested on : https://dc.utk-hyku-staging.notch8.cloud/?locale=en
The menu button has been removed and the header did not break on responsive breakpoints.

![Image](https://user-images.githubusercontent.com/95306716/223762715-15c3bcc1-dace-4cd8-88a3-c97ce3369dac.png)

**Comment by josh-morgan117** [comment]
The header is off on collection and file pages since the logo doesn't change to just the T logo when on mobile (unless that's not a part of the criteria for this ticket).

**Comment by AKFosterDev** [comment]
@kidon0011 I see what you are talking about. Taking a look...

**Comment by jillpe** [comment]
SoftServ QA: Pass!

- Tested header on full screen and small screen on Home, About, Contact, Collection, and Search Page
- Menu button is gone
- Logo changes to just the 'T' in small screen response

<details>
<summary>Screenshots</summary>
Home Page
<img width="1439" alt="Screen Shot 2023-03-13 at 1 27 29 PM" src="https://user-images.githubusercontent.com/84697174/224796922-19eb82cb-94a1-49a9-83ef-7be70bc9c97a.png">
<img width="709" alt="Screen Shot 2023-03-13 at 1 27 38 PM" src="https://user-images.githubusercontent.com/84697174/224796971-9160712a-3f79-4de8-bf0d-b9750e9847dd.png">

About Page
<img width="1437" alt="Screen Shot 2023-03-13 at 1 27 51 PM" src="https://user-images.githubusercontent.com/84697174/224797221-7a22d08c-c4ff-4699-8eb7-ed1e700319dd.png">
<img width="760" alt="Screen Shot 2023-03-13 at 1 27 58 PM" src="https://user-images.githubusercontent.com/84697174/224797237-ab17bdc8-fcc4-405c-b3b4-971a2b7e6e82.png">

Contact Page
<img width="1438" alt="Screen Shot 2023-03-13 at 1 28 10 PM" src="https://user-images.githubusercontent.com/84697174/224797315-160315e1-d2fa-42be-a05c-d5e80e19ed98.png">
<img width="674" alt="Screen Shot 2023-03-13 at 1 28 17 PM" src="https://user-images.githubusercontent.com/84697174/224797347-476a6eb2-f4c0-418e-9068-7deef827ba23.png">

Collection Page
<img width="1436" alt="Screen Shot 2023-03-13 at 1 28 31 PM" src="https://user-images.githubusercontent.com/84697174/224797398-83a443f7-637f-49ab-b673-09e7971d77d7.png">
<img width="641" alt="Screen Shot 2023-03-13 at 1 28 38 PM" src="https://user-images.githubusercontent.com/84697174/224797408-a10fcfdf-2537-46cd-98ac-3e849941ba2d.png">

Search Results Page
<img width="1438" alt="Screen Shot 2023-03-13 at 1 29 09 PM" src="https://user-images.githubusercontent.com/84697174/224797429-f344c23e-358c-4fc2-9a61-a26c046eb52b.png">
<img width="649" alt="Screen Shot 2023-03-13 at 1 29 17 PM" src="https://user-images.githubusercontent.com/84697174/224797434-3a0b461d-af19-4441-900e-ec6e84e799f9.png">



</details>

**Comment by josh-morgan117** [comment]
https://user-images.githubusercontent.com/14128309/225089389-9cefafb2-de3d-453d-bcea-6e93043458af.mp4


My computer still has this issue in staging, if I dock it to either side of the window.

**Comment by markpbaggett** [comment]
@AKFosterDev not sure if this is related to me looking at staging and not "local", but the text drops below the search box on both Firefox and Chrome for me (on About at least):



![Image](https://user-images.githubusercontent.com/2692416/225086105-112ab1a5-a55b-4e4a-8e68-4757031ef9b9.png)
![Image](https://user-images.githubusercontent.com/2692416/225086106-4016648e-6e3c-4839-8e2a-3ee7ff87f121.png)

**Comment by DeonFranklin** [comment]
@AKFosterDev and I tested this on staging and it appears to be working fine. @markpbaggett Could you please test this again on your end so we can close this ticket?

**Comment by josh-morgan117** [comment]
@DeonFranklin The header looks good. Thanks!

**Comment by markpbaggett** [comment]
@DeonFranklin sorry for not seeing this earlier.  Looks good to me.
