### ISSUE TITLE
Configure IiifPrint in UTK

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#354]
# Summary

Once IiifPrint is installed, we should communicate with the client to clarify which configurable features to enable. 

Give the client the options or review their SOW (look in google drive or ask Jill), and update this ticket with what needs to be done.

# Acceptance Criteria

- [ ] Setting pdf splitting for attachment model 
- [ ] Text derivative only 

# Screenshots or Video

# Testing Instructions

# Notes

We will have a fair bit of reconciliation to do, after installing and configuring iiif_print. We did work prior to iiif_print so there is a bunch of overrides that we'll need to consider/reconsider.

**Comment by jillpe** [comment]
Goal is to determine the configurations

**Comment by ShanaLMoore** [comment]
client has their own hocr files

**Comment by ShanaLMoore** [comment]
closing. QA is captured in [this ticket](https://github.com/scientist-softserv/utk-hyku/issues/358)
