### ISSUE TITLE
BUG: Deleting filesets causes faraday timeout issues in production

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#361]
# Summary

Faraday timeout error is occurring when Bulkrax::DeleteFileSetJob

![Image](https://user-images.githubusercontent.com/10081604/223522931-5b85ca64-7d47-4854-b9eb-56e5f9601203.png)

# Steps to reproduce

Bulkrax: [wpatva_cleanup_delete.csv](https://github.com/scientist-softserv/utk-hyku/files/10913088/wpatva_cleanup_delete.csv)

Not all of the files delete successfully because of faraday timeout. 

# Acceptance Criteria

- [ ] Bulkrax::DeleteFileSetJob works and does not produce a timeout issue

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by DeonFranklin** [comment]
The following screenshot shows the result from my import 

![image](https://github.com/scientist-softserv/utk-hyku/assets/95306716/be8d9156-b4d4-4f78-bd79-a498d189a1df)

**Comment by jillpe** [comment]
closed - no longer an issue
