### ISSUE TITLE
Address spec failures: UTK

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#367]
# Summary

I updated UTK's github workflow to pull in a bug fix found in gh actions. The pipeline should fail when specs do. However in doing so, it exposed several spec failures. 

ref: https://github.com/scientist-softserv/utk-hyku/pull/366

failure ref: https://github.com/scientist-softserv/utk-hyku/actions/runs/4418051866/jobs/7744974009

![Image](https://user-images.githubusercontent.com/10081604/225084965-1be4d8d2-c318-4928-8d4a-72d7138df525.png)

**Comment by jillpe** [comment]
closed - no longer relevant
