### ISSUE TITLE
populate parent thumbnail (rake task)

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#369]
# Story

Given the UTK's work structure (parent work has an attachment which owns the file_sets), the parent works do not have a thumbnail. 

We need to make the parent work have a thumbnail. Additionally, when clicking on the parent work, its UV should display its attachment (child works) and their file_sets.

# Acceptance Criteria
The following should be a rake task that we can manually trigger. (Future thought -- should we make a UI component so the user can trigger this themselves?)

After the rake task is run ...

- [ ] parent work is does not require a file upload. It will not have a thumbnail if the parent doesn't upload one. ref: https://github.com/samvera/hyrax/blob/74d80612ae58c6d034d1ee192f608a4a2e20147f/lib/generators/hyrax/templates/config/initializers/hyrax.rb#L108
- [ ] when the parent work doesn't have a file, but it has an attachment/child work with file_sets, its thumbnail should match it's child's thumbnail
- [ ] the parent UV should display its child works and their file sets, even when the parent work doesn't have its own file.

# Screenshots / Video

![Image](https://user-images.githubusercontent.com/10081604/228788937-94ea37f8-b03d-431d-96d5-13b5be16d10d.png)

![image](https://user-images.githubusercontent.com/10081604/228793405-b1a34313-cb24-440e-867d-4f4ccf8b8373.png)

# Testing Instructions and Sample Files

⚠  QA by dev ⚠ Close if it passes QA, no need for client review

This may be best done via manual creations. Manually create a parent work with no fileset attached. On the parent's show page, click the option to Add a child work to it. Create an attachment with a jpg fileset attached. The attachment should have a thumbnail after all the jobs are done. At this point, the parent work should still not have a thumbnail.

Run the rake task. The parent work should have a thumbnail that matches its child's thumbnail (aka the attachment you just created), once the task is complete. 

# Notes

LOUISVILLE had a similar set up, where the parent work did not have a thumbnail. They wanted it set to the first child's first file_set. 

We created a job: https://github.com/scientist-softserv/louisville-hyku/blob/main/lib/tasks/set_parent_thumbnail.rake

We created a rake task for them to manually run: https://github.com/scientist-softserv/louisville-hyku/blob/main/app/jobs/set_default_parent_thumbnail_job.rb

**Comment by ShanaLMoore** [comment]
working on this to unblock Diem's iiif_print testing

ref: https://github.com/scientist-softserv/iiif_print/issues/173#issuecomment-1485882880

**Comment by ShanaLMoore** [comment]
a WIP PR has been started: https://github.com/scientist-softserv/utk-hyku/pull/379

However, this may be less urgent again if Diem could test against ESSI instead.

**Comment by ShanaLMoore** [comment]
@kirkkwang  included this work in [this PR](https://github.com/scientist-softserv/utk-hyku/pull/435/files#diff-dc1057ebede4e8ecfe6b392b83e241fba1c9e2419aa3fb12d3a2b95809c1accb) i believe we can close this or push it through the columns to be QA'd by a dev.

**Comment by DeonFranklin** [comment]
This ticket passes SoftServ QA:
The parent thumbnail populated after the rake task was completed.

![Image](https://github.com/scientist-softserv/utk-hyku/assets/95306716/3abd02fe-a9e1-4633-8d0a-c290dc9408fa)



![Image](https://github.com/scientist-softserv/utk-hyku/assets/95306716/d91ebee0-cc1a-469d-ad79-40291528dcf7)



![Image](https://github.com/scientist-softserv/utk-hyku/assets/95306716/e785f70b-9290-4c66-be84-eacf26a29d74)



![Image](https://github.com/scientist-softserv/utk-hyku/assets/95306716/c95fa3a3-eaf9-44c5-a3d7-4e550c87b7cd)
