### ISSUE TITLE
Spike: Correct margins

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#384]
# Summary
ref
- #411 
- #7 

The left and right margins do not line up with the header, navbars, main body, and footer

# Accepted Criteria
- [ ] As a user, the margins line up with the header, navbars, main body, and footer throughout the entire site

# Screenshots and Videos

# Testing Instructions

# Notes

**Comment by jillpe** [comment]
Related to 
- #352

**Comment by ShanaLMoore** [comment]
Closing ticket until client points out the issue again. I am not seeing anything wrong and there are no screenshots to guide me to the issue.

<details>

<summary>CHROME: </summary>



![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/074643a8-f3b0-4913-a322-6a029a3cc244)



</details>
<details> 
<summary> FIREFOX: </summary>



![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/de22d531-2d5b-4578-860c-f868a7ef521c)

</details>
