### ISSUE TITLE
[ ] Selenium: WebDriver Error

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#39]
**Summary of the issue:**

It appears that the M1 macs (belonging to Amanda and Selam) can't run feature specs due to a selenium web driver error that reads:
```
Selenium::WebDriver::Error::UnknownError:
            unknown error: Chrome failed to start: crashed.
              (chrome not reachable)
              (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
            Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
            System info: host: '45da43a15a4e', ip: '172.18.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.104-linuxkit', java.version: '1.8.0_292'
            Driver info: driver.version: unknown
``` 
**How to re create the issue:** 

In reference to the UTK project, you can test spec/features/**create_generic_work_spec.rb:42**

This specific spec along with other feature specs failed due to the above error message. However, the feature spec: proprietor_spec.rb had passed without triggering the error message. 

**Efforts to resolve the issue:**

Modified docker-compose.yml to add `platform: linux/amd64` and the failing spec still errored out with the same error message.

**Resources:** 
- [Arm supported docker image for Selenium](https://github.com/SeleniumHQ/docker-selenium/issues/1076)
- [Documentation](https://github.com/seleniumhq-community/docker-seleniarm#experimental-mult-arch-aarch64armhfamd64-images)
- [Docker Hub Seleniarm](https://hub.docker.com/u/seleniarm)

**Comment by DiemBTran** [comment]
Linked items:

- Spin Up Project

**Comment by DiemBTran** [comment]
Shana June 2022

---

Confirmation that as a non m1 mac user - I am able to run the entire spec suite without seeing this error.

Additionally, I believe Amanda and April have been solving this for Harvard. I'm not sure if they've resolved it yet but we should ask.

**Comment by DiemBTran** [comment]
Crystal July 2022

---

Selam Can you confirm if this can be closed.

---

Selam July 2022

---

Hi Crystal, 

Thanks for following up on this issue. I tested a feature spec: `spec/features/admin_dashboard_spec.rb`

Unfortunately, the error persists but this time its a **Net::ReadTimeout:**



![Image](https://user-images.githubusercontent.com/29311858/203178958-03538c11-7c33-4e8f-bc15-38f1027b6be7.png)



Also, the browser play of the feature spec in http://chrome.hyku.test/ doesn't play. Hopefully, that makes sense.

**Comment by jillpe** [comment]
covered in #367
