### ISSUE TITLE
📎 SOW: UV showing at the work level

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#391]
# Summary
Currently, UTK references a work's file(s) as an attachment. They would instead like primary file(s) to be displayed in the Universal Viewer

# Accepted Criteria
- [ ] As an admin user, when I import a work, the primary file(s) are displayed in the Universal Viewer
- [ ] As a user, when I visit a work, I can view the primary file(s) in the Universal Viewer

To Do:
- [ ] test and potentially update iiif print

# To Do
- #438 
- #98 
- #427 
- #409 
- #422 
- #439 
- #358 

# Notes
- Lv work might solve this

**Comment by markpbaggett** [comment]
@jillpe this looks good! We approve this SOW as is.

**Comment by kirkkwang** [comment]
relevant draft PR
- https://github.com/scientist-softserv/utk-hyku/pull/399
