### ISSUE TITLE
Spike: Importer woes

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#396]
# Story

ref: https://assaydepot.slack.com/archives/C0396LSM06P/p1682963901910269

"hey all, i have a weird one.  last week, i started reimporting bulkrax sheets to remove URIs and replace them with strings using our same m3 profile and keeping things in line with that. for some reason, the importers aren’t really working. in spots, a work will complete and looks like it should, but not everywhere. [here is an example importer](https://dc.utk-hyku-production.notch8.cloud/importers/205?locale=en) and below is a the sheet that went with it.  the error we’re getting when things fail is: `NoMethodError - undefined method work?' for nil:NilClass.  when things “Complete”, they look right as can be seen [here](https://dc.utk-hyku-production.notch8.cloud/concern/images/2e6c93cb-bec5-4367-99dc-e7df7c72fb28?locale=en) (we recognize the form, resource type, and rights statements fields are still uris, but that’s because we didn’t update our m3 yet to add fields for these.  when a work fails, nothing gets updated as can be seen [here](https://dc.utk-hyku-production.notch8.cloud/concern/images/be80be93-31e0-4811-ad68-ffc780257840?locale=en).  before we try to do anything else here, do you all know what this error might mean?" - Mark

here is the import sheet in case that is useful:
[archivision_full_no_uris_restricted_chunk_0.csv](https://github.com/scientist-softserv/utk-hyku/files/11374348/archivision_full_no_uris_restricted_chunk_0.csv)

# Acceptance Criteria

- [ ] Importers that say they are 'Complete' fully update
- [ ] The above importer is updated

# Screenshots / Video

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

-

# Notes

Related to prior collection issue per these slack conversations - the same works are the ones affected.
- https://assaydepot.slack.com/archives/C0396LSM06P/p1675948966619819
- https://assaydepot.slack.com/archives/C0396LSM06P/p1676478554680999
-

**Comment by markpbaggett** [comment]
Hey all, since I can't see the Slack threads above, I did want to include that I'm almost certain that this relates to these threads as well:

https://utkdigitalinitiatives.slack.com/archives/C0396LSM06P/p1675948966619819

https://utkdigitalinitiatives.slack.com/archives/C0396LSM06P/p1676478554680999

We're only running into errors if it's from a collection that was affected like the above.

**Comment by jillpe** [comment]
Why is this csv different than others?

**Comment by jillpe** [comment]
This was resolved
