### ISSUE TITLE
Unblock audio ingest

### ISSUE THREAD

**Issue by kirkkwang** [notch8/utk-hyku#398]
# Story

UTK cannot ingest audio because they are not creating derivatives.

# Acceptance Criteria

- [ ] Audio ingests successfully
- [ ] Any audio with `IntermediateFile` rdf_type does play
- [ ] Any audio with `PreservationFile` rdf_type does not play

# Testing Instructions and Sample Files

- [x] Create an `Attachment` work with an audio file
  - [x] In the `Rdf type` field add `http://pcdm.org/use#IntermediateFile`
- [x] observe that the file plays
- [x] Create an 'Attachment' work with an audio file
  - [x] In the `Rdf type` field add `http://pcdm.org/use#PreservationFile`
- [x] observe that the file does not play

# Notes

**Comment by jillpe** [comment]
SoftServ QA: Pass!

[Intermediate File URL](https://dc.utk-hyku-staging.notch8.cloud/concern/attachments/89df829e-7ede-4daa-aeec-4988206b8f08?locale=en)
- Uploaded mp3 file as an attachment and with `Rdf type` of `http://pcdm.org/use#IntermediateFile`
- File played
<details><summary>Video</summary>


https://github.com/scientist-softserv/utk-hyku/assets/84697174/a15d96b6-88d1-49ac-81bf-7445b259074d


</details>


[Preservation File URL](https://dc.utk-hyku-staging.notch8.cloud/concern/attachments/094e31c8-4f9e-47b2-a717-1f11db384181?locale=en)
- Uploaded mp3 file as an attachment and with `Rdf type` of `http://pcdm.org/use#PreservationFile`
- File did NOT play
<details><summary>Video</summary>


https://github.com/scientist-softserv/utk-hyku/assets/84697174/84bb06b5-af38-48c1-a73e-4d21a7bbfd24


</details>

**Comment by markpbaggett** [comment]
@jillpe and @kirkkwang this looks good to me.  One question though--In the future, will UV be on the "Work" page for the attachment for preservation files? Right now, it seems that it does show up, but the audio is never playable.  On the FileSet page, the HTML5 Audio Canvas in greyed out.  To me, it seems misleading for UV to be there if the file is not playable.

**Comment by kirkkwang** [comment]
@markpbaggett I have a draft [PR](https://github.com/scientist-softserv/utk-hyku/pull/399) waiting in the wings to address that.  I am going off the assumption that only intermediate files should show in the UV.  Is that correct?

**Comment by markpbaggett** [comment]
@kirkkwang that is correct. Thanks for your help on this.
