### ISSUE TITLE
📎 SOW: Group / Roles

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#4]
# Summary
New Goals
we just want to be able to have a simple workflow in addition to what we have now where a "Submitter" or "Student" can deposit, but an "administrator" can review and approve before go live. Ideally, this would also allow us to have someone with both roles and not need to review if they are carrying out the operation. We're not sure if this works with sipity / admin sets, so let's talk about whether we'd have to apply 1 or the other workflow for each collection since each collection has its individualized admin set.

<details><summary>Old Requirements</summary>
Supports defining complex workflows and specific roles with unique privileges to users in a collection such as:
- Anonymous users : unauthenticated
- Submitter : authenticated user; can submit items (objects) to one or more collections
- Collection administrator/Editor : can add/remove submitters to a collection; can approve and publish / reject submissions; can edit item metadata; can withdraw items from public view; can assign Reviewers to submissions
- Reviewer :  can view an item not yet published and provide comments to Collection administrator/Editor.
- Repository administrator : can perform all functions of the collection administrator for the entire repository; can add new collections

The work that Palni/Palci project started will be contributed back to hyku and made available to the community.  Then the UTK project will receive an upgrade to include this work.  

To Do:
  - [ ] Hyku is updated to Hyku v5
  - [ ] Allinson flex is compatible with the upgraded Hyku
  - [x] #507 

</details>

# Notes
**How will these user levels be set**

https://github.com/samvera/hyku/wiki/Groups-with-Roles-Feature

**Comment by markpbaggett** [comment]
@jillpe, this looks good but is very closely aligned with Institutional repository which can come post migration.  Instead, I think we just want to be able to have a simple workflow in addition to what we have now where a "Submitter"  or "Student" can deposit, but an "administrator" can review and approve before go live.  Ideally, this would also allow us to have someone with both roles and not need to review if they are carrying out the operation.  We're not sure if this works with sipity / admin sets, so let's talk about whether we'd have to apply 1 or the other workflow for each collection since each collection has its individualized admin set.

**Comment by jillpe** [comment]
[Audit Notes from 8/2023](https://github.com/scientist-softserv/utk-hyku/issues/529)

**Groups and Roles**

[Workflow Mark requested:](https://github.com/scientist-softserv/utk-hyku/issues/4#issuecomment-1531653670)
- We could have one admin set that all participants can deposit into that goes through review - and then the default admin set would remove permissions for everyone except admins to deposit into. This would then give you the ability to have an administrators or chosen set of ppl submitting without review and everything else goes through a review process
  - UTK said this would be okay for right now, but still wanted to have the groups and roles features for their future workflows

Testing based on [Groups and Roles documentation](https://github.com/samvera/hyku/wiki/Groups-with-Roles-Feature#defining-roles-users-and-groups)
* Groups
  * [Do not have the ability](https://dc.utk-hyku-staging.notch8.cloud/admin/groups/new?locale=en)
  
* Workflow Roles
  * Have the option to assign roles, however, it does not appear to save
    * Ex. admin@example.com should only have ability to deposit/access Default Admin set, however has the ability to create a work type for all of the sets (Mountains, Default Admin, Submission Review

* Users
  * [Could not add users/roles through Dashboard](https://dc.utk-hyku-staging.notch8.cloud/admin/users?locale=en)
    * Shows that the user's status is pending (ex. jill@scientist.com user), however email was never sent to her

**Comment by jillpe** [comment]
Next Steps:
- Can this be implemented without needing the groups and roles feature

**Comment by jillpe** [comment]
Confirmed in meeting 2024-04-09, this is no longer a requirement. The workflow discussed [above](https://github.com/scientist-softserv/utk-hyku/issues/4#issuecomment-1531653670) does not require the feature. Closing this ticket and making a new one to implement the above workflow
