### ISSUE TITLE
🦄 Spike: Redis error upon imports with filesets

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#400]
# Summary
UTK was importing image collections and ran into an error: `Redis::CommandError - NOSCRIPT No matching script. Please use EVAL.` It was confirmed the error was happening for all imports

Importer: https://dc.utk-hyku-production.notch8.cloud/importers/228?locale=en

CSV: 

[open_open_nouris_chunk_0_with_attachments_with_filesheets_and_attachments_only_0.csv](https://github.com/scientist-softserv/utk-hyku/files/11517642/open_open_nouris_chunk_0_with_attachments_with_filesheets_and_attachments_only_0.csv)

Slack Thread: https://assaydepot.slack.com/archives/C0396LSM06P/p1684448545536509

# Accepted Criteria

- [ ] The problem is identified and follow up tickets are created

# Notes

**Comment by laritakr** [comment]
A deploy took care of it. see https://assaydepot.slack.com/archives/C0396LSM06P/p1684777887568099
