### ISSUE TITLE
🦄 Spike: UV showing at work level reorientation

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#409]
# Summary
ref: #391  
We need to reorient ourselves with where we are at in the process, so we can break down the remaining tasks. If there are questions we need answers to to unblock the task breakdown, we need to take note of them in a follow up spike ticket and tag it in the [meeting notes](https://docs.google.com/document/d/1GsoeK7gkBq3yziAVIK4Fijihd7jNo5nkc0Fnj8K1-B4/edit#)

# Acceptance Criteria
- [ ] Current status of the UV showing is documented
- [ ] Relevant prs, tickets, notes, etc. are documented 
- [ ] Determining how much is left and if additional breakdown is needed

**Comment by kirkkwang** [comment]
relevant draft PR:
https://github.com/scientist-softserv/utk-hyku/pull/399

**Comment by laritakr** [comment]
blocked by:
- #421

**Comment by jillpe** [comment]
closed - tickets are created and labeled with the 'UV' label
