### ISSUE TITLE
Failing Specs

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#412]
# Summary
Address the easy fixes and mark the remaining as to-do's. Timebox to a day. 

- [ ] #418
- [ ] #414

# Acceptance Criteria
- [ ] the pipeline is passing
- [ ] easy fixes are fixed
- [ ] remaining fixes are marked as to-do's and follow-up tickets are created for them
  - [ ] #418
  - [ ] #414

**Comment by ShanaLMoore** [comment]
My current plan is to comment out the feature specs and make it its own ticket. I've spent a significant time discovering a blocking issue that I will go to Rob's office hrs for help on. 

ref:
