### ISSUE TITLE
Add Jemalloc

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#415]
# Story

Add Jemalloc to improve ingest speeds.

# Acceptance Criteria

- [ ] Add Jemalloc to the docker file. Ref this PR for Adventist: https://github.com/scientist-softserv/adventist-dl/pull/429

# Acceptance Criteria

- [ ] Verify Jemalloc is installed. 

# Testing Instructions and Sample Files

QA does not require internal QA. A dev will check the following in the various envs

- In the shell, a dev should be able to get an output when typing export | grep LD_PRELOAD

**Comment by kirkkwang** [comment]
<img width="600" alt="image" src="https://github.com/scientist-softserv/utk-hyku/assets/19597776/73d8e44e-772e-4681-8b39-bda758d56eb5">
