### ISSUE TITLE
Local Authorities show URI rather than term in facet list

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#419]
# Summary
Terms such as Resource Type and License are based on local authority files. Faceting currently does not support resolving these to the terms.

![Image](https://github.com/scientist-softserv/utk-hyku/assets/17851674/1ab0585c-035e-4bf9-9974-2f20a0d9f55a)

# Acceptance Criteria
- [ ] Local authorities show term in facet list

**Comment by jillpe** [comment]
No longer necessary
