### ISSUE TITLE
[5] Add Feature Flipper for PDF UV viewing at a per tenant level

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#42]
ref: https://github.com/samvera/hyku/pull/1777

# Summary

Hyku will be updated to allow PDFs to be viewed in the UV on default. After this merge, there is currently no way for users to  say that they don't want this.
 
The client does not want to view PDFs in the UV so we need to create a feature flipper around this feature and contribute it back to hyku.

# Acceptance Criteria

- [ ] A user should have the ability to control whether or not they can view PDFs in the UV (toggle on/off from the admin features section). 
- [ ] These options should not affect other tenants' ability to view PDFS

# Screenshots or Video

![Image](https://user-images.githubusercontent.com/29311858/203177891-a2e508cb-4530-4414-b679-0f94063cebcb.png)

# Testing Instructions
1. Login into staging as an admin user. 
1. From the left side bar, navigate to Settings > Features
1. There should be "View PDF In App" toggable feature option. When visiting a work's show page that has a pdf...

  - [ ]  when toggled on, PDFs should be viewed in the UV
  - [ ] when toggled off, PDFs should not be viewed in the UV. They should be downloadble.
  - [ ] Each tenant should have their own configuration

# Notes

**Comment by DiemBTran** [comment]
Related MRs:

- [Draft: WIP - enable browse everything](https://gitlab.com/notch8/utk-hyku/-/merge_requests/31)

**Comment by DiemBTran** [comment]
Shana June 2022

---

I'm having issues getting hyku proper (main) to spin up. I've tried its other branches as well. Putting this back for now to focus energy on other tasks.

**Comment by DiemBTran** [comment]
Shana June 2022

---

I made a [PR](https://github.com/samvera/hyku/pull/1807/files) against hyku. I am still trying to work through getting hyku spun up in order to test it locally. 

Rob's upgrade should pull in these changes. Don't QA in staging until #2 is complete:

**Comment by DiemBTran** [comment]
Shana June 2022

---


blocked because I'm still unable to get nnp_catchup running locally. Will take a break and try again later. I've coded a solution but wanted to test it locally to see if it works, before moving this ticket forward.

**Comment by DiemBTran** [comment]
Shana June 2022

---

I was finally able to test my wip implementation and it requires re-work. 

To whoever picks this up, feel free to start with your own approach.

**Comment by DiemBTran** [comment]
Shana June 2022

---

After working on the feature flipper and sharing concerns with Rob, he agreed that it’s best to put it down for now. Additionally, we most likely won’t merge the code that’s responsible for putting PDFs into UVs at this time, so it’ll still be the default behavior to not do that (which is what UTK wants).

**Comment by DiemBTran** [comment]
Shana June 2022

---

After working on the feature flipper and sharing concerns with Rob, he agreed that it’s best to put it down for now. Additionally, we most likely won’t merge the code that’s responsible for putting PDFs into UVs at this time, so it’ll still be the default behavior to not do that (which is what UTK wants).
