### ISSUE TITLE
🎁 Implement title sort if needed. This is currently not a supported feature.

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#420]
# Summary 
related to
- #408 
- #392

![Screenshot 2023-06-07 at 11 39 05 AM](https://github.com/scientist-softserv/utk-hyku/assets/17851674/de210b13-6017-4101-ad5d-b119368864c5)

# Acceptance Criteria:
- [ ] Sorting by title is an available option

# Testing Instructions
- [ ] Set the sort to `title`
  - [ ] Verify the works titles are sorted alphabetically (A-Z) then (a-z)

# Notes
- note the default Title sort is (A-Z) then (a-z)

**Comment by kirkkwang** [comment]
this may be relevant

https://gitlab.com/notch8/louisville-hyku/-/merge_requests?scope=all&state=merged&author_username=kirkkwang&search=title

**Comment by jillpe** [comment]
**QA is blocked until reindex works**
- #465 

The sort relies on works getting indexed properly. Kirk ran a reindex but it looks like some of the works didn’t get reindexed. The problem doesn’t seem to be with the code, the problem is with getting the reindex going it seems. What we don’t know is if this is a staging issue or not.

**Comment by jillpe** [comment]
No longer blocked - bad data was making works appear like they weren't getting reindexed. This ticket is okay to QA.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- ascending: https://qa.utk-hyku-staging.notch8.cloud/catalog?locale=en&page=65&search_field=all_fields&sort=title_ssi+asc
- descending: https://qa.utk-hyku-staging.notch8.cloud/catalog?locale=en&page=1&search_field=all_fields&sort=title_ssi+desc

<details><summary>Title sort ascending sorts (A-Z) then (a-z), while descending sorts (z-a) (Z-A)</summary>

![screencapture-qa-utk-hyku-staging-notch8-cloud-catalog-2023-07-17-11_34_45 (1)](https://github.com/scientist-softserv/utk-hyku/assets/29311858/ae483ff7-9609-43b8-903f-ae87a5ef729c)
![screencapture-qa-utk-hyku-staging-notch8-cloud-catalog-2023-07-17-11_38_20](https://github.com/scientist-softserv/utk-hyku/assets/29311858/2e7f657f-c97d-4818-a3af-f36e0390c6ea)

</details>

**Comment by markpbaggett** [comment]
Looks good.  Bumping.
