### ISSUE TITLE
🐛 IIIF manifest fails to load for parent work: undefined method sort_iiif_manifest_canvases_by

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#421]
# Summary
![Screenshot 2023-06-07 at 12 43 07 PM](https://github.com/scientist-softserv/utk-hyku/assets/17851674/d769fb7e-e1eb-499a-8ff4-c6a91f645d85)

Child work is correct.

# Acceptance Criteria
- [ ] Parent work IIIF manifest is accessible and viewable

# Testing Instructions
- [ ] Go to a work that should render a UV.
- [ ] Observe that the UV displays something instead of erroring out

**Comment by jillpe** [comment]
related to 
- #422 

Try to update iiif_print first. It may help resolve both tickets (warning: latest version includes derivative rodeo - need to figure out which sha will work)

**Comment by jillpe** [comment]
Blocked by #433

**Comment by jillpe** [comment]
SoftServ QA: Pass!

[Work](https://dc.utk-hyku-staging.notch8.cloud/concern/pdfs/d9227081-b413-4e01-8264-e8c4ada3610a?locale=en)

**Comment by markpbaggett** [comment]
@jillpe Looks good! Bumping forward one lane.

**Comment by markpbaggett** [comment]
This looks good on production too: https://dc.utk-hyku-production.notch8.cloud/concern/images/b7f3cc56-c65e-4559-adad-b035b918aa2a/manifest
