### ISSUE TITLE
🐛 Derivatives do not appear to be running upon import

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#422]
# Summary
- Imported a generic work with a PDF to split. PDF was split, but no derivative files were created... no text was indexed and no thumbnails were generated.
- Imported an image... no thumbnail was generated.
![Screenshot 2023-06-07 at 1 01 57 PM](https://github.com/scientist-softserv/utk-hyku/assets/17851674/8b122d22-f2b8-477e-868a-6b51f9145d4f)

# Acceptance Criteria
- [ ] Derivatives files are created upon import for all work types with PDFs

# Testing Instructions
- [ ] Import this CSV [colloquy_with_attachments_small.csv](https://github.com/scientist-softserv/utk-hyku/files/11819413/colloquy_with_attachments_small.csv)
- [ ] Observe that the pages of the PDF displays in the UV

**Comment by jillpe** [comment]
Blocked by #433

**Comment by jillpe** [comment]
SoftServ QA: Pass!

CSV: 
[colloquy_with_attachments_small.csv](https://github.com/scientist-softserv/utk-hyku/files/11821709/colloquy_with_attachments_small.csv)

[Importer](https://dc.utk-hyku-staging.notch8.cloud/importers/132?locale=en)

[PDF split and appears in the viewer](https://dc.utk-hyku-staging.notch8.cloud/concern/pdfs/d9227081-b413-4e01-8264-e8c4ada3610a?locale=en)
- parent and child works display on the show page and are accessible
- parent and child works display in the UV

**Comment by josh-morgan117** [comment]
Can this be done with a PDF submitted through the GUI form? Or limited to setting RDF types in bulkrax sheet?

**Comment by laritakr** [comment]
> Can this be done with a PDF submitted through the GUI form? Or limited to setting RDF types in bulkrax sheet?

I assume you are talking about the PDF splitting? You should be able to upload a PDF through the form and have it split, if it is uploaded to the right work types and with the right structure. If not, something is wrong.

When you want to split a PDF, you upload it as a fileset directly on a parent work, rather than adding it to an Attachment work type as a child of the parent work. And it is only supported for work types PDF and GenericWork. If you don't want the PDF to split, you attach it to an Attachment work type. Attaching the child works to the parent job is submitted with a 10 minute delay so it can take a while for everything to appear complete.

**Comment by markpbaggett** [comment]
@laritakr I think what Josh is asking is about the PDF splitting.  The one problem I see is that splitting for us (to my understanding) is based off both the work type and the class of the file set.  For instance, in PDFs, only the `pcdmuse:IntermediateFile` fileset should be split because they also have a different preservation file that is also PDF.  I think one thing we could use as a work around here is just doing a Bulkrax update import using the ids of the intermediate files to make them intermediate files.  Then, splitting might be triggered? 🤔

**Comment by laritakr** [comment]
@markpbaggett Splitting is triggered ~~solely~~ by the PDF being attached as a fileset onto a GenericWork or PDF work type, rather than an Attachment child work and the rdf file type. 
Derivatives on the PDF, I believe, are triggered based on the rdf file type. 

(Unless @kirkkwang made more changes that I am not aware of, this was my understanding of how it works. But maybe intermediateFile is also part of the first part... i.e. it being attached directly to the parent work)

UPDATE: It appears I may be wrong... I'm not seeing UI uploads are doing PDF splitting. Kirk is out so I will have to look into this or wait for him to return. It appears that it DOES require the rdf file type but I'm not sure what is missing to work in the UI, so we will need to look at that a bit more if you need to be able to upload and split.

**Comment by laritakr** [comment]
Additionally PDF splitting works only on an initial import - either a new work, or adding a PDF to an existing work. We have not yet found a way to determine how & when to split on a reimport/replacement of a file.

**Comment by ShanaLMoore** [comment]
I believe we should pull this ticket back or spin off a new bug ticket. [Manually creating a work with a PDF fileset doesn't appear to be splitting the PDFs](https://dc.utk-hyku-staging.notch8.cloud/concern/pdfs/4149aac0-fd37-4033-b2b9-1b231b91a80c?locale=en), and that should happen regardless of the rdf_type settings. rdf_type should only be used to determine the derivative creation, at least until the derivative rodeo work is in place. I'm almost certain that this used to work so I'm a bit puzzled for why it doesn't now 🤔 but I haven't dug in yet.

**Comment by ShanaLMoore** [comment]
TODO: Update no rodeo ✅  and retest

**Comment by laritakr** [comment]
> TODO: Update no rodeo and retest

Done. :)

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested on:
- csv: 
[colloquy_with_attachments_small.csv](https://github.com/scientist-softserv/utk-hyku/files/11961095/colloquy_with_attachments_small.csv)
- importer: https://qa.utk-hyku-staging.notch8.cloud/importers/39?locale=en
- work show page with UV: https://qa.utk-hyku-staging.notch8.cloud/concern/pdfs/838d95a8-5485-492d-9ce3-0f0bf3066ec2?locale=en

<details><summary>Pages of this work display in the UV</summary>

https://github.com/scientist-softserv/utk-hyku/assets/29311858/ae84c3ad-051e-4bd9-834b-59723fdbcf16
</details>

**Comment by josh-morgan117** [comment]
Appears to be working for me.
