### ISSUE TITLE
🎁 Implement grouped facets

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#426]
# Summary
related to
- #408 
- #392

Issue https://github.com/scientist-softserv/utk-hyku/issues/402 detailed options for implementing group facets. 

Once the decision is made on which method is chosen, the basic tasks will be:

1. Get the list of fields to facet together (based on metadata profile term `indexing_documentation` including `creator facet`)
2. Define new grouped facet field as facetable
3. Map all creator-type fields into grouped facet field in `generate_solr_document`
4.  config.add_facet_field into catalog_controller 
5. Reindex works

Issue https://github.com/scientist-softserv/utk-hyku/issues/104 should be kept in mind, as the creator terms being grouped affect that ticket as well.

# Acceptance Criteria
- [ ] Grouped facets are functional

**Comment by jillpe** [comment]
confirmed 2022-07-13, moving to Milestone 4 to use the AllinsonFlex option

**Comment by laritakr** [comment]
Facets to group per metadata profile:
- all types of creators into a creator facet
- rights_statement and license into a rights facet
- both language terms into a language facet
- keyword and subject into a subject facet
