### ISSUE TITLE
✅ Verify ocr search iiif_print is working

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#427]
ref
- #409 
- #391 

Requires:
- https://github.com/scientist-softserv/utk-hyku/issues/422
- https://github.com/scientist-softserv/utk-hyku/issues/423

# Accepted Criteria
- [ ] Verify ocr search iiif_print is working or not
  - [ ] If working, close this ticket
  - [ ] If NOT working, create a follow up ticket and close this ticket

**Comment by jillpe** [comment]
closed - covered in #358
