### ISSUE TITLE
🎁 Configure OAI-PMH

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#431]
# Summary
Refs:
- #21
- #405

Supports including metadata elements such as thesis advisor and committee members in separate fields in the search index and outgoing OAI-PMH feed

Endpoint data will be configured as part of development. We will need to map for DC and MODS, but depending on the amount of work, MODS can be split off as a separate ticket and completed at a separate time. May require additional work in AllinsonFlex to complete.

This was done in Jio and Adventist - see details in #405 

# Acceptance Criteria

- [x] As a user I can access an OAI feed with prefix oai_dc that shows me all public metadata that has dc mappings
    - [x] As a user I can access an OAI feed with prefix oai_mods that shows me all public metadata that has mods mappings OR 
    - [ ] oai_mods ticket is created.

# Testing

Navigate to `{tenant url}/catalog/oai?verb=Identify` for a repository tenant. You can use the resulting view to navigate the various OAI options. 

<img width="446" alt="Screenshot 2023-07-26 at 5 27 50 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/17851674/9270836f-7a96-4e00-9eac-5b9d9dcd2857">

- select `ListRecords` to see a list of records in oai_dc format
- select the `oai_dc` option to see a particular record in oai_dc format
- in the url, change to `metadataPrefix=mods` to see the same list in mods. alternately, you can click on formats and then select `mods` from the next screen.
- Only terms from the lists below will appear in the feed. If there are multiple values of a term, they should all appear. 

- [ ] The following terms should appear in oai_dc mappings when they exist in the work: 

**creator:** creator, architect, artist, author, composer, illustrator, interviewee, photographer, utk_artist, utk_author, utk_creator, utk_interviewee, utk_photographer
**date:** date_created_d, date_issued_d,
**description:** abstract
**format:** form, form_local, extent
**identifier:** identifier, local_identifier, issn, isbn
**language:** language
**publisher:** provider, intermediate_provider,
**rights:** rights_statement, license
**subject:** subject, keyword
**title:** title
**type:** resource_type

- [ ] The following terms should appear in mods mappings when they exist in the work:

**name.namePart (role.roleTerm=creator):** creator, architect, artist, author, composer, illustrator, interviewee, photographer, utk_artist, utk_author, utk_creator, utk_interviewee, utk_photographer
**typeOfResource:** 'resource_type_tesim'
**identifier (type):** identifier, local_identifier, issn, isbn
**originInfo (dateCreated, dateIssued):** date_created_d, date_issued_d
**language.languageTerm:** language
**physicalDescription (form, extent):** form, form_local, extent
**abstract:** abstract
**subject (topic, cartographics.coordinates):** subject, keyword, coordinates
**location.physicalLocation:** provider, intermediate_provider
**accessCondition:** rights_statement, license
**title:** title, alternative_title
 

# Notes
oai_dc terms to map:  `:contributor, :coverage, :creator, :date, :description, :format, :identifier, :language, :publisher, :relation, :rights, :source, :subject, :title, :type`

**Comment by jillpe** [comment]
Pairing time with Rob and LaRita

**Comment by jillpe** [comment]
SoftServ QA: PASS!

[Record Tested](https://dc.utk-hyku-staging.notch8.cloud/catalog/oai?verb=ListMetadataFormats&identifier=oai:hyku:431a8da4-f6e3-4e08-911e-336c71ead1c4)

[dc url tested](https://dc.utk-hyku-staging.notch8.cloud/catalog/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:hyku:431a8da4-f6e3-4e08-911e-336c71ead1c4)
- [x] The following terms should appear in oai_dc mappings when they exist in the work:

- creator: creator, architect, artist, author, composer, illustrator, interviewee, photographer, utk_artist, utk_author, utk_creator, utk_interviewee, utk_photographer
- date: date_created_d, date_issued_d,
- description: abstract
- format: form, form_local, extent
- identifier: identifier, local_identifier, issn, isbn
- language: language
- publisher: provider, intermediate_provider,
- rights: rights_statement, license
- subject: subject, keyword
- title: title
- type: resource_type


[mods url tested](https://dc.utk-hyku-staging.notch8.cloud/catalog/oai?verb=GetRecord&metadataPrefix=mods&identifier=oai:hyku:431a8da4-f6e3-4e08-911e-336c71ead1c4)
- [x] The following terms should appear in mods mappings when they exist in the work:
- name.namePart (role.roleTerm=creator): creator, architect, artist, author, composer, illustrator, interviewee, photographer, utk_artist, utk_author, utk_creator, utk_interviewee, utk_photographer
- typeOfResource: 'resource_type_tesim'
- identifier (type): identifier, local_identifier, issn, isbn
- originInfo (dateCreated, dateIssued): date_created_d, date_issued_d
- language.languageTerm: language
- physicalDescription (form, extent): form, form_local, extent
- abstract: abstract
- subject (topic, cartographics.coordinates): subject, keyword, coordinates
- location.physicalLocation: provider, intermediate_provider
- accessCondition: rights_statement, license
- title: title, alternative_title

**Comment by markpbaggett** [comment]
Hey all, I have a question about this one.  In Hyku, can OAI Sets only be affiliated with admin sets?  We see oai set as more closely related to collection than admin set in that we often have the need to capture metadata from a single collection rather than a single workflow.

If this is a ton of work, I think we could probably make due for now and revisit this on our own in the future.

**Comment by laritakr** [comment]
> Hey all, I have a question about this one. In Hyku, can OAI Sets only be affiliated with admin sets? We see oai set as more closely related to collection than admin set in that we often have the need to capture metadata from a single collection rather than a single workflow.

Basically any faceted field can easily become an oai set. Other sets would require more work. I know I played around with collection, model, and language and it worked as expected.

I apologize, I thought I had asked earlier about what you wanted as sets when I did the ticket but maybe that didn't get follow-up on as it should have. If you know what you need in collections, please bring it up and there's a good chance it may be a very simple change.

**Comment by markpbaggett** [comment]
@laritakr I've created [this issue](https://github.com/scientist-softserv/utk-hyku/issues/535) about sets and will bump this one along.

**Comment by markpbaggett** [comment]
@jillpe bumping this to done
