### ISSUE TITLE
🦄 Spike: Investigate why database migrations didn't happen in utk prod deploy

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#434]
# Summary
When we deploy, migrations should run automatically. 

todo: look to see if there is a sidekiq command too

**Effects of this on UTK**
- [Slack Thread](https://assaydepot.slack.com/archives/C0396LSM06P/p1686847835627609)

- Examples of importers that failed
  - https://dc.utk-hyku-production.notch8.cloud/importers/271?locale=en
  - https://dc.utk-hyku-production.notch8.cloud/importers/270?locale=en

- CSV's of those importers
  - [wpa_tva_open_delete.csv](https://github.com/scientist-softserv/utk-hyku/files/11762253/wpa_tva_open_delete.csv)
  - [wpa_tva_open_all_failures.csv](https://github.com/scientist-softserv/utk-hyku/files/11762256/wpa_tva_open_all_failures.csv)

# Accepted Criteria
- [ ] Problem is identified for why migrations did not happen in the prod deploy
- [ ] Follow up tickets are created

**Comment by ShanaLMoore** [comment]
verify db:migrate is part of the github workflow.

**Comment by ShanaLMoore** [comment]
migrations didn't run for BL too, per: https://assaydepot.slack.com/archives/C0313NK5NMA/p1685025478813299

**Comment by ShanaLMoore** [comment]
Q posted in slack: https://assaydepot.slack.com/archives/C0313NK4SMS/p1688582963061429



![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/55596a2a-bb22-4e7e-845a-107c1641c0c9)
