### ISSUE TITLE
Reimporting Failed Filesets Fail with 

### ISSUE THREAD

**Issue by markpbaggett** [notch8/utk-hyku#436]
# Story

Historically, when migrating works, attachments, and file sets into our Hyku instance, approximately 10-20% of our file set imports fail.  This goes back to very first imports in November and December of 2022. In order to fix these failures, we initially reran the importer with "replace files and metadata" selected but this caused the full importer including successful imports to rerun. While we'd often see a reduction in failed file sets we'd also see examples where a known failed import would say "Completed," but when you navigated to the file set and tried to download it it wouldn't be there and would give a Rails error instead.

In order to make failed file set reimports occur as quickly as possible, we came up with our own work around.  We realized if you created a list of just the failed imports and created an import job from the list where you deleted the failed file sets and ran the job twice, you could then reimport just those filesets and everything  would go in (except for 10 - 20% of the failures). We used this method for migration for everything up until our latest batches of things in May.  Now, this method no longer works and results in a `NoMethodError` like `NoMethodError - undefined method 'work?' for nil:NilClass`.

You can see this here:

https://dc.utk-hyku-production.notch8.cloud/importers/271?locale=en

And with these two CSVs:

- [wpa_tva_open_all_failures_without_open_4273_obj.csv](https://github.com/scientist-softserv/utk-hyku/files/11818258/wpa_tva_open_all_failures_without_open_4273_obj.csv)
- [wpa_tva_open_delete.csv](https://github.com/scientist-softserv/utk-hyku/files/11818259/wpa_tva_open_delete.csv)

Right now, imports / migration is blocked because we aren't sure how to properly import failed works and file sets. We're open to anything at this point, but we want to have something good in place before we start migrating books since we will be dealing with so many extra files per work. Before we even dealt with failed file set imports related to this batch of things, the collection above took several days just to migrate ~6000 images that were small JPEGs because we've been splitting file set imports into batches of ~400 to try and reduce failures based on past advice. It's entirely possible that our original idea for fixing failed file sets was a bad one, and we should have been doing this differently from the beginning. 

# Acceptance Criteria

- UTK understands how to properly and efficiently reimport works, filesets, and attachments that "failed".
- The method selected does not result in "failures" saying "completed" but are actually still "failed".
- Preferably (hopefully), the reimport method does not require reimporting the works, attachments, and filesets that initially succeeded to save on machine time.
- Ideally, it'd be nice to define a maximum import size per job.

# Testing Instructions and Sample Files

- [wpa_tva_open_all_failures_without_open_4273_obj.csv](https://github.com/scientist-softserv/utk-hyku/files/11818258/wpa_tva_open_all_failures_without_open_4273_obj.csv)
- [wpa_tva_open_delete.csv](https://github.com/scientist-softserv/utk-hyku/files/11818259/wpa_tva_open_delete.csv)

# Notes

**Comment by jillpe** [comment]
ref. https://assaydepot.slack.com/archives/C0396LSM06P/p1688754446389199?thread_ts=1688745662.956879&cid=C0396LSM06P
