### ISSUE TITLE
🐛 Parent work in-viewer ocr doesn't work

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#439]
# Summary
Currently in-viewer OCR only works on child works accessed via their link on the show page. It is not working on the parent work, even after a reindex.

[Example](https://dc.utk-hyku-staging.notch8.cloud/concern/pdfs/d9227081-b413-4e01-8264-e8c4ada3610a?locale=en)

# Accepted Criteria
- [ ] OCR search works on a parent work in the viewer

# Testing Instructions
- as an admin, be sure that `Ssl configured` is checked on in `/admin/account/edit?locale=en`
- Access a parent work in the UV
- Search a term that should be found in the parent work
  - [ ] Term is found and highlighted

**Comment by jillpe** [comment]
SoftServ QA: Pass!

[Example URL](https://dc.utk-hyku-staging.notch8.cloud/concern/pdfs/d9227081-b413-4e01-8264-e8c4ada3610a?locale=en)

Searched the term 'Early' in parent UV and it found and highlighted the word

![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/8e496d6a-1342-4540-a738-b5792f00a1ca)

**Comment by josh-morgan117** [comment]
Searching for "mountains" or photographers" doesn't return any results. It will find "mountain" and "photographer", though not any mention of them on the first page.

**Comment by jillpe** [comment]
Pull in iiif print fixes and retest after merging

**Comment by jillpe** [comment]
Blocked by https://github.com/scientist-softserv/utk-hyku/pull/449

**Comment by ShanaLMoore** [comment]
confirmed that pulling in no-rodeo w a manual pdf import fixes this issue. The words have to be exact matches ie: photograph**s** vs photograh: 



![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/09ca3388-2b3b-4cb2-910e-9bc85dd63949)



![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/95bb4536-3bad-4ed1-bfb6-8917eb7106c7)



### EDIT: Bulkrax appears to be working as well:



![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/d144623b-39fa-4315-a849-81cb8a5529a6)

[Uploading colloquy_with_attachments_small (1).csv…]()

**Comment by ShanaLMoore** [comment]
TODO: Update no rodeo ✅ and retest 





![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/9c08215e-d0a9-427c-908c-9732a2217607)



![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/b5ad56b8-6482-4a14-b084-21a189c669a3)

**Comment by laritakr** [comment]
> TODO: Update no rodeo and retest

Done :)

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot

tested on:
- csv: 
[colloquy_with_attachments_small.csv](https://github.com/scientist-softserv/utk-hyku/files/11961095/colloquy_with_attachments_small.csv)
- importer: https://qa.utk-hyku-staging.notch8.cloud/importers/39?locale=en
- work show page with UV: https://qa.utk-hyku-staging.notch8.cloud/concern/pdfs/838d95a8-5485-492d-9ce3-0f0bf3066ec2?locale=en

<details><summary>OCR search in UV is working</summary>

![Pdf Great Smoky Mountains Colloquy Volume 2, Number 1 ID 838d95a8-5485-492d-9ce3-0f0bf3066ec2 Hyku 2023-07-05 at 4 30 32 PM](https://github.com/scientist-softserv/utk-hyku/assets/29311858/087dea54-fc29-4014-8caf-1a921737a772)
</details>

**Comment by josh-morgan117** [comment]
If I search 'mountains' now, it returns 26 results, but if I search 'mountain', it only returns 3.

**Comment by laritakr** [comment]
> The words have to be exact matches ie: photograph**s** vs photograh:

[As Shana noted above](https://github.com/scientist-softserv/utk-hyku/issues/439#issuecomment-1613580698) the words have to be exact matches.

**Comment by josh-morgan117** [comment]
Is it possible to have 'stemming' instead of 'whole words only' for OCR and search in general? Researchers in particular need that flexibility.

**Comment by laritakr** [comment]
> Is it possible to have 'stemming' instead of 'whole words only' for OCR and search in general? Researchers in particular need that flexibility.

I'm not sure what that would take. @jillpe this may need to be a spike ticket re: searching

**Comment by markpbaggett** [comment]
@jillpe while i think stemming is a question still, i think the rest of this is good to go.  going to bump into next lane.

**Comment by josh-morgan117** [comment]
Will need to wait for a PDF import model to be created for prod before we can test this one.

**Comment by ShanaLMoore** [comment]
@kidon0011 what do you mean? 

Here are all of the available work types for prod. PDF is availble.

![image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/13d7dd70-06ff-4e84-88dd-657f51a28ef4)

Moreover, if you can't see the UV of a child work, you can manually edit that work, select OBJ for rendering and save. 

I have a rake task to automatically update all of prod data but am waiting on Mark for the thumbs up to run it.

**Comment by jillpe** [comment]
Verification on production blocked until #358 resolved
