### ISSUE TITLE
UTK emails not sending

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#441]
# Summary

A dev has to manually create an account and password for clients to access UTK production. When an admin creates a user, it should send that user an email to set up their own password.

# Acceptance Criteria

- [ ] A user should be able to create their own users and passwords. 
- [ ] A user should be able to reset their own passwords. 

# Testing Instructions

IN PRODUCTION
Login as an admin.
Go to manage users. Add a user using an email address you can personally access. 
Verify that an email is received. 
Verify that you can sign up and set a password. 
Verify that you can reset your password. 

# Screenshot 

A flash message will say an email got sent. In staging it sends it to mail trap. In prod, no emails are received. 

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/97b5f60c-4521-40a1-a2d5-e39ed4da8aac)

**Comment by jillpe** [comment]
@aprilrieger Do you know what is required for us to set up the mailer?
