### ISSUE TITLE
UTK: verify graph indexer is correct

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#448]
Is UTK using graph indexer?? If so ...

# Summary 

We were unable to delete 20 collections during the SDAPI ingest.  It is because Adventist is not using hyrax-v2_graph_indexer, and large collections were failing due to the nested indexing.

Pull in this [commit](https://github.com/scientist-softserv/adventist-dl/pull/448/commits/3f0ccc80ce700d49283eaa7f32a9901ca61d4e48) into main for the fix.

# Acceptance Criteria

- [ ] The gemfile lock contains the above commit

# Screenshots or Video

# Testing Instructions
- Go into the server and verify the following method is coming from the graph indexer
  - Collection.first.method(:before_update_nested_collection_relationship_indices)
  
# Notes

**Comment by ShanaLMoore** [comment]
blocked until graph indexer release. we don't want to reference a branch of the graph indexer branch.

**Comment by jillpe** [comment]
Verify if they are using it. If they are not, create a ticket to have them use this

**Comment by orangewolf** [comment]
utk is on hyrax 3.x and therefor uses graph indexer when HYRAX_USE_SOLR_GRAPH_NESTING is set to true. confirmed it is set to true on the deployed and local versions.
