### ISSUE TITLE
WARC support/display

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#45]
# Summary
Supports WARCs: web archives (archive-it.org)

Binary worktype or generic worktype. Users can download and pass to a warc generator

# Acceptance Criteria

- [ ] Binary or Generic worktype
- [ ] users can download and pass to a warc generator

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
no longer in scope 2023-04-19
