### ISSUE TITLE
🐛 Revert to main branch of IiifPrint

### ISSUE THREAD

**Issue by laritakr** [notch8/utk-hyku#454]
# Story

Revert to use IiifPrint main branch.

**Background:** Derivative Rodeo refactoring of IiifPrint broke PDF splitting. Branch `no_rodeo` was swapped as a temporary fix. Two pull requests to IiifPrint fixed PDF splitting and brought in subsequent patches as well.

- https://github.com/scientist-softserv/iiif_print/pull/256
- https://github.com/scientist-softserv/iiif_print/pull/257

# Acceptance Criteria

- [x] IiifPrint is updated to use `main` branch
- [x] PDF splitting performs appropriately

# Screenshots / Video

<details>
<summary></summary>

![Screenshot 2023-07-06 at 3 12 08 PM](https://github.com/scientist-softserv/utk-hyku/assets/17851674/8ba7cbf5-bdd7-4935-83eb-d37629faea62)
![Screenshot 2023-07-06 at 3 12 31 PM](https://github.com/scientist-softserv/utk-hyku/assets/17851674/69196a9e-1f43-4133-a80a-9ae82674ab53)

</details>

# Testing Instructions and Sample Files

Create a new PDF work using file 
[iiif-print-test.pdf](https://github.com/scientist-softserv/utk-hyku/files/11970916/iiif-print-test.pdf)

Verify that the job completes normally and PDF is split into pages and viewable.

# Notes
Move ticket to complete following SoftServe QA.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- [iiif-print-test.pdf](https://github.com/scientist-softserv/utk-hyku/files/11997382/iiif-print-test.pdf)
- https://qa.utk-hyku-staging.notch8.cloud/concern/generic_works/94f5d7e5-90d1-44e4-925c-9fc075c6e934?locale=en

<details><summary>PDF splits and is viewable</summary>

![Generic Work 2023-07-09 Revert to main branch of IiifPrint #454 ID 94f5d7e5-90d1-44e4-925c-9fc075c6e934 Hyku 2023-07-09 at 7 54 22 PM](https://github.com/scientist-softserv/utk-hyku/assets/29311858/445fd186-1a5a-47cb-aa4d-88f1b06366e3)
</details>
