### ISSUE TITLE
Canteloupe to serve images via IIIF

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#46]
# Summary
Integrates with a IIIF Image server like Cantaloupe other other service to provide images following the IIIF Image API specification

# Acceptance Criteria

- [ ] Canteloupe serves images

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
no longer in scope 2023-04-19
