### ISSUE TITLE
🦄 Spike: Reindex

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#465]
# Summary
#420 relies on works getting indexed properly. Kirk ran a reindex but it looks like some of the works didn’t get reindexed. The problem doesn’t seem to be with the code, the problem is with getting the reindex going it seems. What we don’t know is if this is a staging issue or not.

# Accepted Criteria
- [ ] Verify if this is a ~~staging~~ production issue or not
- [ ] Verify if works do not get reindexed
  - [ ] If they do not get reindexed, verify why
- [ ] Make follow up tickets if necessary

**Comment by jillpe** [comment]
For staging, it is confirmed that this was just bad data. This happened in the [past](https://assaydepot.slack.com/archives/C0396LSM06P/p1668706166745629). 

Keeping this ticket open to confirm if this is an issue on prod

**Comment by ShanaLMoore** [comment]
The issue was from bad/old metadata properties that no longer exist on the current profile.

**Comment by ShanaLMoore** [comment]
cc @kirkkwang Can we close this ticket?

**Comment by kirkkwang** [comment]
@ShanaLMoore 
I'd be fine with closing it, if we run into a problem in production we can open this back up or make a new one
