### ISSUE TITLE
Bring back the Edit button

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#468]
# Summary

ref convo: https://assaydepot.slack.com/archives/C031E2P1RJM/p1689287526413699

We noticed that the show page was missing convenient functionality, such as the edit button. This was intentionally removed ([commented out](https://github.com/scientist-softserv/utk-hyku/blob/main/app/views/themes/dc_show/hyrax/base/show.html.erb#L14-L15)) as part of the theming work. 

Mark confirmed that we should add it back. 

**Note: I believe Amanda removed the feature work option so we may want to confirm if she did and still hide that button if that's true.** 

# Acceptance Criteria

- [ ] The show page should have action buttons, ref default hyku: 

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/3376769b-ec2d-4721-95c0-0b1ae81c0bee)

# Screenshots or Video

Staging: buttons are missing 

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/b69d8f0c-20c7-4f93-b30b-9ce0227518ec)

# Testing Instructions
1. Visit a work's show page
2. Confirm the missing buttons have been added back 
- [ ] edit
- [ ] delete
- [ ] attach child
- [ ] add to collection
- [ ] feature

**Comment by ShanaLMoore** [comment]
I believe Amanda disabled the featured work feature in UTK, even though you can set it in the admin dashboard's feature flag section. If you toggle it off it does not hide the button. 

I toggled it to true, tried to [set a featured work](https://dc.utk-hyku-staging.notch8.cloud/concern/videos/febc6b41-d998-47ab-9732-ac09fd8168f2?locale=en) and it does not display in the home page. Perhaps we should make a follow up ticket to hide just that button and/or remove the feature flag ability. 

 

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/19bc7a12-a424-429b-9c13-349cf3bf4a68)



![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/905a21ee-5635-4980-a5c5-9d8e399ead27)




![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/600cba4b-a1b3-4b2c-8f9f-352da61cfd98)

**Comment by kirkkwang** [comment]
That sounds good, if the button doesn't work/isn't meant to work, then I think it shouldn't be there.

**Comment by ShanaLMoore** [comment]
default hyku: 

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/f0cb9638-e4c6-4a00-82a4-cbc527a3ef65)

**Comment by ShanaLMoore** [comment]
just adding notes. It was removed in[ this PR. ](https://github.com/scientist-softserv/utk-hyku/pull/268/files) so QAing this ticket shouldn't check that it works.

**Comment by jillpe** [comment]
SoftServ QA: Pass!

[Audio Work Show Page URL](https://dc.utk-hyku-staging.notch8.cloud/concern/audios/5d20893c-ef7f-44ca-a0e1-0184ea430e00)
   - [x] edit
   - [x] delete
   - [x] attach child
   - [x] add to collection
   - [x] feature

[Generic Work Show Page URL](https://dc.utk-hyku-staging.notch8.cloud/concern/generic_works/256bf94b-e2c7-4890-a6f1-4a2542e37276)
   - [x] edit
   - [x] delete
   - [x] attach child
   - [x] add to collection
   - [x] feature

<details><summary>Screenshots</summary>


![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/150dfe4d-8fd8-4758-afd1-3e87fad6f19e)




![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/9a5866b7-8587-4bcb-b0aa-0028fcf30ce7)


</details>
