### ISSUE TITLE
:bug: Feature Button

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#472]
# Summary

In ticket #468 we brought back the show actions which includes a feature button. However, currently the feature button does nothing for dc tenants. 

Amanda [disabled](https://github.com/scientist-softserv/utk-hyku/pull/268/files) the featured work feature in UTK, even though you can set it in the admin dashboard's feature flag section. If you toggle it off it does not hide the button. 

I toggled it to true, tried to [set a featured work](https://dc.utk-hyku-staging.notch8.cloud/concern/videos/febc6b41-d998-47ab-9732-ac09fd8168f2?locale=en) and it does not display in the home page. Perhaps we should make a follow up ticket to hide just that button and/or remove the feature flag ability. 

 
# Screenshots or Video
<details><summary></summary>

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/19bc7a12-a424-429b-9c13-349cf3bf4a68)

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/905a21ee-5635-4980-a5c5-9d8e399ead27)

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/600cba4b-a1b3-4b2c-8f9f-352da61cfd98)

</details>

# Acceptance Criteria

- [ ] Would it be possible to hide the [feature flipper](https://github.com/voormedia/flipflop/blob/master/app/views/flipflop/features/index.html.erb) just for the dc tenant? 
  - ask client if any tenants need this feature? if not we can just remove show_featured_works from [config/features.rb](https://github.com/scientist-softserv/utk-hyku/blob/main/config/features.rb#L12)
    - for now it may be ok to just comment it out and hide the feature button

- [ ] Hide/remove the feature button just for the dc tenant

# Testing Instructions

- [x] In 2 different windows, sign in as an admin into 2 different tenants:
  - DC
  - a tenant that isn't DC
- [x] If tenant is DC the show featured work option is not available in the features admin dashboard page. 
- [x] Else, all other tenants should have the ability to see and set it

- [x] If tenant is DC, the work show page should not have a feature button
- [x] Else, all other tenants should have the ability to set a featured work

Tested works must be public of the feature button will not be visible

QA tenant: 

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/a55fa446-f01f-48f6-b455-c3ddd59d1114)

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/2cd0e74d-138a-485d-b219-d1b12de19995)

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/cb2a3160-b2b1-48cb-b976-e394b5d5e5fc)

DC tenant 

Should not have a feature button on the show page
Should not have featured works in its home page (previously removed in a separate ticket - this ticket is cleanup)
Should not have featured works available in its features dashboard as an admin user

# Notes

**Comment by ShanaLMoore** [comment]
default hyku: 

![image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/00306171-f1c9-4f42-9d7b-e520bfe9d2f4)

**Comment by DiemBTran** [comment]
**Needs further review:** 

tested on:
- DC tenant:
  - features page: https://dc.utk-hyku-staging.notch8.cloud/admin/features?locale=en
  - work show page: https://dc.utk-hyku-staging.notch8.cloud/concern/generic_works/256bf94b-e2c7-4890-a6f1-4a2542e37276?locale=en
- non-DC tenant:
  - features page: https://qa.utk-hyku-staging.notch8.cloud/admin/features?locale=en
  - work show page: https://qa.utk-hyku-staging.notch8.cloud/concern/generic_works/0908b0fc-7462-455d-a33e-297f61df2599?locale=en

# testing instructions
- [x] DC feature flippers do not have featured works option
- [x] non-DC feature flippers have featured works option 
- [ ] DC work show page does not have Feature button
- [ ] non-DC work show page has Feature button
  - the logic for the work show pages may have been flipped. the DC work show page has the Feature button, while the other one doesn't

<details><summary>Features page is correct. Work show pages are not.</summary>

![Index Feature Digital Collections 2023-07-26 at 9 06 20 AM](https://github.com/scientist-softserv/utk-hyku/assets/29311858/a61c192b-d738-4aca-90dd-a0a8c041b6aa)
![Index Feature Hyku 2023-07-26 at 9 06 10 AM](https://github.com/scientist-softserv/utk-hyku/assets/29311858/6b4db34c-9ba1-4fb0-93e5-55449a9cb6fb)
![Generic Work #423 QA ID 256bf94b-e2c7-4890-a6f1-4a2542e37276 Hyku 2023-07-26 at 9 06 39 AM](https://github.com/scientist-softserv/utk-hyku/assets/29311858/e701d7c6-d733-46a9-9002-3453dc899988)
![Generic Work 2023-07-18 1 task 🎁 Ability to search for all allinson flex metadata properties in the UV #460 ID 0908b0fc-7462-455d-a33e-297f61df2599 Hyku 2023-07-26 at 9 06 30 AM](https://github.com/scientist-softserv/utk-hyku/assets/29311858/6c969299-fd36-4f52-8c05-cc48ba79329e)
</details>

**Comment by ShanaLMoore** [comment]
Thanks @DiemBTran You're right, the login on the work show page is flipped. Correction incoming!! 🙈 

https://github.com/scientist-softserv/utk-hyku/pull/498

**Comment by laritakr** [comment]
Passes QA:
- feature option does not show in dc tenant (both work show page and feature flipper admin option)
- feature option shows in ir and qa tenants (both work show page and feature flipper admin option)
- feature button functions appropriately in ir and qa tenant, with button toggling to "unfeature" and work appearing on home page.

**Comment by josh-morgan117** [comment]
This just applies to works and not collections, right?
