### ISSUE TITLE
Spike: Collection Splash Page is responsive and mobile friendly

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#477]
# Updated Ticket

## Summary
UTK would like this ticket to be mobile friendly and responsive. We need to do an audit on the mobile view to figure out what needs to be fixed. Then make the follow up ticket to fix those items.

## Accepted Criteria
- [ ] Audit complete on collection splash page
- [ ] Follow up ticket created

<details><summary>Original Ticket (Audit done on page before it was complete, so not relevant)</summary>
# Summary
<details><summary>Expanded language options</summary>
When a user clicks on the options for the site languages the header is does not expand with it. See screenshots below.
<img width="419" alt="Screen Shot 2023-07-19 at 12 32 13 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/b3125641-7f27-42ee-85b9-4f6e07ab2f20">

<img width="405" alt="Screen Shot 2023-07-19 at 12 32 02 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/80010bb5-b4f6-4899-a5c8-0f5d23321ded">

</details>

<details><summary>Horizontal Scroll</summary>
User has to scroll horizontally to be able to view entire page width. 

https://github.com/scientist-softserv/utk-hyku/assets/84697174/5d422df4-35ff-47aa-acbf-df13a3bde21f

</details>

<details><summary>"Digital Collections" Header</summary>
The "Digital Collections" heading is cut off at the top. It looks like there needs to be more padding on the bottom as well (under "our collections")

<img width="395" alt="Screen Shot 2023-07-19 at 1 03 14 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/1505c998-8630-4e84-a742-8bedf3aba3bf">

</details>

<details><summary>Page content alignment</summary>
When user scrolls all the way to the left, the page content does not appear to be aligned correctly and is cut off

https://github.com/scientist-softserv/utk-hyku/assets/84697174/6bab5ed9-b0b5-43cc-bceb-967e3289f5db
</details>

<details><summary>Collection Title</summary>
Collection title does not fit on the page and it's contents overlap each other.

<img width="394" alt="Screen Shot 2023-07-19 at 1 04 23 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/c539193a-4cb9-4c39-8850-5c981c615fb0">
</details>

# Acceptance Criteria

- [ ] **Expanded language options**: when language options are expanded, the logo and 'libraries' do not break onto separate lines and the options look cohesive
- [ ] **Horizontal Scroll**: User does not have to scroll horizontally to view entire width of the page contents
- [ ] **"Digital Collections" Header**: The entire "Digital Collections: Explore items digitized from our collections." is visible and has appropriate padding
- [ ] **Page Content Alignment**: The entire contents of the page are visible and do not require a horizontal scroll to view
- [ ] **Collection Title**: The collection title, item count, tags, last update, and url are not cut off and do not overlap each other

</details>

**Comment by jillpe** [comment]
#62 is still in progress. Can not adjust responsiveness until that is complete

**Comment by kirkkwang** [comment]
This spike was based on https://github.com/scientist-softserv/utk-hyku/pull/511 which has not been merged in but I believe it would be pretty close to the final collection splash page

https://github.com/scientist-softserv/utk-hyku/assets/19597776/c3c8a4bf-b813-4cb1-b7e4-3d6899ed8874

- [ ] There is horizontal scrolling
- [ ] Hero image is too tall and touching the element above it
- [ ] Digital Collections banner below the splash image doesn't have the correct vertical alignment
- [ ] Title too big
- [ ] Admin controls are not center aligned like the other pages
- [ ] Metadata not wrapping
- [ ] Bottom table extending too far to the right
- [ ] Work thumbnail disappeared

**Comment by ShanaLMoore** [comment]
Closing this ticket per Kirk's comment. A new implementation ticket will be created for the work.
