### ISSUE TITLE
Work Show Page is responsive and mobile friendly

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#479]
# Summary
<details><summary>Header Logo at 375 x 667</summary>
The log and 'libraries' line breaks at this dimension. 
<img width="364" alt="Screen Shot 2023-07-19 at 1 54 55 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/1d522610-424e-4760-b5f9-9f1e9fac76a6">

</details>

<details><summary>"Digital Collections" Header</summary>
The "Digital Collections" heading is cut off at the top. It looks like there needs to be more padding on the bottom as well (under "our collections")

<img width="391" alt="Screen Shot 2023-07-19 at 1 55 16 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/2fe5c15e-0a2b-4502-9959-2d9404b444b4">

</details>

<details><summary>Search Bar</summary>
Search Bar appears cramped and user cannot read "Search Digital Collections"
<img width="387" alt="Screen Shot 2023-07-19 at 1 56 59 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/4d7f4d4c-f109-4439-8168-bad0636f3dcb">

</details>

<details><summary>Item Details: "Intermediate Provider:</summary>
Under the item details section all of the field titles appear aligned properly except "Intermediate Provider". It overlaps the next column of informations. 

<img width="388" alt="Screen Shot 2023-07-19 at 1 57 41 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/997b9bd0-a8d5-4a9b-b297-f82728815dcc">

</details>

<details><summary>Expanded language options</summary>
When a user clicks on the options for the site languages the header is does not expand with it. See screenshots below.
<img width="419" alt="Screen Shot 2023-07-19 at 12 32 13 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/b3125641-7f27-42ee-85b9-4f6e07ab2f20">

<img width="405" alt="Screen Shot 2023-07-19 at 12 32 02 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/80010bb5-b4f6-4899-a5c8-0f5d23321ded">

</details>

# Acceptance Criteria

- [x] **Header Logo**: The logo and 'libraries' do not break onto separate lines 
- [x] **"Digital Collections" Header**: The entire "Digital Collections: Explore items digitized from our collections." is visible and has appropriate padding
- [x] **Search Bar**: Search bar does not have contents cut-off
- [x] **Item Details**: All of the field titles are a separate column from all of the field values, so there is no overlap between the 2
- [x] **Expanded language options**: when language options are expanded, the logo and 'libraries' do not break onto separate lines and the options look cohesive

# Testing Instructions
Navigate to a work's show page
Ensure the following are accurate:
  - [ ] **Header Logo**: The logo and 'libraries' do not break onto separate lines 
  - [ ] **"Digital Collections" Header**: The entire "Digital Collections: Explore items digitized from our collections." is visible and has appropriate padding
  - [ ] **Search Bar**: Search bar does not have contents cut-off
  - [ ] **Item Details**: All of the field titles are a separate column from all of the field values, so there is no overlap between the 2
  - [ ] **Expanded language options**: when language options are expanded, the logo and 'libraries' do not break onto separate lines and the options look cohesive

# Notes

**Comment by jillpe** [comment]
SoftServ QA:

- [x] **Header Logo**: The logo and 'libraries' do not break onto separate lines 
<details><summary>Screenshot></summary>
  https://github.com/scientist-softserv/utk-hyku/assets/84697174/8ee4b4fd-80a0-4794-989a-abbaa6822250
</details>

- [x] **"Digital Collections" Header**: The entire "Digital Collections: Explore items digitized from our collections." is visible and has appropriate padding
  <details><summary>Screenshots</summary>
  ![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/6f3d6274-1992-4aef-bec0-43bc81c67f23)

  </details>

- [x] **Search Bar**: Search bar does not have contents cut-off
  <details><summary>Screenshots</summary>
    ![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/6f3d6274-1992-4aef-bec0-43bc81c67f23)
  </details>

- [x] **Item Details**: All of the field titles are a separate column from all of the field values, so there is no overlap between the 2
  <details><summary>Screenshots</summary>
  

https://github.com/scientist-softserv/utk-hyku/assets/84697174/85066754-252f-4427-b5ce-838277ea07e9


  </details>

- [x] **Expanded language options**: when language options are expanded, the logo and 'libraries' do not break onto separate lines and the options look cohesive
  <details><summary>Screenshots</summary>
  

![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/8f1ec2ff-4d03-4463-93d5-985fd984a250)



  </details>


Things I noticed (does not affect QA of this ticket, I will create separate tickets for them)
- #517

**Comment by josh-morgan117** [comment]
Besides what Jill pointed out this looks good.
