### ISSUE TITLE
About Page is responsive and mobile friendly

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#481]
# Summary
<details><summary>Header Logo at 375 x 667</summary>
The log and 'libraries' line breaks at this dimension. 
<img width="364" alt="Screen Shot 2023-07-19 at 1 54 55 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/1d522610-424e-4760-b5f9-9f1e9fac76a6">

</details>

<details><summary>"Digital Collections" Header</summary>
The "Digital Collections" heading is cut off at the top. It looks like there needs to be more padding on the bottom as well (under "our collections")

<img width="391" alt="Screen Shot 2023-07-19 at 1 55 16 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/2fe5c15e-0a2b-4502-9959-2d9404b444b4">

</details>

<details><summary>Search Bar</summary>
Search Bar appears cramped and user cannot read "Search Digital Collections"
<img width="387" alt="Screen Shot 2023-07-19 at 1 56 59 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/4d7f4d4c-f109-4439-8168-bad0636f3dcb">

</details>

<details><summary>Expanded language options</summary>
When a user clicks on the options for the site languages the header is does not expand with it. See screenshots below.
<img width="419" alt="Screen Shot 2023-07-19 at 12 32 13 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/b3125641-7f27-42ee-85b9-4f6e07ab2f20">

<img width="405" alt="Screen Shot 2023-07-19 at 12 32 02 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/80010bb5-b4f6-4899-a5c8-0f5d23321ded">

</details>

# Acceptance Criteria

- [x] **Header Logo**: The logo and 'libraries' do not break onto separate lines 
- [x] **"Digital Collections" Header**: The entire "Digital Collections: Explore items digitized from our collections." is visible and has appropriate padding
- [x] **Search Bar**: Search bar does not have contents cut-off
- [x] **Expanded language options**: when language options are expanded, the logo and 'libraries' do not break onto separate lines and the options look cohesive
- [x] link to **About** is visible on a mobile screen
  

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/12dd9002-7382-4885-b716-0dde6f55ec51)

# Testing Instructions
View the about page at various sizes. Confirm that it adjusts and is responsive/mobile friendly. 

# Notes

**Comment by jillpe** [comment]
Staging QA blocked until #478 fixes are up

**Comment by jillpe** [comment]
Clients confirmed search bar is okay in client meeting 2023-08-01. This passes SoftServ QA

**Comment by jillpe** [comment]
SoftServ QA: 

<details><summary>Header Logo ✅ </summary>


![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/2e2c19f0-4cd6-4df6-b399-d160c3ced3c7)


</details>


<details><summary>"Digital Collections" Header ✅ </summary>


![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/7e90398b-a6e7-47db-869c-1cd5500c3343)


</details>


<details><summary>Expanded language options ✅ </summary>


![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/1f4bbbb9-bb5f-4045-a8d9-33b5e5718c9c)


</details>


<details><summary>link to About on home page ✅ </summary>


![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/ff53cf4c-dcfa-41ed-b60a-60f45fff168f)


</details>

**Comment by josh-morgan117** [comment]
I tried to copy and paste text from our current about page into this one and it wasn't wrapping, so I think there was just some text formatting overriding that. I put in my own random text and I see there is a small amount of padding missing on the left.

![Image](https://github.com/scientist-softserv/utk-hyku/assets/14128309/e162a85f-bd06-4ddb-bd7e-061610d8441c)
