### ISSUE TITLE
File Set Show Page is responsive and mobile friendly

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#482]
# Summary
<details><summary>Header Logo at 375 x 667</summary>
The log and 'libraries' line breaks at this dimension. 
<img width="364" alt="Screen Shot 2023-07-19 at 1 54 55 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/1d522610-424e-4760-b5f9-9f1e9fac76a6">

</details>

<details><summary>"Digital Collections" Header</summary>
The "Digital Collections" heading is cut off at the top. It looks like there needs to be more padding on the bottom as well (under "our collections")

<img width="391" alt="Screen Shot 2023-07-19 at 1 55 16 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/2fe5c15e-0a2b-4502-9959-2d9404b444b4">

</details>

<details><summary>Search Bar</summary>
Search Bar appears cramped and user cannot read "Search Digital Collections"
<img width="387" alt="Screen Shot 2023-07-19 at 1 56 59 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/4d7f4d4c-f109-4439-8168-bad0636f3dcb">

</details>

<details><summary>Expanded language options</summary>
When a user clicks on the options for the site languages the header is does not expand with it. See screenshots below.
<img width="419" alt="Screen Shot 2023-07-19 at 12 32 13 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/b3125641-7f27-42ee-85b9-4f6e07ab2f20">

<img width="405" alt="Screen Shot 2023-07-19 at 12 32 02 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/84697174/80010bb5-b4f6-4899-a5c8-0f5d23321ded">

</details>

# Accepted Criteria

- [ ] **Header Logo**: The logo and 'libraries' do not break onto separate lines 
- [ ] **"Digital Collections" Header**: The entire "Digital Collections: Explore items digitized from our collections." is visible and has appropriate padding
- [ ] **Search Bar**: Search bar does not have contents cut-off
- [ ] **Expanded language options**: when language options are expanded, the logo and 'libraries' do not break onto separate lines and the options look cohesive

# Testing Instructions

**Comment by ShanaLMoore** [comment]
There's horizontal scrolling as a mobile viewer.

**Comment by jillpe** [comment]
Staging QA blocked until #478 fixes are up

**Comment by jillpe** [comment]
Clients confirmed search bar is okay in client meeting 2023-08-01. This passes SoftServ QA

**Comment by jillpe** [comment]
SoftServ QA: 

<details><summary>Header Logo ✅ </summary>


![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/5280da15-200d-4de5-ba2e-7a27850d9751)


</details>


<details><summary>"Digital Collections" Header ✅ </summary>


![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/37216b7f-53b0-4ec3-9893-bc5a07cfc37f)


</details>


<details><summary>Expanded language options ✅ </summary>


![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/3a876dba-1bae-4443-81f4-fe8a384b96f2)


</details>
