### ISSUE TITLE
Install CloverIiif

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#483]
# Summary

This ticket is to install CloverIiif and replace the Universal Viewer experience for Audio/Video records. 

# Acceptance Criteria

- [ ] When visiting Audio/Video records, CloverIiif media player is rendered/used. 
- [ ] When visiting other work types, the universal viewer is displayed/used. 

# Testing Instructions

- [ ] Visit or create a generic work with a fileset. Confirm that the universal viewer(UV) is displayed. 
- [ ] Visit or create a audio work, confirm that cloveriiif is displayed instead of the UV
  - [ ] To create a UTK Audio work:
    - [ ] Create an Audio work with no file sets
    - [ ] Create an `Attachment` first with the RDF Type of `http://pcdm.org/use#IntermediateFile` and add the file set onto the attachment
    - [ ] After the Attachment is created, make the Attachment a child work of the Audio work
    - [ ] In the Audio work, set the thumbnail and representative media to the Attachment
- [ ] Create a video work, confirm that cloveriiif is displayed instead of the UV
  - [ ] Same instructions as creating an Audio work

**Comment by DiemBTran** [comment]
temporarily blocked for QA due to a JS issue with buttons. Fix should be coming in soon

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- generic work: https://qa.utk-hyku-staging.notch8.cloud/concern/generic_works/94f5d7e5-90d1-44e4-925c-9fc075c6e934?locale=en
- audio work: https://qa.utk-hyku-staging.notch8.cloud/concern/audios/adb6df16-ba15-4626-9b01-2cf38d550301
- audio attachment: https://qa.utk-hyku-staging.notch8.cloud/concern/parent/adb6df16-ba15-4626-9b01-2cf38d550301/attachments/949edf8e-1294-47f4-86a3-ec814deadcb0
- video work: https://qa.utk-hyku-staging.notch8.cloud/concern/videos/060fe989-4121-4594-a008-18a94f996d8e?locale=en
- video attachment: https://qa.utk-hyku-staging.notch8.cloud/concern/attachments/58409841-9d8f-449a-bc81-9c96de27fddb?locale=en


<details><summary>Non A/V works show the UV. Works with A/V show the CloverIIIF viewer.</summary>

![Generic Work 2023-07-09 Revert to main branch of IiifPrint #454 ID 94f5d7e5-90d1-44e4-925c-9fc075c6e934 Hyku 🔊 2023-07-25 at 2 48 12 PM](https://github.com/scientist-softserv/utk-hyku/assets/29311858/4eef85f6-f29c-4da4-993a-e5bc03ca4f87)
![Audio Install CloverIiif #483 audio p2 ID adb6df16-ba15-4626-9b01-2cf38d550301 Hyku 2023-07-25 at 2 47 53 PM](https://github.com/scientist-softserv/utk-hyku/assets/29311858/db57b8fc-fcd5-41e6-8995-a8aed0456712)
![Video Install CloverIiif #483 video p2 ID 060fe989-4121-4594-a008-18a94f996d8e Hyku 🔊 2023-07-25 at 2 48 03 PM](https://github.com/scientist-softserv/utk-hyku/assets/29311858/5a089b89-cf54-43a1-b9f5-333c4a52cd4e)

</details>

**Comment by jillpe** [comment]
Verification on production blocked until #358 resolved

**Comment by markpbaggett** [comment]
This one looks good.  Moving to done.
