### ISSUE TITLE
Run Translations

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#487]
# Summary

Run translations at the end of milestone 2. 

We'd like to hold off on running this because each time we do it costs money. Instead of running it each time we'll run them all once the milestone 2 tickets are complete. 

# Acceptance Criteria

- [ ] Run translations
- [ ] Any value added to updated to en.yaml locale file should be translated.

# Screenshots or Video
<img width="495" alt="image" src="https://github.com/scientist-softserv/utk-hyku/assets/10081604/a750a34d-2307-4b8f-aa9c-311f6b998c8f">

# Testing Instructions
log into dc staging as an admin user
Inspect over batch collection checkbox from the works index page within the admin dashboard. 
The label should say "Check to batch delete collections."

Switch language to spanish for example. (Espanol)
Make sure it doesn't break translations. (you'd see a missing translation value for the label).
Ideally the label will be translated to spanish. **NOTE**: The accuracy of such translation is not within our control as we run a generator to translate it. 

# Notes

see 1password for credentials

how to: https://playbook-staging.notch8.com/en/samvera/hyrax/how_to/generate_translations

**Comment by jillpe** [comment]
SoftServ QA: Pass

<details><summary>English</summary>


![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/dd0a28d9-9001-469d-b82c-3379d498be5f)


</details>


<details><summary>Spanish</summary>


![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/f2a48155-5bc2-4276-a325-6507c75d5ad4)


</details>
