### ISSUE TITLE
Configure Drivers for Browse Everything

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#49]
# Summary
The [Browse Everything](https://github.com/samvera/browse-everything#what-is-browseeverything) setup has already been completed. This ticket is to get client feedback and credentials for the drivers they would like to use. The options include: 

Dropbox, Google Drive, Box, Amazon S3.

# Acceptance Criteria

- [ ] The UTK client should be able to retrieve files from their various services

**Comment by DiemBTran** [comment]
Linked items:

- [5] BrowseEverything for Bulkrax
- [3] BrowseEverything Setup for Work

**Comment by DiemBTran** [comment]
Related MRs:

- [21 59 enable browse everything (Work and Bulkrax)](https://gitlab.com/notch8/utk-hyku/-/merge_requests/32)

**Comment by jillpe** [comment]
no longer in scope 2023-04-19
