### ISSUE TITLE
Workflow Setup and Customization - Digital Collections Repository

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#5]
# Summary

# Acceptance Criteria
- [ ] Allows custom notifications for depositors via email as the associated workflow progresses (ETD approved, ETD published, etc.)
- [ ] Ability for users to view pending submissions that are awaiting approval
- [ ] Ability for users to view approved submissions
- [ ] Ability for users to view reviewed not yet approved submissions and comment details

# Screenshots/Videos

# Testing

# Notes
**How will users be assigned to workflows?**
**How will submitters determine where they can deposit**

Information on Current UTK workflow and requirements: https://trace-work-types.readthedocs.io/en/latest/workflows/etd.html#future-etd-workflow

**Comment by jillpe** [comment]
related to #4

**Comment by jillpe** [comment]
This ticket was made before the new requirements. Is this still relevant?

**Comment by bkiahstroud** [comment]
This requirement was primarily for the IR configuration, we don't need it for the DL. 

As discussed in [the 2024-04-09 meeting](https://docs.google.com/document/d/1jRGJ8elYl2OwFmCmIgP8n68t_4tZvfvZhScDoHwEHdg/edit), no work is required. The application will have a single AdminSet that utilizes the Default (non-mediated) Workflow.
