### ISSUE TITLE
Spike: EZID for ARK

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#50]
# Summary
EZID is the provider for ARK. They want 4 metadata fields for ARK and would like to mint inside EZID (for works or collections)

# Accepted Criteria
- [ ] We have a plan for having 4 metadata fields for ARK
- [ ] We have a plan to mint inside EZID

# Notes
- What metadata fields should be included?

Resources: 
- https://github.com/duke-libraries/ezid-client
- https://ezid.cdlib.org/doc/apidoc.html

**Comment by jillpe** [comment]
no longer in scope 2023-04-19
