### ISSUE TITLE
🐛 UTK prod parent UV not displaying

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#500]
# Story

**UPDATE: This is related to the archivision bug Mark pointed out to LaRita and I. ref: https://dc.utk-hyku-production.notch8.cloud/concern/images/2228b50c-4b6b-4d7c-b687-77076e977244?locale=en

**We need to reindex prod data to resolve this ticket, but doing so will fail until we resolve the above ^^** 

ref: 
- [x] #512

The client reported that they are blocked from doing any client verification because they can't see the UV of the parent work.

ref: slack thread convo: https://assaydepot.slack.com/archives/C031E2P1RJM/p1690392921558279

## PRODUCTION exploration

example: https://dc.utk-hyku-production.notch8.cloud/concern/images/2228b50c-4b6b-4d7c-b687-77076e977244?locale=en
<details> 

<summary> Works index page. They should have thumbnails. </summary>

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/ca508e48-7d7a-4f57-81fb-6bd1ff7b561a)

</details>
<details> 

<summary> clicking into a parent work should display a UV if it has an attachment w a fileset (and it does): </summary>

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/8c4970a8-137e-4819-87a0-d4ed7a83774c)

</details>
<details> 

<summary> clicking into the attachment displays the UV, as expected: </summary>

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/2aba5391-ec2f-4c87-b66d-1af5ca085f2d)

</details>
<details> 

<summary> Confirmed the fileset is attached: </summary>

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/c174eebf-2225-40da-a885-fc202c09851f)

</details>

# Notes

⚠ This is blocking the client verification tickets and thus the closing out of milestone 2 tickets ⚠ 
**UPDATE: The client can edit a work and save it without making changes, to manually unblock themselves for now**

Shana was able to manually create two works in the prod qa tenant. [1 has an attachment/fileset](https://qa.utk-hyku-production.notch8.cloud/concern/generic_works/7003dd05-f143-4c8a-af89-bbcc5bc85a3c),[ another has a multipage pdf attached](https://qa.utk-hyku-production.notch8.cloud/concern/pdfs/136ab86a-7ff2-495e-b0e9-cda54b933c8c?locale=en) (which split into attachments with filesets). Both are displaying the parent UV as expected. So this may be a bulkrax issue.

<details> 

<summary> See screenshots </summary>

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/2d564c72-c3b9-4fe4-809b-0d11841516d9)

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/25cfb5de-77de-44dc-a9ae-c268094ff34d)

</details>

~~Perhaps it's the workflow they are using. It appears they are importing works only first. Then doing follow up imports with attachment/file_sets?~~

~~i think this could be reproduced using a simple bulkrax csv or zip import.~~

**Comment by ShanaLMoore** [comment]
LOL to random thoughts at 4am insomnia. 😓 the answer literally just came to me.

The problem is that for some reason, these works don't have rendering ids set. 



![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/590f03be-cf83-4c8d-859e-81010628506e)




<details> 

<summary> Example similar to the one in the description </summary>

ref: https://dc.utk-hyku-production.notch8.cloud/concern/images/88bf609e-73ab-4fa0-820c-e84ca9a31853?locale=en

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/c7b8182a-c7b4-4868-8f41-a55ac1b62ded)

</details>
<details>

<summary> Edit the work, select OBJ for rendering: </summary> 

## Note: representative media and thumbnail are already selected


![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/d409d293-ad0b-4a82-bbd9-21a6bf4b6911)

</details>
<details>

<summary> After selecting rendering the UV displays </summary>



![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/bd1fbd19-45ac-4056-b842-273dc2df25ec)

</details>

# TODO: 
- try to reproduce this problem locally
- check [setParentThumbnailJob](https://github.com/scientist-softserv/utk-hyku/blob/main/app/jobs/set_default_parent_thumbnail_job.rb). 
  - I thought rendering_id was supposed to be set in this job. 
- check [rake tasks](https://github.com/scientist-softserv/utk-hyku/blob/main/lib/tasks/set_parent_thumbnail.rake) that should set the parent thumbnail too. 
- add check for rendering_ids to spec
  
At a quick glance it looks like we missed setting the representative id in both places. 

Note: This work was taken from/inspired by work done in LV:
  - ref original job: https://github.com/scientist-softserv/louisville-hyku/blob/main/app/jobs/set_default_parent_thumbnail_job.rb
  - ref original rake task: https://github.com/scientist-softserv/louisville-hyku/blob/main/lib/tasks/set_parent_thumbnail.rake#L21
  - ref original spec: https://github.com/scientist-softserv/louisville-hyku/blob/main/spec/jobs/bulkrax/set_default_parent_thumbnail_job_spec.rb

We need to add the setting of rendering IDs to both places. In prod we will likely need to resolve the existing data by running the rake task after it's corrected.

**Comment by jillpe** [comment]
[Comments from client:](https://assaydepot.slack.com/archives/C0396LSM06P/p1690468684786559?thread_ts=1690388420.767169&cid=C0396LSM06P)

>1. only our most recent imports (274 -288?) have UV on the Attachment.  No other imports before that have this. I chalked this up to us importing a long time ago and whatever magic that added UV there was missing.
>2. i think it’s important to remember how we’ve historically imported collections.  we have a long history of failed imports due to trying to import works, attachments, and filesets at the same time.  for that reason, we started importing all works first then attachments and filesets, but recently shifted to works, then attachments, then filesets because that seemed to make it so that filesets imports rarely failed 10 out of every 5000 or so instead of 40 out of 800. i realized recently that this method actually makes it so the “thumbnail generation” trigger on the work to never run after relationships are created, because the attachment gets attached to the work before it has a fileset.  to fix this, we’ve actually been rerunning all our attachment imports (metadata only) after filesets are attached in order to get the thumbnail generation job to run. 
>3. i’m wondering if our woes with all of this all come back to us trying to expedite imports and avoid import failures by separating imports into tasks based on “type.” i haven’t tried an Image import on staging in a very long time, but maybe it’d be worth looking at what happens when we import an entire with with fileset and attachments in 1 job and what happens when we split that same job into 3 separate imports.

**Comment by ShanaLMoore** [comment]
My new theory is that everything is fine. I created new importers in prod and they are running as expected and getting thumbnails/UV displayed. 

Now I'm guessing when we deployed last to prod we never ran the set thumbnail rake task to handle existing data. 

The problem records must have been imported before the SetParentThumbnailJob existed.

**Comment by ShanaLMoore** [comment]
It turns out that selecting a rendering item wasn't the problem after all. Kirk noticed that the staging UVs were working and they don't have rendering items selected. So it was actually the save/reindexing of that work that fixed the reason the UV wasn't displaying.

This was confirmed by opening a work to edit, and then saving it without making any changes. Also to confirm, in rancher i found a work and called update_index on it; it worked. 

I tried to reindex prod data last night but woke up to a message saying it was killed: 



![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/aa44bfee-ed4d-4d7e-961d-6352e19202de)




I'll hope to figure out what caused the reindexing to fail and run it again over the weekend.

**Comment by ShanaLMoore** [comment]
blocked by #516

**Comment by laritakr** [comment]
We need to reindex the filesets first, and then parent works. Attachments are not necessary to be reindexed. 

Before this happens, we want to check what is in solr for the following works:
- [a good one where we edited the fileset then the work](https://dc.utk-hyku-production.notch8.cloud/concern/images/eacafb36-5dff-43fe-b12e-e4f51213d231?locale=en)
- [same collection where we’ve updated neither yet, but presumably the work was reindexed last night:](https://dc.utk-hyku-production.notch8.cloud/concern/images/d2e13c81-9dc9-47b2-a009-e743bb1960df?locale=en)
- [one from the same collection where we’ve updated the fileset only ](https://dc.utk-hyku-production.notch8.cloud/concern/images/cd961577-fb53-4373-90dd-d423b8f250b0?locale=en)

The goal here is to look at which fields are missing from the works and filesets we are reindexing, so we can identify if the ingesting sequence is causing the problem and determine the best method of ingest to avoid further issues.

Once we know what is on the solr doc for each parent work and the fileset that should be showing in the UV, we can proceed with reindexing.

**Comment by ShanaLMoore** [comment]
https://assaydepot.slack.com/archives/C0311DN2YCA/p1691661472033989

Rob may have discovered a related issue

```
F, [2023-08-10T09:53:51.952203 #1] FATAL -- : [8627d818ea703eb632d706c4ff19d24f] ActionView::Template::Error (Failed to open TCP connection to fcrepo.default.svc.cluster.local:8080 (Connection refused - connect(2) for "fcrepo.default.svc.cluster.local" port 8080)):
F, [2023-08-10T09:53:51.952355 #1] FATAL -- : [8627d818ea703eb632d706c4ff19d24f]     32:       <%= link_to 'Download', hyrax.download_path(file_set),
[8627d818ea703eb632d706c4ff19d24f]     33:         title: "Download #{file_set.to_s.inspect}", target: "_blank" %>
[8627d818ea703eb632d706c4ff19d24f]     34:     </li>
[8627d818ea703eb632d706c4ff19d24f]     35:     <% IiifPrint::Data::WorkDerivatives.new(file_set.id).keys.each do |name| %>
[8627d818ea703eb632d706c4ff19d24f]     36:       <li role="menuitem" tabindex="-1">
[8627d818ea703eb632d706c4ff19d24f]     37:         <a href="<%= "/downloads/#{file_set.id}?locale=en&file=#{name}" %>" download>
[8627d818ea703eb632d706c4ff19d24f]     38:           Download <em>(as <%= name %>)</em>
F, [2023-08-10T09:53:51.952379 #1] FATAL -- : [8627d818ea703eb632d706c4ff19d24f]   
F, [2023-08-10T09:53:51.952404 #1] FATAL -- : [8627d818ea703eb632d706c4ff19d24f] config/initializers/slug_override.rb:7:in `find'
[8627d818ea703eb632d706c4ff19d24f] app/views/hyrax/base/show.html.erb:33:in `_app_views_hyrax_base_show_html_erb___2635501944449706692_550220'
```

**Comment by ShanaLMoore** [comment]
todo: reindex works. the rake tasks is loading too many things in memory and crashes. reindex of filesets completed successfully.

**Comment by laritakr** [comment]
This should be fixed by the rake task which is running to add the parent thumbnails. Verify, then move to client QA when rake task completes.

**Comment by jillpe** [comment]
This has been confirmed fixed
