### ISSUE TITLE
🦄 Spike: Groups / roles

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#507]
# Summary

This is the planning ticket for 
- #4  

# Acceptance Criteria
- [x] Current status of Groups/Roles is documented
- [ ] Relevant prs, tickets, notes, etc. are documented
- [ ] Follow up tickets to complete #4 are made and linked in the ticket

**Comment by jillpe** [comment]
[Audit Notes from 8/2023](https://github.com/scientist-softserv/utk-hyku/issues/529)

**Groups and Roles**

[Workflow Mark requested:](https://github.com/scientist-softserv/utk-hyku/issues/4#issuecomment-1531653670)
- We could have one admin set that all participants can deposit into that goes through review - and then the default admin set would remove permissions for everyone except admins to deposit into. This would then give you the ability to have an administrators or chosen set of ppl submitting without review and everything else goes through a review process
  - UTK said this would be okay for right now, but still wanted to have the groups and roles features for their future workflows

Testing based on [Groups and Roles documentation](https://github.com/samvera/hyku/wiki/Groups-with-Roles-Feature#defining-roles-users-and-groups)
* Groups
  * [Do not have the ability](https://dc.utk-hyku-staging.notch8.cloud/admin/groups/new?locale=en)
  
* Workflow Roles
  * Have the option to assign roles, however, it does not appear to save
    * Ex. admin@example.com should only have ability to deposit/access Default Admin set, however has the ability to create a work type for all of the sets (Mountains, Default Admin, Submission Review

* Users
  * [Could not add users/roles through Dashboard](https://dc.utk-hyku-staging.notch8.cloud/admin/users?locale=en)
    * Shows that the user's status is pending (ex. jill@scientist.com user), however email was never sent to her

**Comment by bkiahstroud** [comment]
This requirement was primarily for the IR configuration, we don't need it for the DL. 

As discussed in [the 2024-04-09 meeting](https://docs.google.com/document/d/1jRGJ8elYl2OwFmCmIgP8n68t_4tZvfvZhScDoHwEHdg/edit), no work is required. The application will have a single AdminSet that utilizes the Default (non-mediated) Workflow.
