### ISSUE TITLE
:bug: NoMethodError - undefined method `work?' for nil:NilClass Bug

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#512]
# Summary

Several recent [importers](https://dc.utk-hyku-production.notch8.cloud/importers/208/entries/314425?locale=en) contain NoMethodError - undefined method `work?' for nil:NilClass Bug failures: 

<details> 

<summary> Screenshots </summary> 

![Screenshot 2023-07-28 at 10-30-06 Show Importer __ Hyku](https://github.com/scientist-softserv/utk-hyku/assets/10081604/8dd19a20-21d6-4e96-8203-71ab70af2811)

![image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/6bc4c5a9-4c40-4aae-84ae-661a8fc9738e)

</details> 

LaRita has seen a [similar bug](https://github.com/samvera-labs/bulkrax/issues/804) before and thinks that #ordered_works is returning nothing, which is causing this error. If so, it's because of a race condition.

We have a [PR in Bulkrax](https://github.com/samvera-labs/bulkrax/pull/844) to resolve this, however, when tested in production the failures still persist so there must be another place or more work to be done somewhere. 

related to
- #500 

# Acceptance Criteria

- [ ] Reimporting a failed archivision import should succeed (or not throw the above error at the very least)

# Testing Instructions

In production, find an importer that has several failures. The error message should match the title of this ticket. The importers titled archivision have a ton of these errors. Re run the importer and confirm that it no longer reports this error. 

# Notes

Fixing this will hopefully solve the reason why we can't reindex works too. 

archivision files from prod: 
[archivision_works_and_collection.csv](https://github.com/scientist-softserv/utk-hyku/files/12197253/archivision_works_and_collection.csv)
[archivision_full_no_uris_restricted_chunk_0 copy.csv](https://github.com/scientist-softserv/utk-hyku/files/12197249/archivision_full_no_uris_restricted_chunk_0.copy.csv)
[archivision_restricted_attachments_0 copy.csv](https://github.com/scientist-softserv/utk-hyku/files/12197251/archivision_restricted_attachments_0.copy.csv)

**Comment by ShanaLMoore** [comment]
Marked High Priority because it impacts client ingests and is a blocker for #500

**Comment by ShanaLMoore** [comment]
blocked by #516

**Comment by jillpe** [comment]
Patch on staging and reindex filesets on staging and then on prod. 

Please communicate w the team/QA before deploying the monkey patch branch to staging cc @laritakr 

There are quite a few QA tickets in the queue to be worked on.

**Comment by ShanaLMoore** [comment]
a [script like this](https://github.com/scientist-softserv/utk-hyku/issues/516#issuecomment-1661272944) may be helpful.

**Comment by jillpe** [comment]
resolved
