### ISSUE TITLE
🐛 Reindexing Large Data Crashes

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#516]
# Summary

We tried to run the reindex:works rake task in UTK prod over the weekend but found that it died. Rob mentioned knowledge about a memory leak with ActiveFedora. 

ref: [slack convo and thread](https://assaydepot.slack.com/archives/C031E2P1RJM/p1690639858968029)

Re work this task and backport it to Adventist upon successful completion. 

TODO: 

break the spawing off a large background job into a reindex job for each work. 

find works to reindex jobs
make individual work index job

this will be a refactor of the current reindex job/rake task

# Acceptance Criteria

- [ ] reindexing work should succeed

# Screenshots or Video

![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/4ee1c9a1-49d7-41d8-a710-3b1b5f1a11d4)

# Testing Instructions

# Notes

**Comment by ShanaLMoore** [comment]
running the rake task in prod seemed to have been successful minus 33 records that failed with LDP 500 errors: 



![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/d520237d-e41b-44ad-b2e1-6c58ef9acfc5)



![Image](https://github.com/scientist-softserv/utk-hyku/assets/10081604/59bcac32-440e-4ffa-9103-fe93934f9d17)

**Comment by ShanaLMoore** [comment]
The 33 failed were due to bad data/file_sets. 

I ran the following script in production to resolve their issues: 



```ruby
retry_jobs = Sidekiq::RetrySet.new
uuids = retry_jobs.to_a.map{|job| original_string = job.item['args'].first['arguments'].first['_aj_globalid']; original_string[/\w{8}-\w{4}-\w{4}-\w{4}-\w{12}/] }
uuids.count #29

uuids.each do |id|
  work = ActiveFedora::Base.find id

  file_set_identifiers = []
  work.file_sets.each do |fs|
    puts fs.id
    file_set_identifiers << fs.bulkrax_identifier
  end

  bulkrax_identifier = work.bulkrax_identifier
  work.destroy(eradicate: true)

  work_entry = Bulkrax::Entry.find_by(identifier: bulkrax_identifier)
  work_entry.build

  work = work_entry.factory.find

  file_set_identifiers.each do |fs_id|
    file_set_entry = Bulkrax::Entry.find_by(identifier: fs_id)
    file_set_entry.factory.find.destroy(eradicate: true)
    file_set_entry = Bulkrax::Entry.find(file_set_entry.id)
    file_set_entry.build
  end

  work.save
  Rails.logger.info "Rebuilt #{work.id}"
end

Rails.logger.info "DONE!"

```

**Comment by ShanaLMoore** [comment]
@laritakr Is the status of this ticket correct? It was in code review but I didn't see a PR from you there.

**Comment by laritakr** [comment]
> @laritakr Is the status of this ticket correct? It was in code review but I didn't see a PR from you there.

I believe that the scripts we ran fixed the problems. Did we want to merge in my commit since the rake task already did what we needed?

**Comment by ShanaLMoore** [comment]
Oh was this the one w the monkey patch? it's already merged. Ok if I close this then?

**Comment by laritakr** [comment]
I wasnt sure if https://github.com/scientist-softserv/utk-hyku/commit/3700624c55a60adcd3c0bb34df5875082f2c2b67 was merged... haven't looked. But yes I think it's ok to close

**Comment by ShanaLMoore** [comment]
cool, i just confirmed it. thanks!
