### ISSUE TITLE
GoodJob switch

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#521]
# Summary
UTK would like to swap Sidekiq for GoodJob so they can prioritize jobs more easily.

This was done in nnp and Adventist. 

Tickets that might be helpful:
- https://github.com/scientist-softserv/adventist_knapsack/issues/553
- https://github.com/scientist-softserv/adventist_knapsack/issues/562

PR that might be helpful:
- https://github.com/scientist-softserv/nnp/commit/318dcaf68dfd8456d794810e7be3517794fcc625

GoodJob Documentation
- https://github.com/bensheldon/good_job

# Accepted Criteria
- [ ] Sidekiq has been switched to GoodJob

# Testing Instructions
- [ ] Create works and attach files manually or via bulkrax. 
- [ ] verify jobs are running in /jobs
- [ ] verify /sidekiq is no longer a valid endpoint

# Note

see [PR](https://github.com/scientist-softserv/utk-hyku/pull/522) for screenshots

Merging this will prob require devs to rebuild project. Or someone can push a docker image after rebuilding, for others to pull.

No jobs should be running when we deploy this to production.

**Comment by ShanaLMoore** [comment]
<img width="1351" alt="Screenshot 2023-08-01 at 2 58 09 PM" src="https://github.com/scientist-softserv/utk-hyku/assets/10081604/69dcb747-d44c-400f-b6df-e804c8a67599">

**Comment by jillpe** [comment]
SoftServ QA: Pass!

<details><summary>Sidekiq is no longer accessible</summary>


![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/c97d5d55-883c-4b15-94ab-a63cf2b9ed12)


</details>

<details><summary>Good Jobs ✅ </summary>


![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/b8544b49-dd9d-4b6d-ac67-54664ac141e0)


</details>

**Comment by markpbaggett** [comment]
Looks good.  bumping.
