### ISSUE TITLE
Create Work Show page for DC with UV

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#57]
# Summary
update the work show page per the figma wire frames (applies to both tenants). note that the nav bar displays beneath the hero image on the home page.

# Acceptance Criteria

- [x] UTK's DC tenant should have a work show page that matches the wireframes (round 3)

# Screenshots or Video

![Image](https://user-images.githubusercontent.com/29311858/202317822-6ff8d19f-aa13-4496-914d-fdb46c5b75aa.png)

![Image](https://user-images.githubusercontent.com/29311858/202317839-f118d56c-192b-4bbf-9bbb-faba64b05d7f.png)

# Notes
UTK does not want the background color around the description/more details

https://www.figma.com/file/3JjoRJYmCrfoAcWhHu2Br4/UTK?node-id=388%3A789

**Comment by DiemBTran** [comment]
Linked items:

Relates to:

- EPIC: UTK Branding

**Comment by AKFosterDev** [comment]
## Related PRs
[#319](https://github.com/scientist-softserv/utk-hyku/pull/319)
[#326](https://github.com/scientist-softserv/utk-hyku/pull/326)

### QA Notes
Settings mentioned in the original QA instructions have been set on staging. I am noticing that the abstract is rendering within the Item Details metadata. 
- [ ] This needs to be kept from rendering in this area. 
- [ ] Metadata headings rendering in alphabetical order
- [ ] I am going to need some help making sure the metadata is rendering correctly.

![Screenshot 2023-02-07 at 1 02 17 PM](https://user-images.githubusercontent.com/39319859/217365797-119f2be8-1f75-473e-8709-01e947e5135d.JPG)

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- https://dc.utk-hyku-staging.notch8.cloud/concern/generic_works/1a121c58-4254-4523-9e6d-4a07f8f74a85

<details><summary>Click to expand</summary>

![Generic Work Error Test Work ID 1a121c58-4254-4523-9e6d-4a07f8f74a85 Hyku 2023-02-08 at 3 39 04 PM](https://user-images.githubusercontent.com/29311858/217676965-7662d14d-3e19-4f51-a20b-80880fe0b383.jpg)

![Generic Work Error Test Work ID 1a121c58-4254-4523-9e6d-4a07f8f74a85 Hyku 2023-02-08 at 3 39 13 PM](https://user-images.githubusercontent.com/29311858/217676970-7030493c-2c4c-49ab-a51a-7d3be0297704.jpg)

![Generic Work Error Test Work ID 1a121c58-4254-4523-9e6d-4a07f8f74a85 Hyku 2023-02-08 at 3 39 30 PM](https://user-images.githubusercontent.com/29311858/217676977-6d1bb3c8-f6af-445c-a497-eed3e1d2a538.jpg)


</details>

**Comment by AKFosterDev** [comment]
## Summary
Before this PR the metadata table was not rendering correctly and the abstract for the work was showing in this section. This PR addresses the rendered table data and styles.

## Related PR
[#337 - i57 Work Show Page Metadata Section](https://github.com/scientist-softserv/utk-hyku/pull/337)

## Screenshots
<details>
<summary><strong>Before this PR</strong></summary>
<img src="https://user-images.githubusercontent.com/39319859/218182582-22d519d1-d27c-47ce-9ee8-8ed08b1fcbb0.JPG"/>
</details>

<details>
<summary><strong>After this PR</strong></summary>

<details>
<summary><strong>Full Screen</strong></summary>
<img src="https://user-images.githubusercontent.com/39319859/218200943-dbfa511a-43a3-4aa0-848e-9e5065f902b3.JPG"/>
</details>

<details>
<summary><strong>991px Screen</strong></summary>
<img src="https://user-images.githubusercontent.com/39319859/218201295-666ad993-aeac-4032-bea8-605c59f7b40f.JPG"/>
</details>

<details>
<summary><strong>767px Screen</strong></summary>
<img src="https://user-images.githubusercontent.com/39319859/218201510-32b7c646-2842-4563-8f41-32070c1c029e.JPG"/>
</details>
</details>

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://dc.utk-hyku-staging.notch8.cloud/concern/generic_works/980329f0-cb13-47b8-a5d6-5949a173a537

<details><summary>The Abstract now renders outside of "Item Details," above it. Abstract is listed as "Description"</summary>



![Image](https://user-images.githubusercontent.com/29311858/218562165-bd0f76a4-36f1-4764-b2a7-3f2c42c91479.jpg)
</details>

**Comment by josh-morgan117** [comment]
@AKFosterDev , the team agreed to justify left to remove the extra spacing from center alignment.

**Comment by AKFosterDev** [comment]
PR to address the text alignment request from the client above
- https://github.com/scientist-softserv/utk-hyku/pull/345

**Comment by AKFosterDev** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- https://dc.utk-hyku-staging.notch8.cloud/concern/generic_works/1a121c58-4254-4523-9e6d-4a07f8f74a85

<details><summary>Click to expand</summary>

![Screenshot 2023-02-17 at 3 46 37 PM](https://user-images.githubusercontent.com/39319859/219817805-97703bbd-42bf-486c-a2a4-c11aa5a19e36.JPG)

![Screenshot 2023-02-17 at 3 46 56 PM](https://user-images.githubusercontent.com/39319859/219817845-9d0b4180-c815-4c5f-a0a5-90c6fa7bb702.JPG)


![Screenshot 2023-02-17 at 3 47 10 PM](https://user-images.githubusercontent.com/39319859/219817854-0a5cdfaf-5d2e-4d54-9301-d2f9b308f172.JPG)

</details>

**Comment by markpbaggett** [comment]
@AKFosterDev and @jillpe, historically, we've done client verification on production (not staging). Should we be doing these tickets on staging or production?

**Comment by jillpe** [comment]
Hi @markpbaggett - so theming tickets should be using the same workflow as the rest of the tickets. Everything in 'Client QA' can be tested on staging and everything in 'Client Verification' can be tested in production :)
