### ISSUE TITLE
Translation Missing errors when dereferencing display label on m3profile properties

### ISSUE THREAD

**Issue by markpbaggett** [notch8/utk-hyku#581]
# Story

After yesterday's roll to production, every front end display label is reporting a `Translation missing: en.allinson_flex.default.$WorkType.label.$Property` error when you look at the work.  This appears to affect everything regardless of when it was initially imported or what m3profile version would have been used.  You can see an example here:

https://dc.utk-hyku-production.notch8.cloud/concern/images/fc32b320-51b0-4027-878e-aa93f51eac7c?locale=en

# Acceptance Criteria

- [ ]

# Screenshots / Video

<img width="1010" alt="Screenshot 2023-12-20 at 8 30 15 AM" src="https://github.com/scientist-softserv/utk-hyku/assets/2692416/783a2cba-d0ad-492e-92d9-bd07fb4edf39">

# Testing Instructions and Sample Files

-

# Notes

**Comment by orangewolf** [comment]
@jillpe I'm closing this as I think its done. Feel free to reopen if we need to
