### ISSUE TITLE
Some Filesets Not Editable

### ISSUE THREAD

**Issue by markpbaggett** [notch8/utk-hyku#587]
# Story

Some filesets are not editable.  Even though the fileset "exists" it cannot be edited to add a new version or manipulate the object at all via the GUI.  Here is an [example](https://dc.utk-hyku-production.notch8.cloud/concern/parent/7f4300de-543c-4a7a-ae47-332211d8de59/file_sets/05162924-ffa8-462a-8dca-db811dc06b5b).

# Acceptance Criteria

I think for now, we just want to be able to address these in a prescribed way and be able to reuse the original source identifier. In these cases, do we need to / should we expect to be able to:

1. run an import to delete the fileset.
2. readd the fileset with the file.

# Screenshots / Video

<img width="1512" alt="Screenshot 2024-01-18 at 11 32 26 AM" src="https://github.com/scientist-softserv/utk-hyku/assets/2692416/5b899d2f-d66e-4326-80eb-1759c97d06a9">
<img width="1512" alt="Screenshot 2024-01-18 at 11 32 41 AM" src="https://github.com/scientist-softserv/utk-hyku/assets/2692416/73a3a529-5b58-400b-9c64-aeedd36e7f89">

**Comment by orangewolf** [comment]
@markpbaggett I'm closing this one because of the redo functionality.
