### ISSUE TITLE
Allow Streaming of Videos and Audio

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#6]
# Summary

Notch8 will work with UTK to select and implement an acceptable solution for this feature. This is currently on the roadmap for multiple projects, so there may be community work in motion that we can utilize for Hyku.

# Acceptance Criteria
- [ ] Serves audio and video files in a web player with support for closed captioning / transcripts with webVTT
- [ ] Can display a webVTT transcript for a video or audio object

# Screenshots/Videos

# Testing

# Notes

**Comment by jillpe** [comment]
completed in #175 and will be covered in #386
