### ISSUE TITLE
featured collection - 6 tile format

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#60]
# Summary
update the home page featured collections section per the figma wire frames

# Acceptance Criteria

- [ ] the featured collections section is changed to look like the screenshot below
- [ ] the collections link out appropriately

# Screenshots or Video
ref: https://www.figma.com/file/3JjoRJYmCrfoAcWhHu2Br4/UTK?node-id=388%3A789

![Image](https://user-images.githubusercontent.com/39319859/200660545-81f96048-c1ba-4922-b0bd-1bbf3a2f7e59.png)

**Comment by DiemBTran** [comment]
Linked items:

Relates to:

- [2] homepage themes / tenant
- EPIC: UTK Branding

**Comment by AKFosterDev** [comment]
## Summary
Custom styling of featured collections section for dc_repository theme

## Pull Request Ready for Review
[#250 - Featured collections section](https://github.com/scientist-softserv/utk-hyku/pull/250)

## Screencasts

### Full screen - logged out

https://user-images.githubusercontent.com/39319859/205372034-5eb7e388-a3c5-47ae-affa-82ded887cf71.mov

### Medium screen - logged out

https://user-images.githubusercontent.com/39319859/205401150-a44fb36f-f09f-4d8f-9ed7-ea7de384cef6.mov

### Small screen - logged out

https://user-images.githubusercontent.com/39319859/205401167-04e0b5d7-82db-4abb-accd-61c9a28493d5.mov

### Full screen - admin logged in

https://user-images.githubusercontent.com/39319859/205372897-a01fe8c5-638c-4d6c-a60f-76679a49230e.mov

## QA Instructions

- These changes only apply to the DC Repository theme - all other themes should have default styling
- Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- Feature flippers should be disabled for the following:
- [ ] Share work button
- [ ] Show featured works tab
- [ ] Show recently uploaded tab
- [ ] Show featured resercher

**Comment by AKFosterDev** [comment]
### QA Note

I disabled the above noted feature flippers and made 6 works featured. There is some issue with the responsive behavior due to the size of the placeholder thumbnails so I added images to the collections and now it is behaving correctly.

**Comment by ShanaLMoore** [comment]
This passes QA per the demo shown in the client meeting.

**Comment by ShanaLMoore** [comment]
test comment

**Comment by ShanaLMoore** [comment]
@ShanaLMoore test comment
