### ISSUE TITLE
Browse Collections - All Collections Grid View

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#61]
# Summary
Update the DC Repository home page browse collections section grid view per the figma wire frames

UTK colors: https://brand.utk.edu/standards/colors/

# Related Tickets
[Browse Collections - All Collections List View #61](https://github.com/scientist-softserv/utk-hyku/issues/61)
[Browse Collections - Filter Collections List Alphabetically #260](https://github.com/scientist-softserv/utk-hyku/issues/260)

# Acceptance Criteria
- [x] add section title 
- [x] add top buttons to section
- [x] populate a list of all collections
- [x] style grid view for collections per screenshot below
- [x] add scroll to section 
- [x] the browse collections section is changed to look like the screenshot below
- [x] the collections link out appropriately

# Screenshots or Video
ref: https://www.figma.com/file/3JjoRJYmCrfoAcWhHu2Br4/UTK?node-id=388%3A789

### grid view

![Image](https://user-images.githubusercontent.com/29311858/202317275-b65cdeb0-bcfe-4d1d-b6fd-28e5455eeb61.png)

**Comment by DiemBTran** [comment]
Linked items:

Relates to:

- [2] homepage themes / tenant
- EPIC: UTK Branding

**Comment by AKFosterDev** [comment]
## Summary
Custom theming for Browse Collections section grid view only

## Pull Request
[Browse Collections - All Collections Grid View #268](https://github.com/scientist-softserv/utk-hyku/pull/268)

## Screencasts
### Full Screen

https://user-images.githubusercontent.com/39319859/207181182-b1dba980-105c-43da-9a4f-b38ccc79f0fd.mov

### Medium Screen

https://user-images.githubusercontent.com/39319859/207181233-0f110846-82dd-4a7d-a780-c6bf531891ac.mov

### Small Screen

https://user-images.githubusercontent.com/39319859/207181273-da59b0fa-9f2d-4848-94b2-56ca6c269965.mov

## QA Instructions
- These changes only apply to the DC Repository theme - all other themes should have default styling
- Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- NOTE: The Grid view button is hard coded as active until the toggle functionality is complete on next ticket.
- Test on browsers - specifically scroll of section
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- Feature flippers should be _disabled_ for the following:
- [ ] Share work button
- Feature flippers should be _enabled_ for the following:
- [ ] Show featured works tab
- [ ] Show recently uploaded tab
- [ ] Show featured researcher

**Comment by AKFosterDev** [comment]
NOTE for QA:
The default thumbnail image is too small for the layout. Not sure what to do to fix this.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested on:

- [x] These changes only apply to the DC Repository theme - all other themes should have default styling
- [x] Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- [x] Test on browsers - specifically scroll of section
     - [x]  Chrome
     - [x]  Safari
     - [x]  Firefox
- [x] Feature flippers should be disabled for the following:
     - [x]  Share work button
- [x] Feature flippers should be enabled for the following:
     - [x]  Show featured works tab
     - [x]  Show recently uploaded tab
     - [x]  Show featured researcher
- [x] NOTE: The Grid view button `Diem's note: (as well as A-Z sort and Group/All Collections)` is hard coded as active until the toggle functionality is complete on next ticket #259, #260.
- [x] NOTE for QA: The default thumbnail image is too small for the layout. Not sure what to do to fix this. `Diem's note: At the smallest breakpoint, the default thumbnail pushes the collection title below the next thumbnail (0:35 in video)`

<details><summary>Scrolling on all 3 browsers work at all 3 breakpoint sizes</summary>

https://user-images.githubusercontent.com/29311858/207439741-12621245-4038-4ec2-acac-eef2e70beeeb.mp4
</details>

**Comment by AKFosterDev** [comment]
## Summary for Updated Work
Custom theming for Browse Collections section grid view only. Rework to properly display default thumbnails and long collection titles
- add flexbox to div
- update styles for default thumbnail and long collection titles

## Pull Request
[Browse Collections - All Collections Grid View Update #274](https://github.com/scientist-softserv/utk-hyku/pull/274)

## Screencasts
### Full Screen

https://user-images.githubusercontent.com/39319859/207474697-5fde767c-0b4e-4527-806e-3207fe1131ca.mp4

### Medium Screen

https://user-images.githubusercontent.com/39319859/207474732-7731ee42-444d-4798-ad53-7e8d04df7643.mp4

### Small Screen

https://user-images.githubusercontent.com/39319859/207474747-5598de3d-fcc3-4d02-9156-15bb8bfdfd8b.mp4

### X-Small Screen

https://user-images.githubusercontent.com/39319859/207474783-c5eee268-ab07-4ba0-83f1-af9dd4c422f7.mp4



## QA Instructions
- [ ] These changes should render the default thumbnail correctly.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested on:

- [x] These changes only apply to the DC Repository theme - all other themes should have default styling
- [x] Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- [x] Test on browsers - specifically scroll of section
     - [x]  Chrome
     - [x]  Safari
     - [x]  Firefox
- [x] Feature flippers should be disabled for the following:
     - [x]  Share work button
- [x] Feature flippers should be enabled for the following:
     - [x]  Show featured works tab
     - [x]  Show recently uploaded tab
     - [x]  Show featured researcher
- [x] NOTE: The Grid view button `Diem's note: (as well as A-Z sort and Group/All Collections)` is hard coded as active until the toggle functionality is complete on next ticket #259, #260.
- [x] NOTE for QA: ~~The default thumbnail image is too small for the layout. Not sure what to do to fix this.~~ Fixed with the latest code changes ･ᴗ･ 

<details><summary>Default thumbnails are now fixed and render correctly</summary>

https://user-images.githubusercontent.com/29311858/207954616-6c6c56e5-22fd-48d4-80b4-fedc08b3e5cd.mp4
</details>

**Comment by markpbaggett** [comment]
@AKFosterDev and @DiemBTran, grid view changes look good to me.  :shipit:
