### ISSUE TITLE
splash page for collections

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#62]
# Summary
ref
- #411 
- #7 

update the [public collections show page](https://ir.utk-hyku-staging.notch8.cloud/collections/c45887dc-1574-49a8-822e-c822c3ecac6d) per the figma wire frames (not the admin view version)

[wireframes](https://www.figma.com/file/3JjoRJYmCrfoAcWhHu2Br4/UTK?type=design&node-id=0-1&mode=design&t=w8xMFm6dTu7mnJAO-0)

# Acceptance Criteria

- [ ] the collections splash page is changed to look like the wireframe
- [ ] only the abstract, date (issued/created), subject, and creator metadata fields should show

# Screenshots or Video

![Image](https://user-images.githubusercontent.com/29311858/202317580-cf0431d7-c70c-4cdf-bca8-6f2f5ecc7738.png)

### grid view

![Image](https://user-images.githubusercontent.com/29311858/202317595-26f99cf2-75f8-4227-9956-1c779513a356.png)

# Testing Instructions
- Open a collection's show page
- Verify that it looks like the wireframes/above screenshot

**Comment by DiemBTran** [comment]
Linked items:

Relates to:

- [2] spike: how to handle theming for collections
- EPIC: UTK Branding

**Comment by DiemBTran** [comment]
Alisha - Aug 2022

---

this is currently blocked by #63 ([2] spike: how to handle theming for collections)

**Comment by jillpe** [comment]
no longer blocked

**Comment by jillpe** [comment]
SoftServ QA: Needs Rework

[Collection Show Page Tested](https://dc.utk-hyku-staging.notch8.cloud/collections/c93b530a-2edf-457c-9a56-e07084c6a862?locale=en&view=gallery)

* note the main image is based on the thumbnail for that collection

Items that look different than the wireframe:


All of the metadata is displayed. Wireframe only had description displayed
  <details><summary>Screenshots</summary>
  
  
  ![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/6e728821-b812-4e5a-8a13-49ede5160734)
  
  
  </details>
  

`Item number`, `creator`, and `last updated` display. Wireframe asks for `item number` and `last updated` to **not** display.
  <details><summary>Screenshots</summary>
  
  
  ![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/c755a9bf-e988-4e85-9396-9c78c99e189c)
  
  
  </details>

Search subcollections and works in this collection bar are left-aligned. Wireframe had it centered.
  <details><summary>Screenshots</summary>
  
  
  ![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/19f5f93d-fd85-4430-a622-a30da1b0c112)
  
  
  </details>

~~Additional views. Wireframes only wanted list or grid view options~~ (Update: This is not necessary, it is better to keep all of the functionality that is already there. See comments below)
  <details><summary>Screenshots</summary>
  
  
  ![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/0792d531-5526-471b-92a6-54eec9f161d7)
  
  
  </details>

**Comment by kirkkwang** [comment]
In client meeting on 8/1/23, it was discussed that only the abstract, date (issued/created), subject, and creator metadata fields should show

**Comment by kirkkwang** [comment]
> Additional views. Wireframes only wanted list or grid view options

@jillpe was there a comment somewhere that explicitly said they only want the list and grid view?  I'm trying to look for something that indicates this and we can definitely do it.  I just want to take the wireframes so literally that we hide something that didn't need to be hidden.

**Comment by ShanaLMoore** [comment]
To add in my two cents, as a general rule of thumb I don't think we should remove functionality from projects. Making it set to grid view only would remove options for them to view it in other ways.

**Comment by jillpe** [comment]
I was being knit-picky based on the wireframes. Both of you make good points, so I'm good to not hide the other options - I'll update my QA comment

**Comment by jillpe** [comment]
SoftServ QA: Pass



https://github.com/scientist-softserv/utk-hyku/assets/84697174/b3771702-6c23-49ae-8963-a3cce9586317
