### ISSUE TITLE
Workflow for 'non-admin' and 'admin' users

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#626]
## Summary
[Meeting notes 2024-04-09](https://docs.google.com/document/d/1jRGJ8elYl2OwFmCmIgP8n68t_4tZvfvZhScDoHwEHdg/edit)
This was a result of the discussion of the Groups and Roles in the client meeting 2024-04-09. Groups with Roles is no longer a requirement for this project. 

The required workflow does not require any approval workflow. Hyrax's standard "Default Workflow" should suffice for the purposes of the DL (previous requirements were for the IR). 

## Acceptance Criteria
- [ ] Admins can import/export only
- [ ] Admins can create new works that don't require approval 
- [ ] Non-admins can import/export only
- [ ] Non-admins can create new works that don't require approval

**Comment by markpbaggett** [comment]
So this is probably a dumb question, but one that I'm not sure about. How do we actually set up groups?  If I just go in to Hyku and setup a group called "Student," is that enough? Also, can any registered user import content or does that require special permissions?

**Comment by bkiahstroud** [comment]
Hi @markpbaggett, I can help answer these. 

> If I just go in to Hyku and setup a group called "Student," is that enough?

The only other steps for setting up the group itself would be: 
1. Adding users to the group 
2. Assigning roles to the group (optional) 

To grant the group deposit access to an Admin Set, you'll need to add the group name as a Participant: 

<details><summary>Screenshot 1</summary>

![Edit Admin Set Hyku 2024-04-26 at 10 22 06 AM](https://github.com/scientist-softserv/utk-hyku/assets/32469930/f17c4a1e-09dc-4725-953b-495253cc9e97)

</details>

> Also, can any registered user import content or does that require special permissions?

This depends on how your Admin Set is configured. I believe the default in Hyku (depending on your version) is that registered users cannot deposit. Changing this is simple, however, and can be done on an AdminSet-by-AdminSet basis. Under the same Participants tab as above, you'll see a button to says "Allow all registered users to deposit". If you click that, it will add a special group called "Registered Users" to the list and will allow them to deposit into the set: 

<details><summary>Screenshot 2</summary>

![Edit Admin Set Hyku 2024-04-26 at 10 25 48 AM](https://github.com/scientist-softserv/utk-hyku/assets/32469930/3298a422-c284-4dd2-99a7-a0f28c02bff0)

</details>

**Comment by jillpe** [comment]
Taking a new approach to the problem (outlined in #627). Closing this ticket as it is no longer relevant
