### ISSUE TITLE
[2] spike: how to handle theming for collections

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#63]
The client wants different collection show pages for each tenant.

There are 2 ways we might approach this:
1. follow our existing pattern and create a theme for this page
2. come up with a way to still have 2 separately designed pages, but without using themes

Have people in the community already handled this? Can we borrow from them?

### Notes
1) Add a page to the themes tab: https://qa.utk-hyku-staging.notch8.cloud/admin/appearance?locale=en#themes
2) Add to collection branding: https://qa.utk-hyku-staging.notch8.cloud/dashboard/collections/ea3affdc-a44a-414d-be3b-39bc9e37c303/edit?locale=en#branding

Efforts to contribute back. 
Users will have default collection them if we go with option 1.

**Comment by DiemBTran** [comment]
Linked items:

- [splash page for collections](https://gitlab.com/notch8/utk-hyku/-/issues/127)
- [EPIC: UTK Branding](https://gitlab.com/notch8/utk-hyku/-/issues/8)

**Comment by DiemBTran** [comment]
Alisha Aug 2022

---

ref: [this discussion](https://assaydepot.slack.com/archives/G031E2P1RJM/p1659734793637819) about theming the collections show page

**Comment by AKFosterDev** [comment]
[LeaAnn & Aprils Theming Talk](https://www.youtube.com/live/F3G1IIZwGNc?feature=share&t=8544)
[Hyku Theming Wiki](https://github.com/samvera/hyku/wiki/Creating-Custom-Themes)

Based on the above Slack discussion: 

Right now there is home page, show page and search page themes. It would be just adding collection show page theme.

That would require wireframe, adding it to the form, add a collection_show_theme.yml file, adding it to the inject_theme_views method, The html and css will need to be in a folder named after the theme

**Comment by jillpe** [comment]
closed - no longer in scope 2023-04-19
