### ISSUE TITLE
Sorting importers by 'last run' does not work

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#633]
## Summary
I'm seeing this error when attempting to sort by last run or next run. Name and status sort fine.

![Image](https://github.com/scientist-softserv/utk-hyku/assets/84697174/0b4dcd9e-c05a-4bd6-bc89-6efdbafb1192)

## Acceptance Criteria
- [ ] The importer can be sorted by 'last run' or 'next run'

**Comment by ShanaLMoore** [comment]
dupe of https://github.com/scientist-softserv/utk-hyku/issues/644
