### ISSUE TITLE
search results

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#64]
# Summary
update the search results page per the figma wire frames

# Acceptance Criteria

- [x] the search results page is changed to look like the screenshot below
- [x] the links are linked appropriately
- [x] facets color is smoky

# Screenshots or Video
ref: https://www.figma.com/file/3JjoRJYmCrfoAcWhHu2Br4/UTK?node-id=388%3A789

![Image](https://user-images.githubusercontent.com/29311858/202317918-864ed65a-47a9-4617-8057-2133609d3583.png)

**Comment by DiemBTran** [comment]
Linked items:

Relates to:

- EPIC: UTK Branding

**Comment by AKFosterDev** [comment]
## Summary
- implement custom theming for search results page for DC Repository theme per Figma design

## Related Pull Request
[#306](https://github.com/scientist-softserv/utk-hyku/pull/306/)
[#311](https://github.com/scientist-softserv/utk-hyku/pull/311) - Bug fix

## Screencasts
### Empty Search Results

**List View - Full Screen**

https://user-images.githubusercontent.com/39319859/213560604-1c813efa-1346-4fbb-95ef-c880fda55611.mp4

**List View - Screen 991px**

https://user-images.githubusercontent.com/39319859/213560649-c438eb01-8353-4a48-bac2-f07b07ccbaa4.mp4


**List View - Screen 767px**

https://user-images.githubusercontent.com/39319859/213560674-7eb44788-1ef9-47d0-8052-c236d40fae4d.mp4


**Grid View - Full Screen**

https://user-images.githubusercontent.com/39319859/213560715-59c7f9aa-e245-49ee-929e-0b9ef2a7d8b9.mp4


**Grid View - Screen 991px**

https://user-images.githubusercontent.com/39319859/213560819-02847d08-1659-48f7-adb4-caf37fed3e73.mp4


**Grid View - Screen 767px**

https://user-images.githubusercontent.com/39319859/213560917-f9217cac-92f7-4381-9997-c8bfcd074f2e.mp4

**Grid View - XS Screen**

https://user-images.githubusercontent.com/39319859/213561354-8669e25d-cf90-492e-937c-b2945b43d140.mp4


### View All Collections Search Results

**List View - Full Screen**

https://user-images.githubusercontent.com/39319859/213561544-2389b587-8ac0-41c9-8662-a47f429de3c8.mp4

**List View - Screen 991px**

https://user-images.githubusercontent.com/39319859/213561697-45ad0b03-ba07-4773-8ce6-6b95d550c1e8.mp4

**Grid View - Full Screen**

https://user-images.githubusercontent.com/39319859/213561756-14abc3c1-8d80-464d-bf2e-001e00e9c70d.mp4

**Grid View - Screen 991px**

https://user-images.githubusercontent.com/39319859/213561862-7104d938-1a3f-4908-bc92-a80f9235c401.mp4


### Works in a Collection Search Results

**List View - Full Screen**

https://user-images.githubusercontent.com/39319859/213561977-0124b01b-0054-4c4c-9474-375ce291d522.mp4


**Grid View - Full Screen**

https://user-images.githubusercontent.com/39319859/213562033-98c554e9-957e-4132-b7fc-5e6b62d4261a.mp4


## QA Instructions
- These changes only apply to the DC Repository theme - all other themes should have default styling
- Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- In Admin dashboard under Appearance/Theme/DC Repository the DC View should be selected from the Search Results Page Theme dropdown (NOTE: the wireframe image will be addressed on a subsequent ticket)
![Screenshot 2023-01-19 at 1 18 32 PM](https://user-images.githubusercontent.com/39319859/213563641-441020a5-4c9a-480a-bf71-d6650dd83cfa.JPG)
- Grid View
- List View
- General breakpoints
- full screen
- 991px
- 767px

**Comment by AKFosterDev** [comment]
After a quick QA on staging, I noticed that some of the styling has affected the default search results page for gallery view and list view and it should not. I will address this once this work is QA'd to make sure there aren't other things that need to be updated.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested on:
- https://dc.utk-hyku-staging.notch8.cloud/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=
- https://dc.utk-hyku-staging.notch8.cloud/catalog?locale=en&q=&search_field=all_fields&utf8=%E2%9C%93&view=gallery
- https://dc.utk-hyku-staging.notch8.cloud/admin/appearance?locale=en#themes

<details><summary> DC search results theming is functional for: list, grid, and all breakpoints. Clicking items leads to correct work show pages. Filters and filter reset works.</summary>



https://user-images.githubusercontent.com/29311858/214117145-6bc2eeee-3872-4de0-8d15-2e3884277853.mp4

</details>

**Comment by AKFosterDev** [comment]
## Summary
Prior to this commit the structure for list and gallery view of search results for DC view search results page was rendering for all themes. This commit conditionally renders for the DC view - dc_repository_search if selected and renders default code for other themes if they are selected.

## Related PR
[#317 - i64 Search Results Page - Update to use conditional rendering](https://github.com/scientist-softserv/utk-hyku/pull/317)

## QA Instructions
- These changes only apply to the DC Repository theme - all other themes should have default styling
- Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- [x] From admin dashboard appearance/themes select "default home" and "list view" from the dropdown for Search Results Page Theme - styling should be default
- [x] From admin dashboard appearance/themes select "DC Repository" and "DC view" from the dropdown for Search Results Page Theme - styling should be the same as screencasts on [PR #306](https://github.com/scientist-softserv/utk-hyku/pull/306)

**Comment by AKFosterDev** [comment]
I tested this out on staging but search isn't working when Default home and List view are selected getting error in screenshot below. So this setting is not QAable right now.

Search working fine when DC Repository and DC View selected and view rendering correctly.

Locally both configurations were working correctly.

![image](https://user-images.githubusercontent.com/39319859/214454026-60f68caa-28a7-4207-8108-b460ac3e990c.png)

**Comment by AKFosterDev** [comment]
The search seems to be working correctly this morning on staging.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested on:
- https://dc.utk-hyku-staging.notch8.cloud/admin/appearance?locale=en#themes
- https://dc.utk-hyku-staging.notch8.cloud/catalog?locale=en&per_page=20&q=test&search_field=all_fields&sort=system_create_dtsi+asc&view=list

<details><summary>Tested with default home/list view, and DC Repository/DC themes. Appropriate default and custom styling display properly</summary>



https://user-images.githubusercontent.com/29311858/214683479-a4179f16-31d6-426c-abf4-ea932c3c37cd.mp4

</details>

**Comment by AKFosterDev** [comment]
Change facets text color added as a new acceptance criteria.

**Comment by AKFosterDev** [comment]
## Summary
On the search results page the facets heading color was globe blue and it should have been smokey grey. This PR corrects this.

## Related PR
[#327 Search Results - Update facet title font color](https://github.com/scientist-softserv/utk-hyku/pull/327)

## Screenshots

**Before**
![before](https://user-images.githubusercontent.com/39319859/217390970-481187ba-2be1-41e5-915f-b6e41cdcf832.JPG)

**After**
![after](https://user-images.githubusercontent.com/39319859/217390986-601096d3-6074-4b0f-9872-63b1de0659fb.JPG)
![after clicked](https://user-images.githubusercontent.com/39319859/217391000-048c3696-fe0c-430b-8b58-8342bd221dc0.JPG)

## QA Instructions
- These changes only apply to the DC Repository theme - all other themes should have default styling
- Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- In Admin dashboard under Appearance/Theme/DC Repository the DC View should be selected from the Search Results Page Theme dropdown
- [ ] On the search results page - Facets font color is dark grey like the above screenshot

**Comment by AKFosterDev** [comment]
## Summary
On the search results page the facets value more_facets_link has the incorrect font size. This PR corrects this.

## Related PR
[#328](https://github.com/scientist-softserv/utk-hyku/pull/328)

## Screenshots

**Before**
![before](https://user-images.githubusercontent.com/39319859/217598291-f27db2a2-9818-41a6-ab20-1bed9a5b9aa1.JPG)

**After**
![after](https://user-images.githubusercontent.com/39319859/217598312-37c8122a-8fee-45bc-8aee-235875d87838.JPG)


## QA Instructions
- These changes only apply to the DC Repository theme - all other themes should have default styling
- Test on staging at https://dc.utk-hyku-staging.notch8.cloud/
- In Admin dashboard under Appearance/Theme/DC Repository the DC View should be selected from the Search Results Page Theme dropdown
- [ ] On the search results page - Facets "more >>" is the same font size as the other menu items like the above screenshot

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://dc.utk-hyku-staging.notch8.cloud/catalog?locale=en&q=&search_field=all_fields&utf8=%E2%9C%93&view=list

<details><summary> Facets heading is smokey gray, facet options are globe blue, hover over facet options is magenta (?), and "more >>" is the correct font size</summary>

![Index Catalog Digital Collections 2023-02-08 at 1 42 08 PM](https://user-images.githubusercontent.com/29311858/217658096-a89788c0-dab1-414b-bef9-01db030f5be8.jpg)
</details>

**Comment by josh-morgan117** [comment]
Looks good!
