### ISSUE TITLE
IIIF Viewer bug (Search API) that displays "No matches found" upon clicking on any image record

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#651]
## Summary
reference: https://docs.google.com/spreadsheets/d/1XbfCosfI_P3N2JVYldD28p6Ca6AxNRbAOKbOcp1GRgo/edit?gid=0#gid=0

[Example link](https://digitalcollections.lib.utk.edu/concern/images/fa040515-80c5-43d3-8b9c-54cdfd8f970b)
[Example screenshot](https://drive.google.com/file/d/1oMMImouB-33baLXqK0TBN1LKj0ahsnHm/view?usp=drive_link)

The search API shouldn't be initiated unless a search is entered

## Acceptance Criteria
- [ ] The IIIF viewer search is only initiated if a search is entered

**Comment by orangewolf** [comment]
we've fixed this in other repos - asked folks to find out where and then copying the solution is probably the right path forward here

**Comment by jillpe** [comment]
2024-08-06 confirmed in client meeting no longer a priority
