### ISSUE TITLE
Ability to pull OAI-PMH metadata

### ISSUE THREAD

**Issue by mlhale7** [notch8/utk-hyku#665]
## Summary
reference: https://github.com/scientist-softserv/utk-hyku/issues/664

OAI can be pulled with standard tools

## Acceptance 
- [ ]  Ability to pull OAI records in oai_dc or mods using standard command line tools or Repox
- [ ]  Ability to see individual records in the browser by navigating https://digitalcollections.lib.utk.edu/catalog/oai

**Comment by jillpe** [comment]
duplicate of #664
