### ISSUE TITLE
In viewer highlighting for Books

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#68]
# Summary
UTK wants in viewer highlighting on books, in which the search goes to the correct page.

# Acceptance Criteria

- [ ] Books have in viewer highlighting
- [ ] Search goes to the correct page

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by DiemBTran** [comment]
Linked items:

- In App PDF viewing

**Comment by jillpe** [comment]
covered in #358
