### ISSUE TITLE
Sorting (page order)

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#70]
# Summary
The easiest way to do this is to have a metadata property that is ordered. Hyrax doesn’t have a solid ordering system in place. This also happens on complex objects
UTK will need ordering on complex objects, books…

# Acceptance Criteria

- [ ] Complex objects has ordering
- [ ] Books has ordering

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
covered by #358
