### ISSUE TITLE
Create thumbnails for intermediateFile but not PreservationFile

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#71]
# Summary
Thumbnail generation should always be done against the pcdmuse:IntermediateFile. 

Create a property in fileset to designate intermediateFile, allow to be mapped in import

# Accepted Criteria

- [ ] Thumbnails are created for intermediateFile
- [ ] Derivatives are not created for pcdmuse:PreservationFile

# Screenshots and Videos

# Testing Instructions

# Notes

**Comment by jillpe** [comment]
related to #343
