### ISSUE TITLE
navPlace mappings

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#73]
# Summary
UTK would like location information to be shared as a navPlace extension in their IIIF manifests.

Mapping is from a field called spacial with a multi value range. One is URI and one is cartographic information. 

We need to figure out mapping for which is longitude and latitude. We may need to make these into their own field, but will need to have a label of what the place is (Property) or we may be able to rely on the Geo Names URI and have it pull the latitude and longitude. 

https://utk-iiif-cookbook.readthedocs.io/en/latest/future/navPlace.html 

# Acceptance Criteria

- [ ] navPlace extension shares location information
- [ ] Mapping for longitude and latitude is established

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by DiemBTran** [comment]
Kirk Oct 2022

---

https://iiif.io/api/extension/navplace/

**Comment by jillpe** [comment]
no longer in scope
