### ISSUE TITLE
Show rights statements in viewer

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#74]
# Summary
UTK would like rights statements to be actionable and render the appropriate badge and usage information to the user in both the IIIF viewer (when metadata is on) and in their metadata display below.

https://rightsstatements.org/en/documentation/assets.html

# Acceptance Criteria

- [ ] Rights statements are actionable
- [ ] Rights statements render the appropriate badge and usage info in IIIF viewer
- [ ] Rights statements render the appropriate badge and usage info in their metadata display

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
no longer in scope 2023-04-19
