### ISSUE TITLE
All pages (books) should have OCR and HOCR

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#76]
# Summary
Historically, UTK has used Tesseract to generate this. They do not have a strong opinion about how to generate this though. Community members have been using Tesseract for their gems as well.

Initial ingest files do already have this, but they would like a system that supports OCR and HOCR on new files in place.

# Acceptance Criteria

- [ ] OCR and HOCR are implemented on new files

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
covered in #358 and #343
