### ISSUE TITLE
Viewer (and manifest) can handle unordered works/files

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#78]
# Summary
A page object may have a property indicating that it is unordered that should be translated to the corresponding IIIF presentation manifest as such.

# Acceptance Criteria

- [ ] Viewer and manifest can handle unordered works/files

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
order matches what is on the show page
