### ISSUE TITLE
Get estimate for changing book files into a downloadable PDF

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#79]
# Summary
Can we separate out the processes to generate them but not have them done at time of ingest.  

# Acceptance Criteria

- [ ] Estimate for bringing in PDF in viewer generation is complete and presented to UTK

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
covered in #99
