### ISSUE TITLE
Compound Object: The parent work has an association to all of the children

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#82]
# Summary
Since member works may stand alone elsewhere in the repository, the member works do not have pcdm:memberOf properties that point at the parent object. Instead, the parent work has a pcdm:hasMember property that points at child works

# Acceptance Criteria

- [ ] The parent work has an association to all of the children

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by crisr15** [comment]
Shana: 
Per the client meeting, the client is ok with the default behavior as long as it gives them the desired outcome.

**Comment by jillpe** [comment]
closed, will be covered in #101
