### ISSUE TITLE
Test: Image Work Types

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#90]
# Summary
Over-arching Goal: Test Image work type against UTK's requirements.

# Acceptance Criteria

- [ ] An image work may have other filesets of any mime-type available for download.
- [ ] Image works should be displayed in a IIIF viewer such as Universal Viewer, Clover IIIF, or Mirador. 
- [ ] Item should pop out into a new window in location-based viewer
- [ ] Rights statements to be actionable and render the appropriate badge and usage information to the user in both the IIIF viewer (when metadata is on) and in our metadata display below
- [ ] Users should be able to easily download the primary filesets.
- [ ] Like other work types, image works should be represented by an OAI-PMH record based on its metadata application profile. The work should be a record in an OAI set for each corresponding collection to which the work belongs.

# Screenshots or Video
Screenshots available via the [link](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/2_image.html)

# Testing Instructions

# Notes
[UTK's Image works type](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/2_image.html)

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
covered in #47
