### ISSUE TITLE
Test: Audio Work Types

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#92]
# Summary
Over-arching Goal: Test Audio work type against UTK's requirements.

# Acceptance Criteria

- [ ] Audio works have closed-captioning or transcript files and may have them in multiple languages.
- [ ] Audio works should be rendered to the user in a IIIF presentation viewer like IIIF React Media Player, Universal Viewer, Clover IIIF, or Mirador.
- [ ] Closed captioning files and structural metadata should be transformed into IIIF structures and ranges.
- [ ] The caption is a navigable transcript
- [ ] Item should pop out into a new window in location-based viewer
- [ ] Rights statements to be actionable and render the appropriate badge and usage information to the user in both the IIIF viewer (when metadata is on) and in our metadata display below
- [ ] Users should be able to easily download the primary filesets.
- [ ] Audio works should be represented by an OAI-PMH record based on its metadata application profile. The work should be a record of an OAI set for each corresponding collection to which the object belongs. 

# Screenshots or Video
Screenshots are available via the [link](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/4_audio.html)

# Testing Instructions

# Notes
[UTK's Audio Works Type](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/4_audio.html)

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
covered in #47
