### ISSUE TITLE
Test: PDF Work Types

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#93]
# Summary
**Over-arching Goal:** Test Newspaper work type against UTK's requirements.

# Acceptance Criteria

- [ ] A PDF may also be converted on demand into a set of images making up each canvas.
- [ ] After converted on demand, work will be displayed in a IIIF viewer on the work page.

# Screenshots or Video
Screenshots available via the [link](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/5_pdf.html)

# Testing Instructions

# Notes
[UTK's PDF work type](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/5_pdf.html)

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
covered in #47
