### ISSUE TITLE
Test: Books and Pages Work Types

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#94]
# Summary
Over-arching Goal: Test Books and Pages work type against UTK's requirements.

# Acceptance Criteria

- [ ] All books should have an auto-generated PDF that is searchable and available for download.
- [ ] All pages should have OCR and HOCR.
- [ ] A book work may have other filesets of any mime-type available for download.
- [ ] Book works should be displayed in a IIIF viewer such as Universal Viewer, Clover IIIF, or Mirador with a “paged” / “2-up” behavior by default. 
- [ ] Item should pop out into a new window in location-based viewer
- [ ] Rights statements to be actionable and render the appropriate badge and usage information to the user in both the IIIF viewer (when metadata is on) and in our metadata display below.
- [ ] Users should be able to easily download the primary filesets.
- [ ] book works should be represented by an OAI-PMH record based on its metadata application profile. The work should be a record in an OAI set for each corresponding collection to which the work belongs.

# Screenshots or Video
Screenshots can be accessed via the [link](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/6_books_and_pages.html)

# Testing Instructions

# Notes
[UTK's books and pages work type](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/6_books_and_pages.html)

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
covered in #47
