### ISSUE TITLE
Test: Compound Object Work Types

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#95]
# Summary
Over-arching Goal: Test Newspaper work type against UTK's requirements.

# Acceptance Criteria

- [ ] All compound objects’ individual works’ filesets should be available for download.
- [ ] Book works within a compound object work should have OCR and HOCR.
- [ ] All audio and video works within a compound object work may have 0-n closed-captioning / subtitle files that should be associated with it in the viewer.
- [ ] Compound object works should be displayed in a IIIF viewer such as Universal Viewer, Clover IIIF, or Mirador with an individuals behavior at the manifest level.
- [ ] Item should pop out into a new window in location-based viewer
- [ ] Rights statements to be actionable and render the appropriate badge and usage information to the user in both the IIIF viewer (when metadata is on) and in our metadata display below.
- [ ] Users should be able to easily download the primary filesets.
- [ ] compound works should be represented by an OAI-PMH record based on its metadata application profile. The work should be a record in an OAI set for each corresponding collection to which the work belongs. Compound objects should also be represented in collections in which they have a pcdm:memberOf relationship.

# Screenshots or Video
Screenshots available via the [link](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/7_compound_objects.html)

# Testing Instructions

# Notes
[UTK's Compound Objects Recipe](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/7_compound_objects.html)

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
covered in #47
