### ISSUE TITLE
📎 SOW: Newspapers

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#96]
# Summary
UTK would like their Newspaper work type to meet their work type requirements (see notes section) and be available for their users.

# Acceptance Criteria
- [ ] As an admin user, I can import newspaper work types and the metadata is imported and saved in the correct format
- [ ] As a user I can view a newspaper work's images in the UV
- [ ] As a user, I can search for ocr in the UV and it appears highlighted (alto)
- [ ] IntermediateFile at the issue level is served in the viewer for Newspaper work types

# Screenshots or Video

# Testing Instructions

# Notes
[UTK's Newspaper Work Type](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/8_newspapers.html)

- Are the alto files already created? Or will we need to generate these?

**Comment by markpbaggett** [comment]
@jillpe  This looks good to be in terms of scope of work.

Here is our understanding of this:

We need to be able to add newspapers as "title" > "volume" > "issue / date".  We have no article level metadata and our structured text is not at the article level.  Alto is page by page and not broken into articles.

**Comment by jillpe** [comment]
Schedule off set meeting to discuss the structure of newspapers. UTK does not think this will be as complicated as they were thinking. Think we can avoid using the newspaper gem

**Comment by jillpe** [comment]
[Audit Notes from 8/2023](https://github.com/scientist-softserv/utk-hyku/issues/529)

**Newspaper**

Comments from Mark:

> think we should just keep things simple with the newspaper title being a colleciton, the volume being a collection, and each issue just being something close to a book except with alto xml instead of hocr and ocr for each page.  i think if we do that, things should be much easier for you all as it’s essentially the same as book just with the ocr done a slightly different way.

> 
To Do:
- Need to verify this work type will work through derivative rodeo

[Sample Files for Testing](https://drive.google.com/file/d/191P6hRpUxrWsBqVV5dALR3YW4YS7LZhJ/view?usp=sharing)

**Comment by jillpe** [comment]
@markpbaggett this will be taken care of with migrations
