### ISSUE TITLE
Audio and Video: IIIF Recipe

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#98]
# Summary
ref
- #409 
- #391 

Over-arching Goal: Align IIIF manifests for audio with UTK's requirements.

UTK requires additional functionality in their IIIF Manifest to allow in viewer experience and use of the manifest in other applications.

This ticket builds off of the base IIIF manifest Recipe.

# Acceptance Criteria

- [ ] The items property of the manifest for a **Video** has one canvas that points at the access proxy of the video.
- [ ] The items property of the manifest for an **Audio** work has one canvas that points at the PROXY_MP3 datastream.
- [ ] The Canvas should have id, type, label, thumbnail, width, height, duration, items, and annotations properties following the IIIF Presentation v3 specification.
- [ ] Audio works that have one or more subtitle or closed captioning file are added as AnnotationPages in the annotations property.The TRANSCRIPT datastream is reserved for English and the TRANSCRIPT-ES datastream is reserved for Spanish

# Screenshots or Video
Screenshots for audio can be accessed via the [link](https://utk-iiif-cookbook.readthedocs.io/en/latest/contents/audio.html#iiif-manifest)

Screenshots for video can be accessed via the [link](https://utk-iiif-cookbook.readthedocs.io/en/latest/contents/video.html#iiif-manifest)

# Testing Instructions

# Notes
[Audio IIIF Recipe](https://utk-iiif-cookbook.readthedocs.io/en/latest/contents/audio.html#iiif-manifest)

[Video IIIF Recipe](https://utk-iiif-cookbook.readthedocs.io/en/latest/contents/video.html#iiif-manifest)

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
related to #47

**Comment by kirkkwang** [comment]
Closing this old ticket, only thing that needs work is getting thumbnails for A/V works, which is tracked by #215
