### ISSUE TITLE
Books and Pages: IIIF Recipe

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#99]
# Summary
Over-arching Goal: Align IIIF manifests for Books and Pages with UTK's requirements.

UTK requires additional functionality in their IIIF Manifest to allow in viewer experience and use of the manifest in other applications.

This ticket builds off of the base IIIF manifest Recipe.

# Acceptance Criteria

- [ ] In the items property, each Page work is a Canvas.
- [ ] Each Canvas has the following properties: id, type, label, width, height, thumbnail, items, and seeAlso.
- [ ] The items property should have 1 AnnotationPage with 1 Annotation. 
- [ ] The Annotation should have a motivation of painting based on the JP2 datastream that targets the Canvas.

# Screenshots or Video
Screenshots can be accessed via the [link](https://utk-iiif-cookbook.readthedocs.io/en/latest/contents/books.html#iiif-manifest)

# Testing Instructions

# Notes
[Books and Pages IIIF Recipe](https://utk-iiif-cookbook.readthedocs.io/en/latest/contents/books.html#iiif-manifest)

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
related to #47

**Comment by jillpe** [comment]
Closed - ticket created in first iteration of project and no longer relevant

**Comment by jillpe** [comment]
Closed - ticket created in first iteration of project and no longer relevant
